.editorconfig
.eslintrc.json
.markdownlint.json
README.md
package-lock.json
package.json
src/_vars.scss
src/app.scss
src/components/Header/header.scss
src/components/Nav/components/NavAvatar/nav-avatar.scss
src/components/Nav/nav.scss
src/services/activity.js
src/services/auth.js
src/services/http.js
src/services/session.js
src/services/storage.js
src/views/About/about.scss
src/views/About/index.js
src/views/ActivitiesAll/activities-all.scss
src/views/ActivitiesAll/components/ActivityGrid/activity-grid.scss
src/views/Help/help.scss
src/views/Help/index.js
src/views/Login/login.scss

- add Sass and Markdown linting
- add pre-commit hook that runs linting scripts before each commit, preventing a commit with linter errors
- add VS Code extension recommendations for Sass and Markdown linters

Add linting

---

src/services/session.js
src/services/user.js

There were a few errors in the JSDoc that were causing the precommit hook to fail.

Fix session and user service JSDoc

---

.vscode/launch.json
src/app.js
src/app.scss
src/components/Error/index.js
src/services/auth.js
src/services/error.js
src/services/http.js
src/services/user.js
src/views/ActivitiesAll/index.js
src/views/Home/components/CLWCredits/index.js
src/views/Home/components/ChapelProgress/index.js
src/views/Home/components/DaysLeft/index.js
src/views/Home/index.js
src/views/Login/index.js

- Fix CL&W credits chart bugs
- rename component to match title: `ChapelProgress` to `CLWCredits`
- change chart column size on medium screen to fill the space better
- display CL&W credits chart even when there are zero credits This was done by setting a default `required` value of `30`, which will be correct for the majority of students, and will not bother users who do not have a CL&W credit requirement.
- Improve component error handling
Now, many of the components that use data from the backend will throw an error if any of their data requests fail. At the moment, these errors are handled in two ways: 1. if the error is an authentication error, the user is redirected to the login view 2. otherwise, the error is displayed using `GordonError` This error handling is provided by the …

Remove token refresh

---

package-lock.json
package.json
src/services/cms.js
src/views/Home/components/Carousel/carousel.scss
src/views/Home/components/Carousel/index.js
src/views/Home/index.js

Home carousel

---

src/views/Orientation/index.js

Using variables instead of hard data, setting all the variables outside of the HTML, added comments, and added official descriptions courtesy of Chris Carlson.

Orientation Roadmap Updates

---

README.md

updated readme file to include instruction on how to connect back end to the the front end.

how to connect back end to front end

---

README.md
src/views/About/about.scss
src/views/About/index.js
src/views/Help/index.js

I messed with the formatting on the About and Help pages. Now they are easier to read.

Change some formatting

---

src/services/activity.js

- getSpecificActivity was doing the same thing as get and it's comments were confused.
- I replaced the name "get" with "getActivity" just to be more descriptive.

Minor changes to activity functions. Removed getSpecificActivity.

---

src/views/About/index.js
src/views/ActivityProfile/components/Membership/components/MemberDetail/index.js
src/views/Events/components/EventItem/index.js
src/views/Help/index.js
src/views/Profile/index.js

Reviewed index.js files to correct spelling mistakes and replace special characters (presumably from cut-and-past from MS Word) with HTML special character codes.  Also corrected spelling of "unsername" variable in ./views/Profile/index.js.

Spelling and special character corrections in index.js files

---

src/views/Profile/index.js

Just a small fix to the previous pull request that implemented the public profile view

removed extra home card, added home info pack in for profs

---

src/components/Header/components/NavAvatarRightCorner/index.js
src/components/Header/components/NavAvatarRightCorner/nav-avatar-right-corner.scss

- Added drop-shadow animation
- Fixed handling of non-square images; they now fill the avatar circle, so it looks nicer
- Avatar now properly refreshes when you change your profile picture

Tweaks to Avatar

---

src/services/user.js
src/views/MyProfile/index.js

Fixed another bug where icons linking to invalid profiles were displayed if none had ever been entered and made one other change to linkedIn to be less strict

found and fixed bug that displayed empty links on MyProfile

---

src/components/Nav/components/NavAvatar/index.js
src/components/Nav/components/NavAvatar/nav-avatar.scss

Fix left margin of nav-avatar text

---

src/components/Header/header.scss
src/components/Header/index.js

Make hamburger menu icon white to match title

---

src/components/Header/components/PeopleSearch/index.js
src/components/Header/components/PeopleSearch/people-search.scss
src/components/Header/header.scss

It animates (width and drop shadow) on focus.

New Search Bar!

---

src/components/ActivityList/index.js
src/components/Header/components/PeopleSearch/people-search.scss
src/services/membership.js
src/services/user.js
src/views/MyProfile/index.js

Users can now hide/make public their individual memberships on their profile via a toggle button.

My profile involvement list2

---

src/views/ActivityProfile/components/Membership/components/MemberDetail/index.js
src/views/ActivityProfile/components/Membership/components/RequestDetail/index.js
src/views/ActivityProfile/components/Membership/index.js
src/views/ActivityProfile/index.js
src/views/Events/components/EventItem/index.js
src/views/Events/index.js
src/views/Login/index.js
src/views/MyProfile/Components/LinksDialog/index.js
src/views/MyProfile/index.js
src/views/Transcript/index.js

modified:   src/views/ActivityProfile/components/Membership/components/MemberDetail/index.js
modified:   src/views/ActivityProfile/components/Membership/components/RequestDetail/index.js
modified:   src/views/ActivityProfile/components/Membership/index.js
modified:   src/views/ActivityProfile/index.js
modified:   src/views/Events/components/EventItem/index.js
modified:   src/views/Events/index.js
modified:   src/views/Login/index.js
modified:   src/views/MyProfile/Components/LinksDialog/index.js
modified:   src/views/MyProfile/index.js
modified:   src/views/Transcript/index.js

Edit appearance of buttons affected by the upgrade

---

src/views/Profile/index.js

- Now you can search for multiple people in a row without refreshing

Fix people search

---

src/services/user.js
src/views/MyProfile/index.js
src/views/Profile/index.js

The Public Profile now has an alphabetized Involvements List, and it also looks consistent with MyProfile.

Alphabetized public profile involvements, matched UI to myProfile

---

public/web.config
scripts/deploy.sh

Some more testing of Travis-CI to find out where it puts files when executing ```npm run build```

Modify deployment script to print list of files

---

README.md

Documentation includes names of servers and info about the web.config file

Add server info documentation to README.md

---

src/components/MyProfileActivityList/index.js
src/components/ProfileList/index.js

Gray out fields when made private

---

src/components/MyProfileActivityList/index.js
src/components/ProfileList/index.js
src/components/ProfileList/profileList.scss
src/services/activity.js
src/services/membership.js
src/views/MyProfile/index.js

Fixes issue #229 
When you are in a secret involvement, there will no longer be a toggle. Instead it will be a lock icon, signifying to the user that they can't change whether this is displayed or not (it just will _not_ be).
Mobile view:
Desktop:

Private Involvements on MyProfile (3)

---

src/app.js
src/components/Header/components/NavAvatarRightCorner/index.js
src/components/Header/components/NavAvatarRightCorner/nav-avatar-right-corner.scss
src/components/Header/components/PeopleSearch/index.js
src/components/Header/components/PeopleSearch/people-search.scss
src/components/Header/index.js
src/components/Nav/components/NavLinks/index.js
src/components/Nav/components/NavLinks/nav-links.scss
src/components/Nav/index.js
src/components/Nav/nav.scss
src/components/ProfileList/index.js

Fixes issue #233 
Right Corner Navatar is gone, those menu options are now in the NavDrawer.
**Search bar:**
(351 just under xs)
(399)
(951 just under md)
(999)
(every size above 1000)

Remove duplicate Navatar on mobile (2)

---

src/views/MyProfile/index.js

Add snackbar messages to photo options dialog

---

src/components/ProfileList/index.js

Fixes issue #237 
It works now :')

Fix one state variable name & mobile toggle works (3)

---

src/components/Header/components/NavAvatarRightCorner/index.js
src/components/Header/components/PeopleSearch/index.js
src/components/Nav/components/NavLinks/index.js
src/routes.js
src/views/Feedback/feedback.scss
src/views/Feedback/index.js

Added a Google form to a new feedback page.
The Google account for the results is gordon360dev@gmail.com
The search text field was updated based on Dr. Tuck and Stephen's suggestion.

added feedback page, updated people search text

---

src/components/ProfileList/index.js

Made student id grayed out

---

src/components/Header/components/PeopleSearch/people-search.scss

people search suggestions now lines up with search bar 
Added bottom padding to search suggestions

People search

---

src/services/auth.js
src/services/storage.js
src/services/user.js
src/views/Login/index.js

Remove unnecessary console.log statements

---

src/components/ProfileList/index.js
src/views/MyProfile/index.js

Remove snackbar from mobile phone toggle, add check mark (1)

---

src/views/MyProfile/Components/LinksDialog/index.js
src/views/MyProfile/index.js

- Make snackbar only show up for hide/show image (not needed for reset/upload because change is immediately visible)
- Fix slightly wonky margins underneath social media dialog action buttons

Tweak snackbar and social media link dialog margins

---

src/views/MyProfile/Components/LinksDialog/index.js
src/views/MyProfile/index.js

Fix social media links dialog UI (1)

---

public/index.html

Updated font code key per Chris Hansen's suggestion. Hopefully this will fix the font error in production.

updated font key for master branch

---

src/views/Login/index.js

This popup message only appears on Internet ~~Exploder~~ Explorer.

Add popup message for Internet Explorer

---

src/components/Header/components/NavAvatarRightCorner/index.js

Fix avatar tooltip so it doesn't stick (2)

---

src/views/Home/components/CLWCreditsDaysLeft/CLWChart.scss
src/views/Home/components/CLWCreditsDaysLeft/index.js

Display current number of chapel credits in center of doughnut

---

package.json
src/components/Header/index.js
src/components/Nav/components/NavLinks/index.js
src/routes.js
src/services/goStalk.js
src/services/people-search.js
src/views/Login/index.js
src/views/MyProfile/index.js
src/views/PeopleSearch/components/PeopleSearchResult/index.js
src/views/PeopleSearch/components/PeopleSearchResult/peopleSearchResult.scss
src/views/PeopleSearch/index.js
src/views/PeopleSearch/peopleSearch.scss
src/views/Profile/index.js

We made a whole new heckin' page.
Solves issue #262.

Advanced people search

---

src/components/Header/components/PeopleSearch/index.js
src/components/Header/components/PeopleSearch/people-search.scss

- Query highlighting
- Query sanitation
- Hide result drop-down when fewer than 3 characters have been entered

People Search Bar Tweak

---

src/views/Home/components/Carousel/carousel.scss
src/views/Home/components/Carousel/index.js

Hoping this fixes the service worker error. There is an extra scss file showing up in the build/static/media directory.

Removed extra scss file

---

src/views/Home/components/CLWCreditsDaysLeft/index.js
src/views/Home/components/Carousel/index.js

The carousel slides should now link to the specified links (in the public image uploader)

Added link support to the carousel images

---

src/views/Home/components/Carousel/carousel.scss
src/views/Home/components/Carousel/index.js

Moved creation of link array out of slider div to prevent black bar at the bottom of images

Carousel fix

---

src/services/emails.js
src/views/ActivityProfile/index.js

Added ability for involvement admins to email members/subscribers using the users mail client (not within the website). This allows the user to format emails properly and include signatures, etc.

Email group

---

src/services/membership.js
src/views/ActivityProfile/index.js

Cleaned up some of the code (consolidated setState)
Clarified ParticipationDescription in Membership Service

Fixed issue where email list only included admin

---

src/components/OfficeList/index.js
src/views/Profile/index.js

Fixes a blank office card showing up for faculty without an office

Officelistfix

---

src/services/user.js
src/views/Help/index.js

Help page says that Guest memberships don't appear on Transcript, but they do. This should fix that.

Subscribers

---

src/views/ActivityProfile/components/Membership/components/MemberList/index.js
src/views/ActivityProfile/components/Membership/index.js

Added error messages in the "Add Member dialog" when required fields are left empty, and made the "Add Member" button look like a button. Partially fixes issue #352.

Add member

---

src/views/ActivityProfile/index.js

Fix issue where involvements only load for admins, and bcc emails don't populate

---

src/components/OfficeList/index.js

Fixes issue #402 
Just changed the office numbers on faculty pages from '927' to '876.'

Fix phone number from '927' to '867'

---

.env.production
package.json

Reverts gordon-cs/gordon-360-ui#436

Revert "Update .env.production"

---

src/views/Home/components/DiningBalance/index.js

Remove requirement for personType (college role) when requesting meal plan info.

Unified dining

---

src/views/CoCurricularTranscript/index.js

Filtered Transcript memberships into service learning, honors, experience, and activities.

---

src/views/IDUploader/index.js

Adds testing functionality to ID uploader through console log. Still trying to fix that blank image bug.

Front end now reports file size (from backend) on ID upload

---

src/views/IDUploader/IDUploader.scss
src/views/IDUploader/index.js

For testing the ID Uploader bug

Added error message upon unsuccessful IDPhoto submission

---

src/views/IDUploader/index.js

Meant to drastically decrease the chance of ID Uploader breaking

ID Uploader Recursive Fix

---

src/views/IDUploader/index.js

Adds console logs to debug IDUploader recursive post method.

ID Uploader attempted fix

---

src/views/IDUploader/index.js

This adds a few small logs to check the status of ID Uploader, and make sure the backend is working as expected.

ID Uploader adding testing output

---

src/views/ActivitiesAll/index.js

If there are no activities in the current session, then change default session to the most recent session (which is fall semester during the summer)

Default Session in Involvements Page

---

src/views/ActivitiesAll/index.js

Added session in the url so that it renders to that session if you click the back button

Back button goes back to most recent page in Involvements #507

---

src/views/Home/components/DiningBalance/index.js

Corrected logic to determine dining balance color that was introduced in a recent pull request.

Fixed bug in dining balance color choice

---

public/index.html
public/sw.js
src/components/Nav/components/NavLinks/index.js
src/services/auth.js
src/views/Admin/index.js

Reverts gordon-cs/gordon-360-ui#542

Revert "Fix for incorrect font key in index.html"

---

scripts/deploy.sh

Incorrect syntax prevented build from completing. This should help.

Fixed Syntax Errors

---

scripts/deploy.sh

Update deployment script syntax

---

scripts/deploy.sh

Update deployment script clean up

---

src/components/Nav/components/NavLinks/index.js
src/views/ActivityProfile/components/Membership/components/MemberDetail/index.js
src/views/ActivityProfile/components/Membership/index.js
src/views/ActivityProfile/index.js
src/views/IDUploader/index.js
src/views/PeopleSearch/index.js

This pull request will bring all of the needed UI updates into one branch, so that they can be tested and merged simultaneously.

Unify UI Adjustments required after dependency updates

---

public/pwa.js
public/sw.js
src/components/Header/components/PeopleSearch/index.js
src/services/auth.js
src/views/Login/index.js

Restore pwa clone

---

package-lock.json
src/views/Home/components/CLWCreditsDaysLeft/CLWChart.scss
src/views/Home/components/CLWCreditsDaysLeft/index.js
src/views/Home/components/DiningBalance/DiningBalance.scss
src/views/Home/components/DiningBalance/index.js
src/views/Home/index.js

These two buttons provide links to the attended page and to Bon Appetit's menu, respectively.

What's for dinner/Events you attended buttons

---

src/views/Admin/index.js
src/views/CoCurricularTranscript/index.js
src/views/EventsAttended/index.js
src/views/IDUploader/index.js
src/views/MyProfile/index.js
src/views/PeopleSearch/index.js
src/views/Profile/index.js

Previously, guests could navigate to pages like People search via URL, and they would receive an ugly error message because they weren't authenticated. 
Now, these pages will render a more visually appealing card that informs them that they can't access X page without logging in, complete with a login button that redirects them to the Home/Login page.

Guest View Not Logged In Pages

---

src/views/MyProfile/Components/VictoryPromiseDisplay/VictoryPromise.scss

VP display fits into a 4 box square

Update in spacing

---

README.md

Setup of front-end testing has been started but is incomplete. This README section provides background, instructions, and resources for the continuation of the setup.

Added Section on Testing to README

---

src/components/Nav/components/NavAvatar/index.js

This PR fixes the styling issues that were present with the avatar shown in the left navdrawer. I felt that this was a necessary fix to implement before the semester begins.
|Before|After|
|-----|------|
|![Screenshot from 2019-08-03 14-08-03](https://user-images.githubusercontent.com/5964594/62415484-5c813800-b5f8-11e9-8e7a-c49bac7e63eb.png)|![Screenshot from 2019-08-03 14-07-49](https://user-images.githubusercontent.com/5964594/62415487-630faf80-b5f8-11e9-934f-95a3febb2bfd.png)|

Fix Navdrawer Avatar styling

---

src/services/auth.js

looking at formatting for URLSearchParams()

Doing some Console Logging

---

src/services/auth.js

Final update to getAuth()

---

.env.development
.env.production
src/services/auth.js

Trying this with pointing to https://360ApiTrain.gordon.edu/

Jason whitehouse patch 10

---

src/components/ProfileList/index.js
src/services/user.js
src/views/ActivityProfile/components/Membership/components/MemberList/index.js
src/views/ActivityProfile/components/Membership/index.js
src/views/PeopleSearch/components/MobilePeopleSearchResult/index.js
src/views/PeopleSearch/components/PeopleSearchResult/index.js
src/views/PeopleSearch/index.js

Added mailbox number and dorm to the profile view.
Partially resolves #620

Add mailbox location

---

package-lock.json
src/views/EventsAttended/index.js

Added a button that links to the Events page on both the view if user has chapel credits and if they do not.

added button to link attended page to events page

---

src/views/ActivityProfile/components/Membership/components/MemberList/index.js
src/views/ActivityProfile/components/Membership/index.js

Added ability to see mailbox numbers of activity members on the member list.

Add mailbox location to activity profile

---

package-lock.json
src/views/ActivityProfile/components/Membership/index.js

group admins can confirm a final roster, but only advisors or super admins can reopen them.

group admins can confirm rosters

---

src/views/Timesheets/components/SavedShiftsList/index.js
src/views/Timesheets/components/ShiftItem/index.js
src/views/Timesheets/index.js

Separates the list of shifts into different sections according to the shifts' statuses: Saved, Submitted, Rejected, or Approved.

Separate shifts into sections

---

src/views/Home/home.scss

Remove extra margins on login

---

src/views/Timesheets/components/ShiftDisplay/index.js

Fix tabs on mobile

---

README.md
src/services/jobs.js
src/views/Timesheets/components/SavedShiftsList/SavedShiftsList.scss
src/views/Timesheets/components/SavedShiftsList/index.js
src/views/Timesheets/components/ShiftItem/index.js
src/views/Timesheets/index.js

This pull request contains changes that were requested by @joshuaRogers24. The idea is to merge this into develop, then we can update pull request #710 to reflect these changes.

Resolve review comments

---

src/app.scss
src/components/Header/index.js
src/views/Timesheets/components/SavedShiftsList/index.js
src/views/Timesheets/components/ShiftItem/index.js
src/views/Timesheets/index.js
src/views/Timesheets/timesheets.scss

Add work week disclaimer and link to historical paid shifts

Reports link and info

---

src/views/Timesheets/components/ShiftDisplay/index.js
src/views/Timesheets/index.js

* Make tooltip surround whole header
* Fix enviroment variables
* Fix bug with future date checking
* Fetch jobs after keyboard date entry
Co-authored-by: Adam Princiotta <adamprinciotta@gmail.com>
Co-authored-by: Jacob <jacob.bradley@gordon.edu>

Tooltip around header

---

README.md
src/project-name.js
src/views/News/index.js

These are minor changes to the README.md file for the Gordon 360 UI repository. Changes include organizational adjustments and some details added for clarity as to the installation of and contribution to the Gordon 360 project.

(S20) README Update

---

.vscode/settings.json
README.md
src/components/SchedulePanel/index.js
src/project-name.js
src/views/Home/components/Question/index.js
src/views/Home/components/Question/index.scss
src/views/Home/components/Question/questionData.js
src/views/Home/index.js
src/views/MyProfile/index.js
src/views/News/index.js
src/views/PeopleSearch/components/MobilePeopleSearchResult/index.js
src/views/PeopleSearch/components/PeopleSearchResult/index.js
src/views/Profile/profile.scss
src/views/WellnessCheck/components/Approved/Approved.css
src/views/WellnessCheck/components/Approved/Approved.js
src/views/WellnessCheck/components/Denied/Denied.css
src/views/WellnessCheck/components/Denied/Denied.js
src/views/WellnessCheck/index.js

updated look of questions, updated CDC link, denial feedback

S20 wellness questions ui

---

src/views/WellnessCheck/components/Approved/Approved.css
src/views/WellnessCheck/components/Approved/Approved.js
src/views/WellnessCheck/components/Denied/Denied.css
src/views/WellnessCheck/components/Denied/Denied.js

Fixed the compatibility across different operating systems. Need to be checked on Mac OS and Windows.

S20 wellness animation

---

src/components/Nav/components/NavLinks/index.js
src/views/Home/components/Question/index.js
src/views/Home/index.js
src/views/WellnessCheck/components/HealthStatus/HealthStatus.js
src/views/WellnessCheck/index.js

fixes minor code review issues on the wellness check branch

hopefully final changes

---

src/services/jobs.js
src/views/Home/components/Question/questionData.js
src/views/Timesheets/index.js

fixed bug causing wellness check to crash on faculty page due to lack of phone number variable.

S20 faculty wellness check fix

---

src/services/jobs.js
src/views/Timesheets/index.js

added basic front end working clock in and out button to the time sheets page. Styling and other peripherals  can be added as a separate part later on.

S20 timesheets clock in out

---

src/views/Home/components/Question/questionData.js

added changes that fixes the wellness check feature in the faculty page.

fixing wellness check for faculty again

---

public/index.html
public/pwa.js
public/sw.js
public/sw_global_variables.js
public/sw_guest_cache.js
public/sw_user_cache.js
src/services/auth.js
src/views/Login/index.js

Recreated Service Worker into different parts for organization and readability.

Updated Service Worker

---

public/sw.js
public/sw_global_variables.js
public/sw_guest_cache.js
public/sw_user_cache.js
src/components/Header/components/NavButtonsRightCorner/navButtons.js
src/components/MyProfileActivityList/index.js
src/components/Nav/components/NavAvatar/index.js
src/components/OfflineBanner/index.js
src/views/MyProfile/Components/Identification/index.js
src/views/MyProfile/Components/Involvements/index.js
src/views/MyProfile/Components/VictoryPromiseDisplay/index.js
src/views/MyProfile/index.js

This pull request modifies offline mode for the My Profile URL. Originally when offline, clicking on the My Profile link would bring the user to their public profile page. This has been modified so that the user goes to their My Profile page instead. While offline on the My Profile page, all services that would require the user's browser to communicate with Gordon 360's API will be hidden. In other words, the user will only see their information and no buttons or switches that would allow them to make any changes.
The service worker has updated its removal of the old cache. Console logging has been disabled too

Updated My Profile View in Offline Mode

---

src/services/news.js
src/views/News/index.js

News is currently a beta feature. This pull request adds the ability to search news displayed on the News Page UI from the database.
Currently Working:
- Search works for *approved* news with any of the 4 attributes
Closes #806  
Needs Work:
- Everything from PR #843  
- Perhaps add search to unapproved? But might be best as is.
- Perhaps add search button (feels more conventional)

(S20) News Page - "Search" UI

---

src/services/jobs.js

reverted getActiveJobsForUser

---

src/views/Events/event.scss
src/views/Events/index.js

Main improvement is just centering those filter buttons on mobile. Very painful working around MUI so I just made a media query to work around it. The breakpoint is sort of hard coded but I think it was the least terrible way to do this.
Also cleaned up Grid usage a bit and adjusted search bar

(S20) Fixed Events Alignment

---

src/services/jobs.js

Route name changes to match the back end changes.

added route name changes to match back end

---

src/services/user.js

In user.js, I named variables as FirstName and LastName. It should be Firstname and Lastname.

Fix variable name for advisor

---

public/pwa.js
public/sw.js
public/sw_global_variables.js
public/sw_guest_cache.js
public/sw_user_cache.js
src/components/AdvisorList/index.js
src/components/Identification/index.js
src/components/MyProfileActivityList/index.js
src/components/OfficeList/index.js
src/components/PWAInstructions/index.js
src/components/ProfileList/index.js
src/components/ProfileList/listItems.js
src/components/QuickLinksDialog/components/LinksList/index.js
src/components/SchedulePanel/components/ScheduleCalendar/index.js
src/components/SchedulePanel/index.js
src/views/About/index.js
src/views/ActivitiesAll/index.js
src/views/Events/index.js
src/views/MyProfile/index.js
src/views/Profile/index.js

- PWA bug fixes
- Fix for My Profile infinite re-render for Faculty view
- Department is now apart of Faculty's Office Information card instead of their Personal Information
- Adds a link to the Links Dialog box. This link will bring the user to Gordon's main website where they can view Gordon College's maps

S20 pwa installer

---

src/views/Timesheets/index.js

- Timesheets is unavailable to non-students

S20 timesheets staff disable

---

src/views/Events/index.js

Improvements:
- Fixes a bug where the Events page returns nothing

Fixed Events Bug

---

src/components/OfficeList/index.js
src/services/user.js
src/views/PeopleSearch/components/MobilePeopleSearchResult/index.js
src/views/PeopleSearch/components/PeopleSearchResult/index.js
src/views/PeopleSearch/index.js

When FacStaff have a mailstop (Mail_Location), show it on their profile and in people search results, similar to students' mailbox number.

Display FacStaff Mailstop on profile and search

---

src/components/AlertDialogBox/index.js
src/services/housing.js
src/views/ApartmentApp/apartmentApp.scss
src/views/ApartmentApp/components/StaffMenu/index.js
src/views/ApartmentApp/components/StudentApplication/components/ApplicantList/components/ApplicantListItem/index.js
src/views/ApartmentApp/components/StudentApplication/components/ApplicantList/index.js
src/views/ApartmentApp/components/StudentApplication/components/HallSelection/components/HallListItem/index.js
src/views/ApartmentApp/components/StudentApplication/components/HallSelection/index.js
src/views/ApartmentApp/components/StudentApplication/components/SaveButton/index.js
src/views/ApartmentApp/components/StudentApplication/index.js
src/views/ApartmentApp/index.js

Converted all ApartApp components from class components to functional components

Apartapp functional components

---

README.md

Went through whole readme and verified that each hyperlink goes to the correct destination.
resolves #1002

Fixed broken/incorrect links

---

README.md
src/setupProxy.js
src/views/ApartmentApp/apartmentApp.scss
src/views/ApartmentApp/components/StaffMenu/index.js
src/views/ApartmentApp/components/StudentApplication/components/ApplicantList/index.js
src/views/ApartmentApp/components/StudentApplication/components/HallSelection/index.js
src/views/ApartmentApp/components/StudentApplication/index.js
src/views/PeopleSearch/index.js

Improvements to the code based on code review in #926

Merged from develop and other requested improvements

---

src/views/ActivitiesAll/components/ActivityGrid/activity-grid.scss
src/views/ActivitiesAll/components/Requests/components/RequestsReceived/index.js
src/views/ActivitiesAll/components/Requests/components/RequestsReceived/requests.scss

"no requests" text properly padded
involvement cards properly padded
need to edit scss sheets

Involvments text

---

package-lock.json
src/views/ApartmentApp/components/StudentApplication/components/HallSelection/components/HallListItem/index.js

Fixed incorrect variable name,
But the old bu has returned which causes  the hall dropdowns to not always update the displayed text right after the user makes a selection. That issue will require a much more thorough investigation later

Fixed hall issue caused by changed variable/prop name

---

.vscode/settings.json
src/_vars.scss
src/components/OfficeList/index.scss
src/components/PWAInstructions/index.scss
src/components/SchedulePanel/components/ScheduleCalendar/schedulecalendar.scss
src/views/ActivitiesAll/components/Requests/components/RequestsReceived/requests.scss
src/views/Page404/components/ScottieDog/scottieDog.scss

Last change: All of inconsistent white, black and gray colors(achromatic color).
(See Color Consistency: Black, White, Gray #1025)
Now, I have worked on all of inconsistent chromatic colors.
There's only few colors I need to change.
Thing I have changed:
1. src/_vars.scss
- Add $primary-red: #ff0000
- Delete $neutral-black2: #111111
2. src/components/PWAInstructions/index.scss
- #ce392e -> $secondary-red
BEFORE: #ce392e 
AFTER: $secondary-red
- #0078da -> $primary-cyan
BEFORE: #0078da
AFTER: $primary-cyan
- #014983 -> $primary-blue
in _vars.scss $primary-blue is already declared (Hexadecimal Color #014983).
- #31342b -> $neutral-dark-gray
in _vars.scss $neutral-dark-gray is already declared (Hexadecimal Color #31342b).
3. \src\views\ActivitiesAll\components\Requests\components\RequestsRece …

Color Consistency: All of chromatic color

---

src/services/housing.js
src/views/ApartmentApp/components/StaffMenu/index.js
src/views/ApartmentApp/components/StudentApplication/components/ApplicantList/components/ApplicantListItem/index.js
src/views/ApartmentApp/components/StudentApplication/components/HallSelection/components/HallListItem/index.js
src/views/ApartmentApp/components/StudentApplication/components/HallSelection/index.js
src/views/ApartmentApp/components/StudentApplication/index.js

The StudentApplication component was loading apartment applications in a useEffect that depended on unnecessary state and so was being run too oten and getting cut short, causing state inconsistencies. 
The useEffect has been simplified to only depend on `userProfile`, so that it only runs when the component is initially rendered.

ApartApps Fix application load bug and other changes from review

---

src/views/ApartmentApp/components/StaffMenu/components/ApplicationTable/components/ApplicationRow/components/ApplicantSubTable/index.js
src/views/ApartmentApp/components/StaffMenu/index.js

This branch implements several simplifications of the process of generating the arrays for the CSV files, based on ideas and suggestions from #1067 
It also adds a button that allows the user to refresh or reload the application data that is used in the data table and CSV files, which is more efficient than refreshing the entire page within the browser. The styling and position of this button have not yet been finalized, but the functionality of the button should be working. 
Feel free to offer styling/placement suggestions for the button, but the primary goal is to get it functional and merged in time for the user testing tomorrow; the aesthetic styling can be cleaned up next week in a separate PR

Apartapp simplified CSV generation and refresh data button

---

src/views/ApartmentApp/index.js

Fixed issue with loading not displaying the GordonLoader during page load, etc.

Fixed ApartApp page loading

---

src/views/ApartmentApp/components/StudentApplication/components/ApplicationDataTable/index.js
src/views/ApartmentApp/components/StudentApplication/components/HallSelection/components/HallListItem/index.js
src/views/ApartmentApp/components/StudentApplication/components/OffCampusSection/components/OffCampusListItem/index.js

This bug was revealed during the in-class demo

ApartApp - Bug fix for date submitted saying "Invalid DateTime"

---

src/views/ApartmentApp/apartmentApp.scss
src/views/ApartmentApp/components/StudentApplication/components/InstructionsCard/index.js
src/views/ApartmentApp/components/StudentApplication/index.js

ApartApp - Left justify application instructions

---

src/services/housing.js
src/views/ApartmentApp/apartmentApp.scss
src/views/ApartmentApp/components/StaffMenu/components/ApplicationTable/components/ApplicationRow/index.js
src/views/ApartmentApp/components/StudentApplication/components/ApplicantList/index.js
src/views/ApartmentApp/components/StudentApplication/index.js

ApartApp - Urgent bug fixes

---

src/routes.js

1084 ApartApp (1) Change application page title (in top left) from "Apartment App" to the more formal "Apartment Application"

---

src/views/ApartmentApp/components/StudentApplication/index.js

Suggested by @EjPlatzer [here](https://github.com/gordon-cs/gordon-360-ui/pull/1093#discussion_r623272075)
Style of createSnackbar was inspired by the elegant implementation used in src/components/MembershipList

Added the createSnackbar helper function

---

src/services/housing.js
src/views/ApartmentApp/apartmentApp.scss
src/views/ApartmentApp/components/StaffMenu/index.js
src/views/ApartmentApp/components/StudentApplication/components/Agreements/index.js
src/views/ApartmentApp/components/StudentApplication/components/ApplicantList/components/ApplicantListItem/index.js
src/views/ApartmentApp/components/StudentApplication/components/ApplicantList/index.js
src/views/ApartmentApp/components/StudentApplication/components/BottomBar/components/SaveButton/index.js
src/views/ApartmentApp/components/StudentApplication/components/BottomBar/index.js
src/views/ApartmentApp/components/StudentApplication/components/HallSelection/index.js
src/views/ApartmentApp/components/StudentApplication/components/InstructionsCard/index.js
src/views/ApartmentApp/components/StudentApplication/components/OffCampusSection/index.js
src/views/ApartmentApp/components/StudentApplication/index.js
src/views/ApartmentApp/index.js

This branch includes minor UI styling improvements and better readability/conciseness of the code in general (or at least that was my goal)
One of the other key improvements of this branch comes from the fact that I learned about `service/error.js` and learned how to properly check the error types of the error codes received from the API.

Apartapp cleanup

---

package-lock.json
src/views/About/about.scss
src/views/About/contributors.json
src/views/About/index.js

The About page benefitted greatly from a refactor, and in the process was redesigned for better parity with the rest of the site. The list of contributors is now a `.json` which can be easily edited and added to without having to deeply understand the structure of the page (and the repeated layout components are no longer repeated, and instead mapped to).
The previous design:
The new design:
The main elements of the redesign were to put the content on a card and make consistent use of Material UI design.

Update and refactor About page design

---

src/views/About/contributors.json

This section of the About page was accidentally deleted earlier.

Add 2019-20 Software Development Team

---

src/views/InvolvementsAll/index.js

Created small PR for this just to avoid confusion in future PRs seeing changes. This is an extension of PR #1128.

Formatted Involvements Changes - #1128 Extension

---

README.md

Quick change to help clarify instruction before 2021 Practicum team starts

Capitalize LTS to Clarify

---

README.md

Mac is like Linux.  Made LTS clearer and more clearly preferred.

Clarify nvm's Linux instructions, add Mac

---

src/views/PeopleSearch/index.js

Attempt to fix issue #1150. I am not sure if this is the way it is supposed to be done, or if there is another way that display problems are supposed to be handled, but as for me, this aligns the checkbox to the center of the card it is in.

Centering include alumni textbox

---

src/components/Header/components/PeopleSearch/index.js
src/components/Profile/components/PersonalInfoList/index.js
src/services/people-search.js

This PR must be merged together with https://github.com/gordon-cs/gordon-360-api/pull/584 to make the whole feature works properly.
Feature added:
- If a person's nickname != firstname && nickname != firstname in the AD_Username, the found person will be shown in this format:
**firstname lastname (nickname)**
and the nickname will be highlighted.
Example shown as following:

S21 nickname people search

---

src/components/Profile/components/PersonalInfoList/index.js

WAS:
The note appears on every profile page.
NOW:
The note only appears on my profile page.

Changed some codes to make NOTES only appear on My Profile page

---

src/services/goStalk.js
src/services/housing.js
src/services/user.js
src/views/ApartmentApp/components/StudentApplication/components/InstructionsCard/index.js
src/views/PeopleSearch/components/PeopleSearchResult/index.js
src/views/PeopleSearch/index.js

I replaced "Freshman" with "First Year" in the people search bar and the profile page.

Replaced "Freshman" with "First Year" Closes issue #1193

---

src/services/goStalk.js
src/views/PeopleSearch/index.js

This PR fixes advanced people search filter issue, such as
- space, number, and some other symbols pull out everyone in the database.
- pulling out everyone in the database by clicking the include alumni checkbox.

Fixed advanced people search filter issue

---

src/views/PeopleSearch/index.js

Patch to #1213, swapped heading back to what it was before

Swapped mailbox # heading with mail location - PATCH

---

src/components/Header/components/PeopleSearch/index.js

Actually coded by Kevin and Cameron.  I just had a clean branch handy.

Fix quick search for people without nicknames (mostly staff)

---

src/views/PeopleSearch/index.js

Changed breakpoints to smooth transition from full to partial window width

Use window width better in search results list

---

src/views/PeopleSearch/index.js
src/views/Timesheets/index.js

RELEASE: Disable Timesheets for HR Switch over

---

src/components/Header/components/PeopleSearch/index.js
src/views/Events/index.js
src/views/InvolvementProfile/components/Membership/components/AdminCard/index.js
src/views/InvolvementProfile/components/Membership/components/NonMemberButtons/index.js
src/views/InvolvementsAll/index.js
src/views/News/index.js

Added a bunch of clear buttons.

Added TextField clear buttons

---

src/services/session.js
src/views/Home/components/CLWCreditsDaysLeft/index.js
src/views/Home/components/DaysLeft/index.js

Before:
After:
https://github.com/gordon-cs/gordon-360-api/pull/636

(S21) Added "current term" on homepage

---

src/components/Profile/components/Identification/index.js
src/components/Profile/components/Identification/index.scss
src/components/Profile/components/PersonalInfoList/index.js
src/components/Profile/components/ProfileInfoListItem/index.js
src/services/user.js

S21 Clifton Strengths 2.0

---

.env.development
.env.production
public/index.html

.env.production apparently actually refers to any production environment, including both train and prod.

(S21) PATCH - Point Train to Train DB (fixed .env.production)

---

src/views/About/contributors.json

New Update of the 2021 Summer Practicum

summer practicum update my about page

---

src/components/Profile/components/Identification/index.js

Relates to #1270.
Changes:
Student => Show first name.
FacStaff => Show full name.
However, here is my suggestion.
For student, show nickname.
For FacStaff, show the full name. How do you guys think?
Before:
After:

s21_facstaff_profile_card

---

src/views/InvolvementProfile/components/ContactListItem/index.js
src/views/InvolvementProfile/components/Membership/components/MemberList/components/MemberListItem/index.js
src/views/InvolvementProfile/components/Membership/components/MemberList/index.js
src/views/InvolvementProfile/index.js

Adding a Link in The Involvement roster so that when user click on a certain member it will show them the member's profile.

 S21-Added a link profile for the admin/Advisors 

---

src/components/Profile/components/PersonalInfoList/index.js

Add a note

---

package-lock.json
src/components/Profile/components/PersonalInfoList/index.js

added some comment on the toggle. and improved the code.

S21 toggle improvement

---

src/views/AcademicCheckIn/components/UpdatePhone/index.js
src/views/AcademicCheckIn/index.js

Realized that window.history is bad and does not work with all browsers (sorry @EjPlatzer for not believing you). Replaced this to use the history already defined in app.js and it seems to be fully functional.
Also implemented a small change to the phone page at request of Dr. Tuck.

Academic Check In Quick Fixes

---

src/views/AcademicCheckIn/index.js

Made another blunder and missed Evan's comment on the last PR. Checking if this looks better.

Updates for the history in Academic Check In

---

src/views/Home/components/CLWCreditsDaysLeft/index.js
src/views/InvolvementsAll/index.js

Some minor fixes
Before:
After:

add variant=filled and delete attended events

---

src/views/Home/index.js

Edited by @cpabbot 
This was removed since some db difference is improperly redirecting on prod

Removed Academic Check In from Homepage

---

src/services/user.js

fixed user services files

---

src/routes.js

We are sticking with the GO Gordon site for this year (2021 Fall) and will continue to test this process until then.
**Message from Evan Platzer:**
"Given that we aren't able to do a thorough test of the system soon though, I'm beginning to think that sticking with the GO site for this semester is the best call. I'll have the GoCo Labs team test it further this fall and hopefully we will be confident in it for the Spring."

Removing Academic Checkin from 360

---

src/components/Header/components/PeopleSearch/index.js

Just deleted two lines of extra codes that caused the result racing issue.

Fixed: quick people search racing issue

---

src/services/cliftonStrengthsData.js
src/services/user.js

This PR is just for cleaning up the code so that the Clifton Strengths objects are not cluttering the user service code.

Refactor Clifton Data into Separate File

---

src/components/Profile/components/PersonalInfoList/index.js

Add Space After Comma in Address

---

src/components/GordonLimitedAvailability/index.js
src/components/Profile/components/MembershipsList/index.js
src/components/Profile/index.js
src/views/ApartmentApp/index.js
src/views/CoCurricularTranscript/index.js
src/views/Timesheets/index.js

Repeated code refactored into a component.
This pull request completes the following:
- Refactor the aforementioned shared message into a component called `<GordonLimitedAvailability/>` and made views reference it (Timesheets, ApartApp)

Refactor Availability Message into GordonLimitedAvailability Component

---

src/components/AppRedirect/index.js
src/views/EnrollmentCheckIn/index.js

RELEASE: Allow wellness checkin before enrollment checkin

---

src/services/housing.ts
src/views/ApartmentApp/components/StudentApplication/components/Agreements/index.js
src/views/ApartmentApp/components/StudentApplication/components/InstructionsCard/index.js

As we prepare for housing selection for the 2022-2023 school year, the Apartment Application page needs some updates.

ApartApp: Fix typos and update info for 2022

---

node_modules/react-big-calendar/lib/sass/variables.scss
src/components/Profile/components/PersonalInfoList/PersonalInfoList.module.css
src/views/Update/Update.module.css
src/views/Update/index.js

added scss and added param for the build

UI alum form

---

src/views/CoCurricularTranscript/Components/CoCurricularTranscriptExperience/CoCurricularTranscriptExperience.module.scss

tabbing alignment
before:
https://gyazo.com/09cacc31de519f480e006e8f0e7bcb76
after:
https://gyazo.com/6126b6accd485c9cdfa046777443329d

aligned dates between experience and activities

---

src/views/Home/components/DiningBalance/index.js

Some Faculty and Staff have a valid meal plan, so we should show that, rather than assuming all FacStaff only have a dining dollars balance.

Display meal plan when it exists

---

src/components/Profile/components/PersonalInfoList/index.js

Sensitive info viewers need room number to do their job properly.

Show room number to sensitive info viewers

---

src/components/Profile/components/PersonalInfoList/index.js
src/services/request.ts
src/views/InvolvementProfile/components/Membership/components/NonMemberButtons/index.js

This release fixes membership requests so that users can once again request membership themselves.

Hotfix: Users can request membership in an involvement

---

src/services/goStalk.ts

HotFix: Fix PeopleSearch ClassType

---

src/components/Profile/components/PersonalInfoList/index.js

Replaced isEmpty() with checking the string length logic.
Closes #1378.

Replacing isEmpty() to str.length === 0

---

src/views/RecIM/components/Listing/index.js
src/views/RecIM/index.js
src/views/RecIM/views/League/index.js
src/views/RecIM/views/Match/Match.module.scss
src/views/RecIM/views/Match/index.js

Super basic, just so we have something to work with

[Rec-IM] Basic Match Page Layout

---

src/services/recim/match.ts
src/services/recim/participant.ts

Adjustment PR introducing changes from the SQL Refactor conducted by @Kevin-Chu58 
API PR required:
https://github.com/gordon-cs/gordon-360-api/pull/761

Implement API/SQL changes to vm's

---

src/app.global.scss
src/views/RecIM/components/Forms/CreateActivityForm/index.js
src/views/RecIM/components/List/Listing/Listing.module.scss
src/views/RecIM/components/List/Listing/index.js
src/views/RecIM/components/List/index.js
src/views/RecIM/views/Activity/Activity.module.scss
src/views/RecIM/views/Activity/index.js
src/views/RecIM/views/Home/Home.module.scss
src/views/RecIM/views/Home/index.js
src/views/RecIM/views/Match/Match.module.scss
src/views/RecIM/views/Match/index.js
src/views/RecIM/views/Team/Team.module.scss
src/views/RecIM/views/Team/index.js

- Added card headers to home, activity, team, match page
- Created v1 of breadcrumb navigation
- Some visual work on activity listing
- Standardized createActivity button
- Fixed bug where team listings didn't properly link to their respective activities, so activityID was undefined in the navigation path
- Improved mobile responsiveness

[Rec-IM] Home, Header Visual Updates

---

src/components/SpreadsheetUploader/index.js
src/views/EnrollmentCheckIn/components/EnrollmentCheckInWelcome/index.js

This release contains the time-sensitive pr #1597.

Release: Update registration hold message 

---

src/services/user.ts

The previous definition of `isStudent` was causing issues for incoming students, who did not yet have a `Class` stored in the database. Instead, we now use the `PersonType` attribute, which is composed in the API according to which tables the profile info was sourced from. Accordingly, if a profile has info from the `Student` table, then it's `PersonType` will include `stu`.

Use `PersonType` to determine profile shape

---

src/services/user.ts
src/views/EnrollmentCheckIn/components/EnrollmentCheckInWelcome/index.js

As noted in #1599, profile info was not being parsed correctly for incoming students, who don't yet have a `Class` in the database. This fixes hotfix fixes that parsing so that incoming students can properly use 360.

Hotfix: Fix Profile parsing for incoming students.

---

src/services/user.ts
src/views/CoCurricularTranscript/index.js
src/views/IDUploader/index.js

This release merges #1602 to fix a major, time-sensitive bug in the ID Uploader and Co-Curricular Transcript pages.

Release: Hotfix ID Uploader and Co-Curricular Transcript

---

src/components/AppRedirect/index.js
src/views/CoCurricularTranscript/index.js
src/views/PeopleSearch/components/PeopleSearchResult/index.tsx

This PR is a cherry-picked collection of three small changes that fix various features of the UI as mentioned in the title.
See #1608, #1604, and #1601 for details.
Closes #1607

HOTFIX RELEASE: Fix People Search, Enrollment Checkin Cache, CCT

---

src/components/Header/components/QuickSearch/QuickSearch.module.scss
src/components/Header/components/QuickSearch/index.js
src/views/RecIM/components/Forms/InviteParticipantForm/index.js
src/views/RecIM/components/List/Listing/Listing.module.scss
src/views/RecIM/components/List/Listing/index.js
src/views/RecIM/components/List/index.js
src/views/RecIM/views/Team/Team.module.scss
src/views/RecIM/views/Team/index.js

- More options menu to remove a team participant or make co-captain
- Invite participant window, where a list of participants can be invited at once
To do: redundancy check - prevent invites being sent to people that are already on the team or have already been invited.
**Note: there is no API functionality with this yet, this is simply the UI work**

[Rec-IM] Roster Updates

---

src/services/http.ts
src/services/recim/activity.ts
src/views/RecIM/components/Forms/ActivityForm/index.js
src/views/RecIM/components/Forms/CreateTeamForm/index.js
src/views/RecIM/views/Activity/index.js
src/views/RecIM/views/Home/index.js
src/views/RecIM/views/Team/index.js

PR Tackles the first PATCH route usage in the form of _Edit an Activity_ 
Notes:
There will be a PR required in the API that needs to be merged to allow PATCH for local development due to HTTP PATCH being blocked by development proxy. The PR will allow us to develop locally on the 360ApiRecim API without a proxy with no CORS failures. 
- Fixed as of Jan 18th, 2023

[Rec-IM] Edit Activity functionality added to CreateActivityForm

---

.env.development
.env.production
src/services/recim/activity.ts
src/services/recim/series.ts
src/views/RecIM/components/Forms/CreateActivityForm/index.js
src/views/RecIM/components/Forms/CreateSeriesForm/index.js
src/views/RecIM/components/List/Listing/index.js
src/views/RecIM/components/List/index.js
src/views/RecIM/views/Activity/index.js
src/views/RecIM/views/Home/index.js

PR tackles Series Creation Form in both the Activity Creation Form as well as a stand-alone creation button on the Activity Page. Activity's Series currently are listed above Activity Teams 
TLDR;
- Create Series prompted after Create Activity
- Create Series option on Activity Page
PR also handles ActivityType propagation

[Rec-IM] Series Creation and Propagation 

---

src/views/RecIM/components/List/Listing/index.js

- changed icons
- fixed listing UI

[Rec-IM] Quick Series UI Update

---

src/services/recim/team.ts
src/views/RecIM/components/List/Listing/index.js
src/views/RecIM/views/Activity/index.js
src/views/RecIM/views/Team/index.js

Handles changes from the API stated in:
https://github.com/gordon-cs/gordon-360-api/pull/783

[Rec-IM] UI Integration of API update

---

src/services/recim/team.ts
src/views/RecIM/components/Forms/CreateMatchForm/index.js
src/views/RecIM/components/Forms/components/InformationField/index.js
src/views/RecIM/components/List/Listing/index.js
src/views/RecIM/components/List/index.js
src/views/RecIM/views/Activity/index.js
src/views/RecIM/views/Match/index.js
src/views/RecIM/views/Team/index.js

To clarify a bit more on the purpose of this PR, this is the edit icon that can allow a referee or admin to edit the score, sportsmanship, and attendance of the teams involved in the match.
Also this will enable admins to create new matches that were not auto scheduled.

[Rec-IM] Match Editing and Creation

---

src/views/RecIM/components/List/Listing/index.js
src/views/RecIM/components/List/index.js
src/views/RecIM/views/Activity/Activity.module.scss
src/views/RecIM/views/Home/Home.module.scss
src/views/RecIM/views/Match/Match.module.scss
src/views/RecIM/views/Match/index.js

//DONE
- Fixed API based routing error in breadcrumb, activityID => ___.Activity.ID
- Handle error regarding empty/single team matches
- Handle UX for empty/single team matches
- Score properly fetched
- Fixed API based routing error from matchlisting on team page (activityID was never passed for some reason)
- Link to team page via clicking Team Name on Match Page
//TODO
- Edit functionality to be handled by @silasw2

[Rec-IM] Match functionality/UX

---

src/views/RecIM/components/List/Listing/index.js

Show participant names instead of participant usernames.
Original commit 0dac6745ce786475010a3f8e87d872368ca28a6a but removed in merge conflict resolution b0afdf07539d94493e5dffa7873a3fb36f697330

[Rec-IM] Fix participant names

---

src/services/recim/match.ts
src/services/recim/team.ts
src/views/RecIM/views/Match/index.js

handles changes from:
https://github.com/gordon-cs/gordon-360-api/pull/791

[Rec-IM] API Team Update

---

src/views/RecIM/views/Activity/index.js

[Rec-IM] User-Test#1 - Fix null isAdmin on reload, fix logic error

---

src/views/RecIM/views/Admin/Admin.module.scss
src/views/RecIM/views/Admin/index.js
src/views/RecIM/views/Home/index.js

- export homeHeader
- reduce loading logic
- remove unneeded states
TEAM FETCH LOGIC ERROR PR:
https://github.com/gordon-cs/gordon-360-api/pull/793 (this will need to be approved to fetch all teams)
@cpabbot the page looks amazing! great work so far

[Rec-IM] Simplify logic for Admin v1

---

.env.development
.env.production
src/services/recim/activity.ts
src/services/recim/team.ts
src/views/RecIM/components/List/index.js
src/views/RecIM/index.js
src/views/RecIM/views/Activity/index.js
src/views/RecIM/views/Admin/Admin.module.scss
src/views/RecIM/views/Admin/index.js

WIP, but can merge whenever and continue to be developed.

[Rec-IM] Admin Page v1

---

docs/Developer's Guide.md

This PR updates local development documentation to clarify particular directions after getting input from the new development team.

Clarify SSH Tunnel Backend

---

src/views/RecIM/components/List/Listing/Listing.module.scss
src/views/RecIM/components/List/Listing/index.js
src/views/RecIM/views/Activity/Activity.module.scss
src/views/RecIM/views/Activity/index.js
src/views/RecIM/views/Home/Home.module.scss
src/views/RecIM/views/Home/index.js

Linked issue described https://github.com/gordon-cs/RecIM-Docs/issues/89

[Rec-IM] ActivityListing UI Update

---

src/services/recim/series.ts
src/views/RecIM/components/Forms/CreateSeriesForm/index.js

Handles all changes in the API pertaining to Auto-Scheduling, Schedule Creation. Auto-scheduling will be merged in modules based on completeness.
This PR handles changes in:
https://github.com/gordon-cs/gordon-360-api/pull/798

[Rec-IM] Scheduling Part 1

---

src/views/RecIM/components/Forms/TeamForm/index.js
src/views/RecIM/views/Activity/index.js

Closes issue: https://github.com/gordon-cs/RecIM-Docs/issues/96

[Rec-IM] Redirect to Team Page after Creation

---

src/views/RecIM/views/Activity/index.js

[Rec-IM] Remove accidentally leftover debugger

---

src/components/Header/index.js
src/components/Nav/components/NavLinks/index.js
src/views/RecIM/components/List/Listing/index.js

added drawer button, added dash to header button

[Rec-IM] Quick Add Nav Button to Rec-IM

---

src/views/RecIM/views/Activity/components/ScheduleList/index.js
src/views/RecIM/views/Activity/index.js
src/views/RecIM/views/Team/index.js

- Add individual activity implemntation
- Series delete and warning

[Rec-IM] Non specific work added to Match-Edit-V2

---

src/views/RecIM/components/Forms/EditMatchStatsForm/index.js
src/views/RecIM/components/Forms/MatchForm/index.js
src/views/RecIM/components/Forms/TeamForm/index.js
src/views/RecIM/components/Forms/components/InformationField/index.js
src/views/RecIM/components/List/Listing/index.js
src/views/RecIM/components/List/index.js
src/views/RecIM/views/Match/index.js
src/views/RecIM/views/Team/index.js

- Singular edit button on match YAY

[Rec-IM] Updated Match Edit

---

src/views/RecIM/views/Activity/index.js

bug that only allowed admins to create teams

[Rec-IM] Fix users unable to create team

---

src/views/RecIM/views/Activity/index.js
src/views/RecIM/views/Home/Home.module.scss
src/views/RecIM/views/Home/index.js
src/views/RecIM/views/Team/Team.module.scss
src/views/RecIM/views/Team/index.js

This PR makes the team page and home page have admin button styling identical to the activity page button styling introduced a while ago. Below are pictures with the look of the new pages.
Home Page:
Team Page:

[Rec-IM] Cohesive Button Design

---

package-lock.json
package.json
src/views/RecIM/views/Activity/index.jsx
vite.config.ts

Also forgot to push one of the fixes I had on react-router change

[Rec-IM] Fix Vite profile issue regarding "." in the URL

---

src/views/RecIM/components/List/index.jsx
src/views/RecIM/views/Activity/index.jsx

If a user wasn't participating in the activity, the condition was overwritten despite the activity registration being closed.
captain status cannot be changed. listing updated to add minimal tag if admin.

[Rec-IM] activity registration condition fix + team captain immutability 

---

src/views/RecIM/components/Forms/EditMatchStatsForm/index.jsx
src/views/RecIM/components/Forms/MatchForm/index.jsx
src/views/RecIM/components/List/index.jsx
src/views/RecIM/views/Match/index.jsx

The main one is that I was unaware of what Minimal meant. I thought it implies "no options" but then did not realize we had a separate tag for it.

[Rec-IM] Visual Bug fix

---

src/views/InvolvementProfile/components/Membership/index.jsx

PROD HOTFIX: Fix involvements Loading

---

src/views/InvolvementProfile/components/Membership/index.jsx

The recent PR, #1695, only fixed 1/2 instances of the incorrect logic. This PR resolves the second and last of these.

HOTFIX: Add Involvement Join Buttons Back

---

src/views/InvolvementProfile/components/Membership/index.jsx

PROD HOTFIX:  Add Involvement Join Buttons Back

---

.env.production
src/components/Profile/components/PersonalInfoList/index.jsx

When the user has no Clifton Strengths, this will now display a link to the site where they can take the Clifton Strengths test. 
fixes #1319

Adds Clifton Strengths test link to profile if user has no strengths

---

src/services/recim/series.ts
src/views/RecIM/components/Forms/SeriesForm/index.jsx
src/views/RecIM/views/Activity/components/ScheduleList/index.jsx
src/views/RecIM/views/Activity/index.jsx
src/views/RecIM/views/Home/index.jsx

This PR allows editing of a specific series from its additional options drop-down in the scheduling page. It also involved renaming the form as a whole since it is not longer just a create form.

[Rec-IM] Edit Series

---

src/services/checkIn.ts

This is why you should always audit automatic imports.

Fix improper import

---

package-lock.json
src/components/Profile/components/PersonalInfoList/index.jsx
src/components/Providers/components/AuthProvider/index.tsx
src/components/Providers/index.tsx
src/index.tsx
src/services/auth.ts
src/services/checkIn.ts
src/services/error.ts
src/services/user.ts
src/views/InvolvementProfile/components/Membership/components/AdminCard/index.jsx
src/views/InvolvementProfile/components/Membership/index.jsx
vite.config.ts

This branch pulls from [fixHMR](https://github.com/gordon-cs/gordon-360-ui/pull/1715), not develop since fixHMR has not yet been merged into develop. Main reason for this PR is the HMR fix, but this comes with a few updates from develop since our last merge.

[Rec-IM] Merge in Develop *HMR Fix*

---

src/views/RecIM/components/Forms/EditMatchStatsForm/index.jsx
src/views/RecIM/components/Header/Header.module.scss
src/views/RecIM/components/List/Listing/index.jsx

Note: 'vs.' to be replaced with the score upon completion, and TBD if the score does not exist at that point.

[Rec-IM] Match Listing Update

---

src/views/RecIM/components/Helpers/index.js
src/views/RecIM/components/List/Listing/index.jsx
src/views/RecIM/views/Activity/components/ScheduleList/index.jsx
src/views/RecIM/views/Home/index.jsx
src/views/RecIM/views/Match/index.jsx

Replaced all luxon uses in recim with date-fns

[Rec-IM] Removed luxon

---

src/services/recim/activity.ts
src/services/recim/match.ts
src/services/recim/series.ts
src/services/recim/team.ts
src/views/RecIM/components/Forms/ActivityForm/index.jsx
src/views/RecIM/components/Forms/EditMatchStatsForm/index.jsx
src/views/RecIM/components/Forms/MatchForm/index.jsx
src/views/RecIM/components/List/Listing/index.jsx
src/views/RecIM/components/List/index.jsx
src/views/RecIM/views/Activity/index.jsx
src/views/RecIM/views/Home/index.jsx
src/views/RecIM/views/Match/index.jsx
src/views/RecIM/views/Team/index.jsx

Handles name changes + Activity Delete route

[Rec-IM] API/Develop Update

---

src/services/http.ts
src/services/recim/match.ts
src/views/RecIM/components/List/Listing/Listing.module.scss
src/views/RecIM/components/List/Listing/index.jsx
src/views/RecIM/components/List/index.jsx
src/views/RecIM/views/Match/index.jsx

I'm not ecstatic about the styling but I think this is pretty solid especially for now; feel free to give feedback if there's anything you think would make design more intuitive, but I think this works pretty well. I considered a few different approaches but went with this for simplicity and clarity.
I also considered combining the parameters to pass down into one `attendanceDetails` object to reduce the number of parameters, but I thought those parameters might end up getting used for other contexts in the future so I left them as is. It is a large number of parameters, but I don't think it hurts; I could even leave a comment to document what the different parameters are used for if desired.
Admin view
User view

[Rec-IM] Match Attendance

---

src/services/recim/match.ts
src/services/recim/participant.ts
src/services/recim/team.ts
src/views/RecIM/components/Forms/MatchForm/index.jsx

Details are expunged in the API PR. Refer there for changes.
This PR is a part of a larger PR. Please review the base PR... https://github.com/gordon-cs/gordon-360-ui/pull/1727
API PR changes https://github.com/gordon-cs/gordon-360-api/pull/861

[Rec-IM] Bug Fixes / Merge Conflicts / API Related Changes

---

src/views/RecIM/components/Forms/InviteParticipantForm/InviteParticipantForm.module.scss
src/views/RecIM/components/Forms/InviteParticipantForm/index.jsx

People search results can now overflow dialog box

[Rec-IM] Fixed invite bug

---

src/views/RecIM/components/Forms/ActivityForm/index.jsx
src/views/RecIM/components/Forms/TeamForm/index.jsx
src/views/RecIM/components/Forms/components/ConfirmationRow/index.jsx
src/views/RecIM/components/Helpers/index.js
src/views/RecIM/views/Activity/index.jsx
src/views/RecIM/views/Match/index.jsx
src/views/RecIM/views/Team/index.jsx

This pr adds the following feature(s) to RecIM UI:
- Add Cropper to Activity Form and Team Form
**Activity Form**
Create new activity
Update current activity
**Team Form**
Create new team
Update current team
Just a note:
- I have updated the `serverAddress` logic in `GetImageUrl()` at the backend, so now whatever images you upload from 360train will also work properly when you run the system locally. But this will not work if you upload an image from localhost, and try to get it on 360train.
Corresponding API pr: https://github.com/gordon-cs/gordon-360-api/pull/854.

[Rec-IM] Post/Update/Remove Image in RecIM Activity and Team

---

src/components/GordonDialogBox/GordonDialogBox.module.scss
src/components/GordonDialogBox/index.jsx
src/services/recim/team.ts
src/views/RecIM/views/Activity/index.jsx
src/views/RecIM/views/Match/index.jsx
src/views/RecIM/views/Team/index.jsx

- Activity delete
- Team delete
- Match delete

[Rec-IM] Add Deletes

---

src/views/RecIM/views/Match/Match.module.scss
src/views/RecIM/views/Match/index.jsx

Still not perfect, but much more clean and usable from before.

[Rec-IM] Fix Match Responsiveness

---

src/views/RecIM/components/Forms/ImageOptions/index.jsx
src/views/RecIM/views/Activity/Activity.module.scss
src/views/RecIM/views/Activity/index.jsx
src/views/RecIM/views/Match/Match.module.scss
src/views/RecIM/views/Match/index.jsx
src/views/RecIM/views/Team/Team.module.scss
src/views/RecIM/views/Team/index.jsx

Team & Activity
--
before:
after:
- overlay is hidden if not admin
- image is button if admin
- spunky shadow expand on hover
- fade transition 
MATCH
--
(web)
(mobile)
- Icons are slightly bigger and have a rounded border

[Rec-IM] Simple image visual update

---

src/views/RecIM/components/List/Listing/index.jsx
src/views/RecIM/views/Team/index.jsx

[Rec-IM] Added attendance counts to match page for admins

---

src/views/RecIM/components/List/Listing/Listing.module.scss
src/views/RecIM/components/List/Listing/index.jsx
src/views/RecIM/views/Activity/components/ScheduleList/index.jsx
src/views/RecIM/views/Match/Match.module.scss
src/views/RecIM/views/Match/index.jsx

[Rec-IM] Display match winner with styling

---

src/views/RecIM/components/Forms/ActivityForm/index.jsx
src/views/RecIM/components/Forms/MatchForm/index.jsx
src/views/RecIM/components/Forms/SeriesForm/index.jsx
src/views/RecIM/components/Forms/SeriesScheduleForm/index.jsx
src/views/RecIM/components/Forms/TeamForm/index.jsx
src/views/RecIM/components/Forms/WaiverForm/index.jsx
src/views/RecIM/views/Activity/index.jsx

This PR fixes a few bugs that were accidentally left in with my last PR. Sorry for the trouble!

[Rec-IM] Form Bug Fixes

---

src/services/housing.ts
src/services/user.ts
src/views/ApartmentApp/components/StudentApplication/index.jsx
src/views/ApartmentApp/index.jsx

This PR fixes 2 issues with ApartApp:
- Students' advisors are fetched when adding them to an application. This throws a 401 Unauthorized, so I surrounded it with a try catch for the time being.
- The ApartApp Object has Missing properties when passed to the api. I added a "Hall" property and set it to blank because it is not actually required.

Fix ApartApp Save Process

---

src/services/housing.ts
src/services/user.ts
src/views/ApartmentApp/components/StudentApplication/index.jsx
src/views/ApartmentApp/index.jsx

See #1754
@EjPlatzer is out so I am requesting a few other approvals.

Release fix apartapp save

---

src/views/RecIM/components/Header/Header.module.scss
src/views/RecIM/components/Header/index.jsx

[Rec-IM] Improve breadcrumbs for mobile

---

src/services/housing.ts
src/views/ApartmentApp/components/StudentApplication/components/Agreements/index.jsx
src/views/ApartmentApp/components/StudentApplication/components/InstructionsCard/index.jsx

This PR will release changes from #1760

Release: ApartApp Messaging

---

src/services/recim/match.ts
src/views/RecIM/components/Forms/SurfaceForm/index.jsx
src/views/RecIM/components/List/Listing/index.jsx
src/views/RecIM/components/List/index.jsx
src/views/RecIM/views/Activity/index.jsx
src/views/RecIM/views/Admin/Admin.module.scss
src/views/RecIM/views/Admin/index.jsx
src/views/RecIM/views/Home/Home.module.scss
src/views/RecIM/views/Home/index.jsx

Not perfect, for example needs loader and might need some reshuffling, but it works!

[Rec-IM] Admin Surface Management

---

.env.development
src/views/RecIM/components/Forms/Form/components/InformationField/index.jsx
src/views/RecIM/components/Helpers/index.js
src/views/RecIM/views/Activity/Activity.module.scss
src/views/RecIM/views/Activity/components/ScheduleList/index.jsx
src/views/RecIM/views/Match/index.jsx

Default User
--
Mobile View:
Desktop View:
Admin
--
Mobile View:
Desktop View:

[Rec-IM] Show Series Schedule (iteration 1)

---

src/views/RecIM/components/Forms/ActivityForm/index.jsx
src/views/RecIM/components/Forms/EditMatchStatsForm/index.jsx
src/views/RecIM/components/Forms/Form/components/ConfirmationRow/index.jsx
src/views/RecIM/components/Forms/Form/components/InformationField/index.jsx
src/views/RecIM/components/Forms/Form/index.jsx
src/views/RecIM/components/Forms/MatchForm/index.jsx
src/views/RecIM/components/Forms/SeriesForm/index.jsx
src/views/RecIM/components/Forms/SeriesScheduleForm/index.jsx
src/views/RecIM/components/Forms/SurfaceForm/index.jsx
src/views/RecIM/components/Forms/TeamForm/index.jsx
src/views/RecIM/components/Forms/WaiverForm/index.jsx

I spent a little bit of time refactoring the RecIM base Forms component, mainly focusing on clarifying the code and removing unnecessary abstractions.
I have an in-progress update to field validation that I think will make everything much nicer, keep an eye for it hopefully soon.

[RecIM] Refactor Forms base component

---

.env.development
src/views/ApartmentApp/components/StudentApplication/index.jsx

This PR will pull in changes that were made directly to master.

Merge Master to Develop

---

src/views/RecIM/components/Forms/ImageOptions/index.jsx

A simple one line fix that prevents the default image got sent to API every single time you drop a custom image in cropper.

[Rec-IM] Image Upload Fix

---

src/services/recim/activity.ts
src/services/recim/participant.ts
src/services/recim/recim.ts
src/services/recim/series.ts
src/views/RecIM/components/Forms/SeriesScheduleForm/index.jsx

Handles changes from here: https://github.com/gordon-cs/gordon-360-api/pull/885
+ API bug fixes

[Rec-IM] schedule surfaces

---

src/views/RecIM/components/List/Listing/Listing.module.scss
src/views/RecIM/components/List/Listing/index.jsx

Though this pr has nothing to do with the branch name `gotoButton`, it does resolve the redirection when click the reject team invite button, which has been tested and worked properly.

[Rec-IM] finally fixed invite redirect when reject

---

src/views/RecIM/components/Forms/InviteParticipantForm/index.jsx
src/views/RecIM/views/Activity/index.jsx

Creating an individual sport team via `add participant`

[Rec-IM] Fix broken invididual sport invite

---

src/views/RecIM/components/Forms/SeriesForm/index.jsx
src/views/RecIM/views/Home/Home.module.scss
src/views/RecIM/views/Home/index.jsx

Simplified definition.
relies on:
https://github.com/gordon-cs/gordon-360-ui/pull/1784

[Rec-IM] series definition

---

src/services/socialMedia.tsx
src/services/user.ts

Added calendar link. Requires validation #1571

Faculty Calendar LInk

---

src/views/RecIM/components/Forms/SeriesForm/index.jsx
src/views/RecIM/components/Forms/WaiverForm/index.jsx
src/views/RecIM/components/List/Listing/index.jsx
src/views/RecIM/components/List/index.jsx
src/views/RecIM/views/Activity/components/ScheduleList/index.jsx
src/views/RecIM/views/Activity/index.jsx
src/views/RecIM/views/Home/Home.module.scss
src/views/RecIM/views/Home/index.jsx

Prevent users from accidentally autoscheduling twice
depends on:
https://github.com/gordon-cs/gordon-360-ui/pull/1785
https://github.com/gordon-cs/gordon-360-ui/pull/1784
https://github.com/gordon-cs/gordon-360-ui/pull/1786

[Rec-IM] autoscheduler loader

---

docs/Developer's Guide.md

Dr. Tuck recommended I add this, after I ran into an issue related to not restarting everything.

Update Developer's Guide.md

---

src/views/RecIM/views/Admin/Admin.module.scss
src/views/RecIM/views/Admin/index.jsx

Implements the admin report functionality per issue 191 on the Recim project board.
Update 6/7: Finished feature, implemented printing, and closed issues on the 360 project board
Here are some pictures of the feature, and some information on testing.
Admin report Dialog Box:
Report printing dialog on Firefox:
And on Chrome:
Also this is how it shows up on small screens and mobile:
I didn't test it on any other browsers, but the css seemed to be fairly robust.  There is a possibility that the window.print method I was using may in some browsers print other elements from the page.
Also, I don't know if this is a desired feature, but it was suggested a couple of times that we could add CSV generation to the reporting functionality, to allow the report to be viewed as a spreadsheet.  Just a …

 [Rec-IM] Admin reporting

---

docs/Developer's Guide.md

The order of ports in the "ssh -R" port forwarding command was reversed so that was updated.  Other changes were made to make terms consistent.

SSH port forwarding port order correction and other tweaks

---

src/components/Header/index.jsx

This PR is for #784 to fix the issue that the tabs are not highlighted correctly sometimes.

Fix the "tab is not highlighted correctly sometimes" Issue

---

src/components/Profile/components/PersonalInfoList/index.jsx
src/services/user.ts

This is a permanent fix to the bandage fix by @bennettforkner 
https://github.com/gordon-cs/gordon-360-ui/issues/1880

S23 fix profile advisors

---

src/components/Header/index.jsx

Reverts gordon-cs/gordon-360-ui#1837

Revert "Fix the "tab is not highlighted correctly sometimes" Issue"

---

src/views/Timesheets/components/SavedShiftsList/SavedShiftsList.module.scss
src/views/Timesheets/components/SavedShiftsList/index.jsx

Submit to dropdown fix

---

src/components/EventList/components/EventItem/index.jsx

Added check for empty date strings to add-to-calendar-button.  Potentially should be merged to master to fix bug there, so let me know how you want me to approach that...

Fixed cl&w Credits Button Bug

---

src/components/EventList/components/EventItem/index.jsx

The event info panel closes when you click on the add to calendar button

---

.env.development
src/components/GordonTooltip/GordonTooltip.module.scss
src/components/GordonTooltip/index.jsx
src/components/Header/components/NavAvatarRightCorner/NavAvatarRightCorner.module.scss
src/components/Header/components/NavAvatarRightCorner/index.jsx
src/components/PWAInstructions/PWAInstructions.module.scss
src/components/PWAInstructions/index.jsx
src/views/InvolvementProfile/components/Membership/components/AdminCard/components/RequestsReceived/RequestsReceived.module.scss
src/views/InvolvementProfile/components/Membership/components/AdminCard/components/RequestsReceived/index.jsx
src/views/Timesheets/components/ShiftItem/ShiftItem.module.scss
src/views/Timesheets/components/ShiftItem/index.jsx

clean up deprecated styles packages

---

src/services/membership.ts

to match the API change https://github.com/gordon-cs/gordon-360-api/commit/da31131606e24360e82fcbb500a8b208588a6cfe

turned the patch request to change the membership privacy to put

---

src/components/Profile/components/OfficeInfoList/UpdateOfficeLocationDialog/index.jsx
src/services/user.ts

API: https://github.com/gordon-cs/gordon-360-api/pull/953

turned both routes from patch to put

---

docs/ThemePaletteDocs.md
src/components/EventList/components/EventItem/index.jsx
src/components/GordonTooltip/GordonTooltip.module.scss
src/components/GordonTooltip/index.jsx
src/components/Header/components/NavAvatarRightCorner/NavAvatarRightCorner.module.scss
src/components/Header/components/NavAvatarRightCorner/index.jsx
src/components/PWAInstructions/PWAInstructions.module.scss
src/components/PWAInstructions/index.jsx
src/components/Profile/components/MembershipsList/components/MembershipInfoCard/MembershipInfoCard.module.scss
src/components/Profile/components/MembershipsList/components/MembershipInfoCard/index.jsx
src/components/Profile/components/MembershipsList/index.jsx
src/components/Profile/components/OfficeInfoList/UpdateOfficeLocationDialog/index.jsx
src/components/Profile/components/OfficeInfoList/index.jsx
src/components/Profile/components/PersonalInfoList/PersonalInfoList.module.scss
src/components/Profile/components/PersonalInfoList/index.jsx
src/services/membership.ts
src/services/peopleSearch.ts
src/services/user.ts
src/views/InvolvementProfile/components/Membership/components/AdminCard/components/RequestsReceived/RequestsReceived.module.scss
src/views/InvolvementProfile/components/Membership/components/AdminCard/components/RequestsReceived/index.jsx
src/views/PeopleSearch/components/SearchFieldList/index.tsx
src/views/Timesheets/Timesheets.module.scss
src/views/Timesheets/components/ShiftItem/ShiftItem.module.scss
src/views/Timesheets/components/ShiftItem/index.jsx
src/views/Timesheets/index.jsx

Reverts gordon-cs/gordon-360-ui#1973
API server is now deployed, so this should work now.  (It was hung, waiting for me to approve the deploy action.)

Revert "Revert "Release 07/05/2023""

---

src/components/Profile/components/MembershipsList/index.jsx

issue: https://github.com/gordon-cs/gordon-360-ui/issues/1974

added shaded note about involvements privacy

---

src/views/Timesheets/components/SavedShiftsList/index.jsx

Fix box shadow for SavedShiftsList

---

src/views/InvolvementProfile/components/Membership/index.jsx

Changed "Subcriber" to "Subscriber"

Fixed spelling typo

---

src/app.module.scss
src/components/Header/index.jsx
src/components/QuickLinksDialog/QuickLinksDialog.module.scss
src/components/QuickLinksDialog/index.tsx
src/views/About/About.module.scss
src/views/About/index.jsx
src/views/BannerSubmission/BannerSubmission.module.scss
src/views/BannerSubmission/index.jsx
src/views/Events/Events.module.scss
src/views/Events/index.jsx
src/views/Help/Help.module.scss
src/views/Help/index.jsx
src/views/Home/components/CLWCreditsDaysLeft/index.jsx
src/views/Home/components/DaysLeft/index.jsx
src/views/Home/components/DiningBalance/index.jsx
src/views/Home/components/Doughnut.module.scss
src/views/Home/components/NewsCard/index.jsx
src/views/IDUploader/IDUploader.module.scss
src/views/IDUploader/index.jsx
src/views/InvolvementProfile/InvolvementProfile.module.scss
src/views/InvolvementProfile/index.jsx
src/views/InvolvementsAll/Involvements.module.scss
src/views/InvolvementsAll/components/Requests/Requests.module.scss
src/views/InvolvementsAll/index.jsx
src/views/PeopleSearch/components/SearchFieldList/SearchFieldList.module.scss
src/views/PeopleSearch/components/SearchFieldList/index.tsx
src/views/Timesheets/Timesheets.module.scss
src/views/Timesheets/components/SavedShiftsList/index.jsx
src/views/Timesheets/index.jsx

Reverts gordon-cs/gordon-360-ui#1980

Revert "S23 page headers"

---

src/views/Home/components/GuestWelcome/index.jsx

Small fix Dr.Senning pointed out. Just had to put space between "Gordon" and "360" in the login page.

Minor fix of rewording login page title

---

src/components/Profile/components/MembershipsList/MembershipsList.module.scss
src/components/Profile/components/MembershipsList/index.jsx

these changes were already pushed previously, not sure why shows the old version in develop
old pull request: https://github.com/gordon-cs/gordon-360-ui/pull/1998
before:
now:

Scss changes for note design 

---

src/services/auth.ts
src/views/RecIM/components/List/Listing/index.jsx
src/views/RecIM/components/List/index.jsx
src/views/RecIM/views/Admin/index.jsx

Add remaining statuses controllable purely from the admin control panel
- Pending/Cleared can be toggled
- Suspended/Cleared can be toggled (as well as a specific datetime for suspensions to end)
- Banned/Cleared can be toggled

[Rec-IM] participant statuses

---

src/views/RecIM/components/List/Listing/Listing.module.scss
src/views/RecIM/components/List/Listing/index.jsx
src/views/RecIM/components/List/index.jsx
src/views/RecIM/views/Activity/components/ScheduleList/index.jsx
src/views/RecIM/views/Match/index.jsx

Match page now shows recent matches or `This team has not played any matches`. API query limits recent matches to five on 1v1 matches. None are rendered for ladder matches

[Rec-IM] match page update

---

src/components/Error/Error.module.scss
src/components/Error/index.jsx

Made color changes for error screens in RecIM so the colors are less disturbing.

Color changes for error screens, RecIM

---

src/theme.ts

Very minor cleanup and code updates

Finishing touches on theme.ts

---

src/components/GordonDialogBox/GordonDialogBox.module.scss
src/services/recim/series.ts
src/views/RecIM/views/Activity/components/ScheduleList/index.jsx
src/views/RecIM/views/Home/Home.module.scss
src/views/RecIM/views/Home/index.jsx

helpful information set that gives `number of games made`, `end time of last game`

[Rec-IM] Auto Schedule Estimate

---

src/views/Timesheets/index.jsx

This patch introduces a time-sensitive update to the Timesheets page. See #2110 for details.

Patch: migrate timesheets

---

src/theme.ts
src/views/RecIM/views/Home/Home.module.scss
src/views/RecIM/views/Home/index.jsx

This PR will add a red alert message to the RecIM homepage when a participant must sign the waiver:

Add Alert Message for Unsigned Rec/IM Waiver

---

src/views/RecIM/components/Forms/WaiverForm/index.jsx
src/views/RecIM/views/Home/index.jsx

Fix jotform waiver url

---

src/views/RecIM/components/Forms/WaiverForm/index.jsx

Hotfix: jotform waiver url

---

src/views/HousingLottery/HousingLottery.module.scss
src/views/HousingLottery/index.jsx
src/views/HousingLottery/studentView/Agreements/index.jsx

Made fixes regarding the component agreements.

Fixes regarding Agreements

---

src/services/housing.ts
src/views/HousingLottery/HousingLottery.module.scss
src/views/HousingLottery/adminView/index.jsx
src/views/HousingLottery/index.jsx
src/views/HousingLottery/studentView/PreferenceBox/index.jsx
src/views/HousingLottery/studentView/PreferredHall/index.jsx
src/views/HousingLottery/studentView/StudentApplicants/index.jsx
src/views/HousingLottery/studentView/index.jsx

send the application data from frontend to backend and from backend to frontend

Hl connect front back

---

src/views/HousingLottery/adminView/index.jsx
src/views/HousingLottery/index.jsx

Added a feature to distinguish if the user is logged in and if the logged in user is a student or an admin.

Hl sort user

---

src/views/HousingLottery/HousingLottery.module.scss
src/views/HousingLottery/studentView/PreferenceBox/index.jsx

preference should save the selected options from radio buttons when user made selection. 
card header function could reuse by mutiple times in the application page.

preference console report fix and header sharing with applicant card

---

.env.development
package-lock.json
package.json
src/views/HousingLottery/HousingLottery.module.scss
src/views/HousingLottery/index.jsx
src/views/HousingLottery/studentView/Instructions/index.jsx
src/views/HousingLottery/studentView/PreferenceBox/index.jsx
src/views/HousingLottery/studentView/PreferredHall/index.jsx
src/views/HousingLottery/studentView/StudentApplicants/index.jsx
src/views/HousingLottery/studentView/index.jsx

I improved the student UI view.

Adjusted the layout of boxes in the student UI

---

src/views/HousingLottery/HousingLottery.module.scss
src/views/HousingLottery/studentView/Instructions/index.jsx
src/views/HousingLottery/studentView/PreferenceBox/index.jsx
src/views/HousingLottery/studentView/PreferredHall/index.jsx
src/views/HousingLottery/studentView/index.jsx

Error fixes for our MVP mainly regarding preference box and Agreements. For preference, clicking the 'submit' button on studentView did not deliver any data from the preference box so I had to fix that bug. As for the Agreements, it returned an "onChange() is not a defined function" error whenever we click any of the check boxes in the 'agreements' component. I fixed that error and added a feature that students cannot submit the application unless they have clicked(agreed to) all the checkbox.

Hl premvp fix

---

src/views/HousingLottery/studentView/Instructions/index.jsx

Just a minor fix to correct text error.

Very Minor fix, adding for MVP presentation

---

.env.development
.env.production
src/views/HousingLottery/HousingLottery.module.scss
src/views/HousingLottery/adminView/index.jsx

Start creating the admin view for the housing lottery.
Missing applicant's standing for application table
You may notice the stand columns are missing from the row since I haven't figured out to get the highest standing from the applicants
It would make another 5 columns to view the current standing of each applicant and find the highest-standing applicant to assign the lottery number

Admin view

---

src/views/RecIM/components/Forms/InviteParticipantForm/index.jsx

I am not exactly sure why the username is coming up as null here, but handling the null case fixes the issue for the hotfix's sake.

HotFix: Fix RecIM Username Search

---

src/views/RecIM/components/Forms/InviteParticipantForm/index.jsx

Hotfix PROD: Fix RecIM Username Search

---

package-lock.json
src/views/HousingLottery/adminView/index.jsx

update Json array

---

src/views/HousingLottery/studentView/Instructions/index.jsx

Update the Housing Lottery FAQ in the instructions page

Hl instructionsupdate

---

src/components/Profile/components/OfficeInfoList/index.jsx

HotFix: CTS Ticket 169936

---

src/components/Profile/components/OfficeInfoList/UpdateOfficeLocationDialog/index.jsx
src/services/peopleSearch.ts
src/services/user.ts
src/views/PeopleSearch/components/SearchFieldList/index.tsx

Depends on gordon-cs/gordon-360-api#1023.
Fix the UpdateOfficeLocation component to send building code instead of building description.

Send code. not description, updating office location

---

src/views/HousingLottery/adminView/index.jsx

Added UI changes in the Admin react table. Fixed header and added vertical scroll so it is more convenient for users to read data. Every other columns also shows in different colors to make the data more easily distinguishable for the user.

Better UI for the React Table

---

src/views/HousingLottery/adminView/index.jsx
src/views/HousingLottery/studentView/index.jsx

Add snackbar for submitting application and due date

Hl snackbar

---

src/views/HousingLottery/studentView/PreferredHall/HallSlotComponent/index.jsx

A feature to dynamically remove halls from the selection list once chosen to present only the remaining options for subsequent selections.

Removing Selected Halls from Preferred Hall Options

---

src/views/HousingLottery/adminView/index.jsx

Changed the input data type from text input to DatePicker

Set a proper date input

---

src/views/HousingLottery/studentView/StudentApplicants/index.jsx
src/views/HousingLottery/studentView/index.jsx

Fixed handleApplicantChange() function and changed Gird tags to List according to the feedback.

Fixes for StudentApplications file

---

src/views/HousingLottery/studentView/StudentApplicants/index.jsx
src/views/HousingLottery/studentView/index.jsx

Reverts gordon-cs/gordon-360-ui#2210
Something noticed issues caused the page doesn't loading properly

Revert "Fixes for StudentApplications file"

---

src/views/HousingLottery/studentView/Instructions/index.jsx
src/views/HousingLottery/studentView/PreferenceBox/index.jsx
src/views/HousingLottery/studentView/PreferredHall/HallSlotComponent/hallSlotComponent.module.scss
src/views/HousingLottery/studentView/PreferredHall/HallSlotComponent/index.jsx
src/views/HousingLottery/studentView/PreferredHall/index.jsx
src/views/HousingLottery/studentView/PreferredHall/preferredHall.module.scss
src/views/HousingLottery/studentView/StudentApplicants/ApplicantFields/index.jsx
src/views/HousingLottery/studentView/StudentApplicants/index.jsx
src/views/HousingLottery/studentView/index.jsx

Hl student UI fix

---

src/components/PhotoCropper/index.tsx
src/views/About/contributors.json
src/views/IDUploader/index.jsx

**Changes fixed in PR:**
- Fixed typos
- Fixed padding issue
Before:
After:

S24 fixing typos

---

src/components/GordonDialogBox/index.tsx
src/components/Profile/components/PersonalInfoList/index.jsx
src/views/IDUploader/index.jsx

- Re-added close button functionality to GordonDialogBox component
- Added ability to close mailbox opening instructions by clicking off

S24 closing mailbox instructions

---

src/services/peopleSearch.ts

- Fixed the unassigned search filter so that it only returns unassigned students

fix unassigned returning all students

---

src/components/Profile/components/SchedulePanel/index.tsx
src/views/Home/components/DaysLeft/index.jsx

I added the current term with the dates to the non student views as requested in the project board by Dr. Tuck. I tested this for both faculty and staff views, along with making sure that it does not interfere with the student view.
Fixes #2045

Current Term for Faculty

---

src/views/PeopleSearch/components/SearchFieldList/components/SearchField/index.tsx
src/views/PeopleSearch/components/SearchFieldList/index.tsx

- Replaced slider to choose graduation year range with two SearchFields
- Added an option to the SearchField component to choose whether or not the default menu option _All_ is shown in the menu
- Disabled toggle to choose graduation year or graduation year range when alumni checkbox is not selected

S24 alumni year range

---

src/components/EventList/components/EventItem/index.jsx

#2135 
Made event item focusable with tab key and description of event focusable with tab key, **but** not able to make event expand with enter key.
Just found this was related to #2133 , not sure if the way I'm doing it is the best

Make Events Focusable with Tab

---

src/services/recim/participant.ts
src/views/RecIM/components/List/index.jsx
src/views/RecIM/views/Home/index.jsx

https://github.com/gordon-cs/RecIM-Docs/issues/104
API: https://github.com/gordon-cs/gordon-360-api/pull/1051
- Removed Hall Rankings (currently broken)
- Add past/upcoming Matches

[Rec-IM] Add service for participant matches

---

src/components/DynamicButton/index.tsx
src/components/GordonOffline/index.tsx
src/views/ApartmentApp/components/StudentApplication/components/BottomBar/index.jsx

The DynamicButton component is a thin wrapper around MUI's `Button`, so I made it behave like one, in that it accepts all `Buton` props and forwards them to the underlying `Button`.

Streamline typing and composability of DynamicButton

---

src/components/Profile/components/VictoryPromise/components/GraphDisplay.tsx

I cleaned up the victory promise graph slightly, and fixed the `minimumScore` so that empty scores are again proportional to the lowest non-empty score.

Victory Promise Improvements

---

src/components/Profile/components/PersonalInfoList/index.jsx
src/views/InvolvementProfile/components/ContactListItem/index.jsx
src/views/InvolvementProfile/components/Membership/components/MemberList/MemberList.module.scss
src/views/InvolvementProfile/components/Membership/components/MemberList/components/MemberListItem/index.jsx
src/views/InvolvementProfile/components/Membership/components/MemberList/index.jsx

Various Color Fixes

---

src/components/Header/index.jsx
src/views/Home/components/GuestWelcome/index.jsx

Reference #2132 
- Login main image now has alt text.
- Screen reader now more clearly states whether you are on the home page when 360 logo is focused on.
- Other tabs on the header and in hamburger already indicate whether you are on a page and which page you are on.

Improve Login/Home Page Accessibility

---

src/components/Nav/components/NavAvatar/index.tsx

Addresses the following console errors.

Reduce Startup Console Errors

---

src/views/InvolvementProfile/index.jsx

Add Headers to Involvement Profiles

---

src/services/event.ts
src/views/Events/index.jsx

Paginating the Events Page by Date (ie. "This Week", "Two Months", "One Month").

Paginate Events Page

---

src/views/About/contributors.json

- Added our names and years to the about page
- Thanks for the summer everyone :)

S24 adding practicum names

---

src/views/Events/index.jsx

Changed to ScottieCyan so that contrast tests passed.
From this...
To this...

Change Past Events Checkbox Color

---

src/views/Home/components/DiningBalance/index.jsx

swap the day left color with day finished color, so every color layers are counterclockwise.

Swap the colors for days remaining

---

src/components/Header/index.tsx
src/routes.jsx
src/views/Housing/index.jsx

- Created initial page for Housing
- Added `/housing` to `src/routes`
- Added Housing tab to the header

WMR Initial tab

---

src/components/Header/index.tsx
src/components/Nav/components/NavLinks/index.tsx
src/routes.jsx
src/views/CampusSafety/CampusSafety.module.scss
src/views/CampusSafety/index.tsx

Initial placeholder version of the campus safety page, for the GCPD Safety Page and Lost and Found Project

Added new campus safety resources page, initial commit

---

src/views/CampusSafety/index.tsx

Added Several Links on Safety Page

---

src/views/Housing/components/ResidentView/MyHall/index.jsx
src/views/Housing/components/ResidentView/MyRA/index.jsx
src/views/Housing/components/ResidentView/OnDuty/index.jsx
src/views/Housing/components/ResidentView/Resources/index.jsx
src/views/Housing/index.jsx

* Created `MyHall` component
* Created `MyRA` component
* Created `OnDuty` component
* Created `Resources` component
* Added all components to the `Housing` index.jsx

Create more components for ResidentView

---

src/views/CampusSafety/CampusSafety.module.scss
src/views/CampusSafety/index.tsx

Added red visual alert for emergency number

---

src/services/auth.ts
src/views/Housing/index.jsx

Add Auth group for RA permissions and pulled in HousingAdmin auth group for use with Res Life staff

Add RA Auth Group

---

src/views/Housing/components/RAView/components/Schedule/index.jsx
src/views/Housing/components/RAView/components/TaskList/index.jsx
src/views/Housing/components/RAView/index.jsx
src/views/Housing/index.jsx

- Basic skeleton of some of the RA View!
- A work in progress but there is stuff
- Added component folders for different things

wmr - Ra view actual

---

src/views/CampusSafety/views/LostAndFound/LostAndFound.module.scss
src/views/CampusSafety/views/LostAndFound/index.tsx

This is a sample code for the Lost and Found UI. This shows sample data that is hard coded into it. Yet to add changes to allow it to pull data from the backend.

UI with sample data for Lost and Found Page

---

src/components/Nav/components/NavLinks/index.tsx
src/views/Housing/index.jsx

- added Housing Button to the side navigation

wmr - add housing button to side navigation

---

src/services/lostAndFound.ts

Wrote front-end service for getting missing item by ID

Added getMissingItemReport service

---

src/views/CampusSafety/components/Header/Header.module.scss
src/views/CampusSafety/components/Header/index.tsx
src/views/CampusSafety/index.tsx
src/views/CampusSafety/views/LostAndFound/LostAndFound.module.scss
src/views/CampusSafety/views/LostAndFound/index.tsx
src/views/CampusSafety/views/MissingItemForm/index.tsx
src/views/CampusSafety/views/SafetyPage/index.tsx

Breadcrumbs are working and mobile view works great as well

General User L&F Home Page Mobile View + Header Breadcrumbs Functioning

---

.env.development
src/services/auth.ts
src/services/lostAndFound.ts
src/views/CampusSafety/components/Header/Header.module.scss
src/views/CampusSafety/components/Header/index.tsx
src/views/CampusSafety/index.tsx
src/views/CampusSafety/views/LostAndFound/index.tsx
src/views/CampusSafety/views/LostAndFoundAdmin/LostAndFoundAdmin.module.scss
src/views/CampusSafety/views/LostAndFoundAdmin/index.tsx
src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/MissingItemList.module.scss
src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/components/MissingItemReportData/MissingItemReportData.module.scss
src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/components/MissingItemReportData/index.tsx
src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/index.tsx

A page containing the list of all missing items, with filters to search the list.  Each item entry is clickable to view more details.

Data Entry Missing Item Database Page

---

src/views/Housing/components/RAView/index.jsx
src/views/Housing/index.jsx

Thank you to @Centerville1 and @Mrand03 for all y'all's help ^^

Wmr button hall select

---

src/views/Housing/components/RDView/components/RoomRanges/index.jsx

**Changes in PR:**
- The `RoomRanges` component now has a way to delete an RA/AC assignment to a room range by simply pressing the remove button next to the assignment.

wmr- Completed room range delete RA Assignment

---

src/views/Housing/components/ResidentView/components/MyHall/index.jsx
src/views/Housing/components/ResidentView/components/MyRAC/index.jsx

- Created the function `fetchRacName` in the `MyRAC` file, which sets the resident's RA based on the resident's room range

wmr - Display the full name of resident's RA

---

.env.development
src/views/Housing/components/RDView/components/RoomRanges/index.jsx

This was done with **help from ChatGPT please take extra caution** when reviewing changes. All functionality has been tested

Updated layout for RoomRanges in RD view ()

---

src/services/residentLife/roomRanges.ts
src/views/Housing/components/RDView/components/RoomRanges/index.jsx
src/views/Housing/index.jsx

- created `/services/residentLife/` folder
- migrated `roomRanges` api calls to aforementioned folder
Note: Adding and removing assignments has not been fully tested yet due to database bug(?)

WMR - Migrate api calls

---

.env.development
src/views/Housing/components/RAView/index.jsx

Adjusted halls to use building codes
new call to api to see if RA is checked in
Halls get auto selected based on tha RAs housing status 
when the village is selected all needed building codes get passed to the API

RA Checkin work

---

src/views/Housing/components/RDView/components/RoomRanges/index.jsx
src/views/Housing/index.jsx

When filtering data the index used for selected list item was off, causing unexpected behavior. switch from using the index to passing the ID of the list item to the API function call
button for remove room range added back

Fixed indexing issue

---

src/services/residentLife/RA_OnCall.ts
src/views/Housing/components/RAView/index.jsx
src/views/Housing/components/RDView/components/OnDutyTable/index.jsx

Adjusted the RA checkin confirmation to show the hall name instead of the building code using a map like @dli505 was doing before

Populated On duty table with data

---

.env.development
src/services/residentLife/RA_Info.ts
src/views/Housing/components/ResidentView/components/MyHall/index.jsx
src/views/Housing/components/ResidentView/components/MyRA/index.jsx
src/views/Housing/components/ResidentView/components/OnDuty/index.jsx
src/views/Housing/components/ResidentView/index.jsx

`Changes in PR`
- Created `RA_Info.ts` in `/services/residentLife/`to store all api calls
- Displayed RA photo in the "Where's My RA" table
- Worked to make `OnDuty`, `MyHall` and `MyRA` more responsive

wmr - Display RA Photo

---

src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/index.tsx
src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/components/ReportItemPageOther/index.tsx

A red snackbar with an error message now pops up in the lower left corner when a report fails

Completed Snackbar for Errors

---

src/services/auth.ts
src/views/Housing/components/RDView/components/MobileView/index.jsx
src/views/Housing/components/StaffView/index.jsx
src/views/Housing/index.jsx

Added on call table to mobile view component
Added standard staff view and pulled in table and mobile view components
Added auth group to use for physical plant staff to get housing info
@EjPlatzer for the auth groups will we need to make 360-RA-sg and 360-PLT-SG groups to use? we currently are just pulling in the main groups

Rd on call table

---

src/services/residentLife/ResidentStaff.ts
src/views/Housing/components/ResidentView/components/MyHall/index.jsx
src/views/Housing/components/ResidentView/components/MyRA/index.jsx

**Changes made in PR**
- Renamed the typescript file 
- Added `fetchRdInfo` function in the typescript file
- Took out the hardcoded times on the table (the table is not part of MVP, so the times are not necessarily needed
- Screenshot is from Mya's login since my login (Wilson Hall) does not have an assigned RD in the View that the API endpoint  is pulling from

Display RD Name on My Hall Component Card

---

src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/MissingItemList.module.scss
src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/index.tsx

Quick Fix for Project Board Issue #81

Quick Fix for Project Board Issue #81

---

src/services/residentLife/RA_Info.ts
src/views/Housing/components/RAView/index.jsx

Created a simple way for RAs and ACs to be able to set their preferred contact which is the method in which residents will be able to contact them. It gets the RA/AC's ID and what contact they choose, then it posts this information to the database to be pulled by the resident and RD view.

wmr - RA can set preferred contact

---

src/views/Housing/components/ResidentView/components/MyHall/index.jsx
src/views/Housing/components/ResidentView/components/MyRA/index.jsx

- @RossClark01 brought up a good point that the username of an RA might not always be their "first.last" name. Sometimes, they might have just an initial as a first name, or have a number in the last name, so pulling the username from the email would be the best way to get the username for all cases.
- Mistakenly put RD instead of RA, so I fixed that real quick

wmr - Fixed RA UI error and fixed user profile links

---

src/views/CampusSafety/index.tsx
src/views/CampusSafety/views/LostAndFound/index.tsx
src/views/CampusSafety/views/LostAndFound/views/ReportFound/index.tsx
src/views/Home/components/LostAndFoundCard/index.tsx

Report found item page, with buttons linking to it from the home page widget and the main lost and found page.

Report Found Item Page

---

src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/index.tsx

Fix for Bug on Project Board #97

---

src/services/residentLife/RA_OnCall.ts
src/views/Housing/components/ResidentView/components/OnDuty/index.jsx
src/views/Housing/index.jsx

- Added API call to `RA_OnCall.ts` file to pull the On Duty RA's information
- Filled in the needed information for `On Duty` component (name, room #, contact info, photo, profile link)
- @Mrand03 or @dli505, one of you should test it to see if the information displays in your resident view. On the backend, the `Housing.Current_On_Call`, is the view that we pull from to display this information. Since my dorm (Wilson) does not have an RD (look at `RD_Info` view), the RA on duty for Wilson does not show up in the `Housing.Current_On_Call` view, so I cannot see whether it displays, but the logic to display it should be right
- This is a joint pull request with ( https://github.com/gordon-cs/gordon-360-api/pull/1103 ), so that needs to be approved before the results …

wmr - Display On Duty Component Info

---

src/views/Housing/components/RDView/components/OnDutyTable/index.jsx
src/views/Housing/components/RDView/components/RoomRanges/index.jsx
src/views/Housing/components/RDView/index.jsx

**Changes Made in PR:**
- Began cleaning up the RD View which included deleting the editDocs component and putting the code in the RDView index.jsx, commenting out the taskList component which will not be part of the MVP (This will be deleted when we make our release branch), and made changes so each color for text, hover and click look good on both light and dark mode. 
- I am still working to find little issues in the UI but the main issues I saw are fixed.

Stared RDView Code and File Cleanup

---

src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/MissingItemCreate.module.scss
src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/index.tsx

Fixed issue where one of the color items was being split on Safari

Color Wrapping Bug Fix

---

src/views/CampusSafety/views/LostAndFound/index.tsx

Board Issue 82, and fixed merge conflicts

Board issue82 richie

---

src/views/CampusSafety/views/LostAndFound/LostAndFound.module.scss
src/views/CampusSafety/views/LostAndFound/index.tsx
src/views/CampusSafety/views/LostAndFound/views/MissingItemEdit/MissingItemEdit.module.scss
src/views/CampusSafety/views/LostAndFound/views/MissingItemEdit/index.tsx
src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/index.tsx
src/views/Home/components/LostAndFoundCard/LostAndFoundCard.module.scss
src/views/Home/components/LostAndFoundCard/index.tsx

As a general User, i want to get notified when my item is marked as Found, and i want to be able to mark my Item as PickedUp, after i pick it up from Gordon Police. 
Also for Git Board Issue #5

Pickup richie

---

src/views/Housing/components/RDView/components/RoomRanges/index.jsx
src/views/Housing/components/RDView/index.jsx

**Changes made in this PR**
- Room ranges UI was made to be cleaner and more appealing 
- Added instructions and clarified the instructions that were there for room ranges so that everything is esay to do for the user

wmr- Minor changes to UI on Room Ranges

---

src/views/Housing/components/RAView/components/Links/index.jsx
src/views/Housing/components/RAView/components/Schedule/index.jsx
src/views/Housing/components/RAView/index.jsx

- added mobile view for RA view
- removed TaskList and Scheduling
- added links for work requests and GoPo
- made button prettier
- formatted everything

WMR - cleaning up ra UI

---

src/views/Home/components/LostAndFoundCard/LostAndFoundCard.module.scss
src/views/Home/components/LostAndFoundCard/index.tsx
src/views/Home/index.jsx

Fixed Issues #119, 120, 121, 123, 124, and 125.

More of Evan's Fixes

---

src/views/CampusSafety/views/LostAndFound/index.tsx
src/views/CampusSafety/views/LostAndFound/views/MissingItemEdit/MissingItemEdit.module.scss
src/views/CampusSafety/views/LostAndFound/views/MissingItemEdit/index.tsx

Finished the Status and Made fields for other status uneditable

Status for items and uneditable fields

---

src/views/Housing/components/ResidentView/components/MyHall/index.jsx

- Changed hall mascot photo paths so that they are relative to the root, rather than the directory. This is most likely why it was not showing up in our Sp-branch.

Wmr display hall images on sp

---

src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/index.tsx

Change the admin list view to sort by dateCreated, that way new reports always show up on top.

Change Admin List to sort by Created Date

---

src/views/ResLife/components/ResidentView/components/MyRA/index.jsx
src/views/ResLife/components/ResidentView/components/OnDuty/index.jsx
src/views/ResLife/utils/isMobile/isMobile.ts
src/views/ResLife/utils/staffType/staffType.ts

**Changes in PR**
- Removed all instances of isMobile utility function since Evan said it was not needed
- Changed staff type to be deeply immutable so that it cannot be changed when imported

Wmr UI fixes

---

src/views/ResLife/components/ResidentView/components/MyRA/index.jsx
src/views/ResLife/index.jsx

Logic for hiding the page when browsed directly by non resident students
notice added when no RA assigned on resident view

WMRA UI  updates for deployment

---

src/views/CampusSafety/components/Header/index.tsx
src/views/CampusSafety/index.tsx
src/views/CampusSafety/views/LostAndFoundAdmin/index.tsx
src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/components/MissingItemReportData/index.tsx
src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/index.tsx

Uses URL query parameters to store the filter values, and maintains the filter values across navigation.

Report Filters Saved in URL Query Params

---

src/views/Home/components/LostAndFoundCard/components/ActiveReports/index.tsx

Changed link from the edit form page to the report lost page

Fixed broken link on home page

---

src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/index.tsx

Updated Last Checked Colors

---

src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/components/ReportItemPageOther/index.tsx

I just made the same changes I made on the general user side to the admin side.

Date Input via Keyboard Disabled for Admin Form

---

src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/components/reportStolen/index.tsx

Require Description for Stolen Items

---

src/services/lostAndFound.ts
src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/index.tsx

I still have to remove the code for the sort thing, i only commented out the code did not remove it yet.

Lazy Loading for Missing Item Reports

---

.env.development
src/views/ResLife/components/RAView/index.jsx
src/views/ResLife/index.jsx

RAs now have the option to view who is on call for each hall if they are on call.
Added logic to housing developer view selector to avoid a looping issue

Added RAs on call to RA view

---

src/services/http.ts
src/services/lostAndFound.ts
src/views/CampusSafety/components/Header/index.tsx
src/views/CampusSafety/index.tsx
src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/index.tsx
src/views/CampusSafety/views/LostAndFound/views/MissingItemEdit/index.tsx
src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/components/ReportItemPageOther/index.tsx
src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/index.tsx

Fixes from UI Review

---

src/components/Header/index.tsx
src/services/lostAndFound.ts
src/views/CampusSafety/components/Constants/index.ts
src/views/CampusSafety/components/Helpers/index.ts
src/views/CampusSafety/views/LostAndFound/index.tsx
src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/index.tsx
src/views/CampusSafety/views/LostAndFound/views/MissingItemEdit/index.tsx
src/views/CampusSafety/views/LostAndFoundAdmin/FoundItems/FoundItemsEdit/index.tsx
src/views/CampusSafety/views/LostAndFoundAdmin/FoundItems/FoundItemsList/index.tsx
src/views/CampusSafety/views/LostAndFoundAdmin/FoundItems/index.tsx
src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/components/MissingItemReportData/index.tsx
src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/components/ReportItemPageOther/index.tsx
src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/index.tsx
src/views/Home/components/LostAndFoundCard/components/ActiveReports/index.tsx
src/views/Home/components/LostAndFoundCard/components/FoundReports/index.tsx

The start of defining constants and helper methods in one place.  More to be added and to build off of this.
Most likely we'll want to define some more components in the components folder.  See Rec-IM for good examples of doing this type of thing.

Review Improvements and Code Reuse

---

src/views/CampusSafety/views/LostAndFoundAdmin/FoundItems/FoundItemFormCreate.module.scss
src/views/CampusSafety/views/LostAndFoundAdmin/FoundItems/index.tsx

Fixes for the comments from Matt's review:
- Removed unused styling
- Updated finder input to allow separate first and last name fields
- Made finder fields functional
- Removed console.logs
- Removed unnecessary snackbar
- Fixed incorrect navigation routes
- Implemented people search and guest input for item owner
- Added a note saying that valuable items should go in the safe

Found Item Create Fixes

---

src/routes.jsx
src/services/residentLife/RD_TaskList.ts
src/views/ResLife/components/RDView/components/EditDocs/index.jsx
src/views/ResLife/components/RDView/components/TaskList/index.jsx

**Changes made in this PR:**
- Used the needed API calls to add tasks to the task list as well as display the task list for given halls when a hall is selected. 
- User can now also delete the task from the task list and it successfully deletes it from the database and no longer shows it on the task list. 
- I am now working on getting the edit function to work so that when the user clicks the edit button, the task maker fields fill out and they can edit it.

wmr - API Calls Added to RD Task List

---

src/views/CampusSafety/components/CustomDatePicker/index.tsx
src/views/CampusSafety/components/GordonPersonAutocomplete/index.tsx
src/views/CampusSafety/components/Helpers/index.ts
src/views/CampusSafety/components/StatusChip/StatusChip.module.scss
src/views/CampusSafety/components/StatusChip/index.tsx
src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/index.tsx
src/views/CampusSafety/views/LostAndFound/views/MissingItemEdit/index.tsx
src/views/CampusSafety/views/LostAndFoundAdmin/FoundItems/FoundItemsEdit/index.tsx
src/views/CampusSafety/views/LostAndFoundAdmin/FoundItems/FoundItemsList/index.tsx
src/views/CampusSafety/views/LostAndFoundAdmin/FoundItems/index.tsx
src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/MissingItemList.module.scss
src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/components/MissingItemReportData/index.tsx
src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/components/ReportItemPageOther/index.tsx
src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/index.tsx

Moved several more reused components and methods into the components folder.
Reusable Methods
- capitalizeString
- Url Query Methods
Reusable Components
- CustomDatePicker
- StatusChip
- Gordon People Search Autocomplete fields

Code Reuse

---

src/views/ResLife/components/RDView/components/RoomRanges/index.jsx
src/views/ResLife/components/RDView/components/TaskList/index.jsx

**Changes Made In PR:**
* Added scrollbar to tasklist
* Styled the tasklist component 
* Added a light/dark mode logic to show different stylings

wmr - Added styling to RD Room Range and RD Task List

---

src/views/ResLife/components/RAView/index.jsx
src/views/ResLife/components/RDView/components/OnDutyMobileView/index.jsx
src/views/ResLife/components/RDView/components/TaskList/index.jsx
src/views/ResLife/components/RDView/index.jsx
src/views/ResLife/components/StaffView/index.jsx

updated task list to allow for one off event submission

Updated Basic Select Name

---

src/views/ResLife/components/RAView/components/CheckIn/index.jsx
src/views/ResLife/components/RAView/index.jsx

- Refactored RA CheckIn to be its own separate component

Wmr checkin refactoring

---

src/views/ResLife/components/RAView/components/CheckIn/index.jsx
src/views/ResLife/components/RAView/components/TaskList/index.jsx
src/views/ResLife/components/RAView/index.jsx
src/views/ResLife/components/RDView/components/OnDutyMobileView/index.jsx
src/views/ResLife/components/RDView/index.jsx
src/views/ResLife/components/ResidentView/components/MyHall/index.jsx

* Tasklist will always be displayed, but if an RA/AC is not on duty, they will get a message that says that tasks are unavailable to them unless they are on duty
* Added `CheckIn` button component into the `MyHall` component. With this, line 165 in `MyHall`, the `CheckIn` will only show if the user is an RA. I have it commented out to check that the `CheckIn` component works, but for the final push, it should be uncommented
* It would be great if someone could test how the tasks would look when things are added to it, I was not able to get to that. My thinking is that we will do the same thing we did with tasklist and create a scrollbar, so it does not go above a specified height

Wmr ra UI fixes

---

src/routes.jsx
src/services/residentLife/RD_OnCall.ts
src/views/ResLife/components/RAView/components/RD-OnCall/index.jsx
src/views/ResLife/components/RAView/index.jsx
src/views/ResLife/components/RDView/components/EditDocs/index.jsx
src/views/ResLife/components/RDView/components/RDOnCallForm/index.jsx
src/views/ResLife/components/RDView/components/TaskList/index.jsx

Added the component for scheduling RDs to be on duty and for RAs to have access to the on call info
RD On-Duty Scheduler: 
Accessible through Edit Docs:
Available on the RA page:
Matched existing style where able and followed logic from the task component for RDs and the Ra on duty for residents. The RD on call phone is passed from RD to RD so it will be one number. We can edit this once we get it.

Rd checkin

---

src/views/ResLife/components/RAView/index.jsx
src/views/ResLife/components/RDView/components/OnDutyMobileView/index.jsx

- Fixed spacing and look of On Duty Mobile component

wmr-update on duty mobile component

---

src/services/residentLife/RA_Statuses.ts
src/views/ResLife/components/ResidentView/components/MyHall/index.jsx
src/views/ResLife/components/ResidentView/components/MyRA/index.jsx

- Residents can now view their RA/AC's availability and current status

WMR RA statuses on Resident View

---

src/views/ResLife/components/RAView/components/RD-OnCall/index.jsx
src/views/ResLife/components/RDView/components/OnDutyMobileView/index.jsx
src/views/ResLife/components/ResidentView/components/MyHall/index.jsx
src/views/ResLife/components/ResidentView/components/MyRA/index.jsx
src/views/ResLife/components/ResidentView/components/OnDuty/index.jsx

This will resolve an issue when using the 360 'app' clicking on a link takes you over to your default browser

Changed links on mobile to open in the same tab

---

src/services/lostAndFound.ts
src/views/LostAndFound/index.tsx
src/views/LostAndFound/views/FoundItemCleanOut/FoundItemCleanOut.module.scss
src/views/LostAndFound/views/FoundItemCleanOut/components/ConfirmCleanOut/ConfirmCleanOut.module.scss
src/views/LostAndFound/views/FoundItemCleanOut/components/ConfirmCleanOut/index.tsx
src/views/LostAndFound/views/FoundItemCleanOut/index.tsx

This is a messy, non-functional version of the clean-out page. It will need many styling changes and added logic, but this was my general idea. I would appreciate any feedback!
Known issues:
- Does not work on mobile

Found Item Clean Out Page

---

src/views/LostAndFound/views/FoundItemCleanOut/index.tsx

One line change to change found item clean out expiration date for testing

Test Date Changed for Demo

---

src/routes.jsx
src/services/residentLife/Status.ts
src/views/ResLife/components/RAView/components/ContactMethod/index.jsx
src/views/ResLife/components/RAView/components/StatusCard/index.jsx
src/views/ResLife/components/RAView/components/StatusManager/index.jsx
src/views/ResLife/components/RAView/components/TaskList/index.jsx
src/views/ResLife/components/RAView/index.jsx
src/views/ResLife/components/RDView/components/TaskList/index.jsx

- Added `StatusManager`
- Component is not yet done, but pushing up for others to access

Pushing up progress

---

src/views/LostAndFound/views/FoundItemConfirm/index.tsx
src/views/LostAndFound/views/FoundItemEdit/index.tsx

[When you go into the edit page for the found item entered i want to navigate back to the found item entry confirmation page. And commented out the last change for going to the admin page after a confirmation match.

Quick fix match richie

---

src/routes.jsx
src/services/residentLife/HousingAccess.ts
src/services/residentLife/RA_Checkin.ts
src/services/residentLife/RA_OnCall.ts
src/services/residentLife/RA_Statuses.ts
src/services/residentLife/RD_OnCall.ts
src/services/residentLife/RD_TaskList.ts
src/services/residentLife/ResidentStaff.ts
src/services/residentLife/Status.ts
src/services/residentLife/Tasks.ts
src/services/residentLife/roomRanges.ts
src/views/ResLife/components/RAView/components/CheckIn/index.jsx
src/views/ResLife/components/RAView/components/ContactMethod/index.jsx
src/views/ResLife/components/RAView/components/StatusCard/index.jsx
src/views/ResLife/components/RAView/components/StatusManager/index.jsx
src/views/ResLife/components/RAView/components/TaskList/index.jsx
src/views/ResLife/components/RAView/index.jsx
src/views/ResLife/components/RDView/components/EditDocs/index.jsx
src/views/ResLife/components/RDView/components/OnDutyMobileView/index.jsx
src/views/ResLife/components/RDView/components/OnDutyTable/index.jsx
src/views/ResLife/components/RDView/components/RDOnCallForm/index.jsx
src/views/ResLife/components/RDView/components/RoomRanges/index.jsx
src/views/ResLife/components/RDView/components/TaskList/index.jsx
src/views/ResLife/components/RDView/index.jsx
src/views/ResLife/components/ResidentView/components/HousingWelcome/Banner.jsx
src/views/ResLife/components/ResidentView/components/MyHall/index.jsx
src/views/ResLife/components/ResidentView/components/MyRA/index.jsx
src/views/ResLife/components/ResidentView/components/OnDuty/index.jsx
src/views/ResLife/components/ResidentView/index.jsx
src/views/ResLife/index.jsx

Variable name updates to align with backend and help make things clearer and easier to maintain
adjusted status scheduler to use profile for gathering RA_ID
added back button on status creator. This option needs to appear on all sub pages of reslife. Styling needs some love
adjusted routes for sub pages/components. i.e instead of /roomranges component route will now be /reslife/roomranges. This helped to clean up auth logic to one file, the reslife index

Code cleanup

---

src/services/residentLife/Status.ts
src/views/ResLife/components/RAView/components/StatusManager/index.jsx
src/views/ResLife/components/RDView/components/RoomRanges/index.jsx
src/views/ResLife/components/RDView/components/TaskList/index.jsx

updated scheduling with weekday selector
Reviewers: this was done with help from ChatGPT.  Please double check when reviewing for any errors i missed
**update: added alerts for success and failures when working with a status(Added to status/task/roomrange forms)

Added weekday scheduling to statuses to match backend change

---

src/views/LostAndFound/index.tsx
src/views/LostAndFound/views/Admin/index.tsx
src/views/LostAndFound/views/FoundItemEdit/index.tsx
src/views/LostAndFound/views/Kiosk/index.tsx

Also includes formatting changes from prettier (since whoever did FoundItemEdit didn't have prettier installed I assume).

Found Item List Status Defaults to Active

---

src/views/LostAndFound/views/Admin/LostAndFoundAdmin.module.scss
src/views/LostAndFound/views/Admin/index.tsx

Full Details Button in Comparison View

---

src/views/ResLife/components/RAView/components/StatusManager/index.jsx

- Fixed the status list so that it shows the status based on the selected day

wmr - Completed RA Active Status Display

---

src/views/ResLife/components/RDView/components/RDOnCallForm/index.jsx

fixed issue where rd on call would not load in SP. issue came from api error return. wrapped error message on backend and called this on front end

wrapped api returns

---

.env.development
src/views/ResLife/components/RAView/components/StatusManager/index.jsx
src/views/ResLife/components/RDView/components/RDOnCallForm/index.jsx
src/views/ResLife/components/RDView/components/RoomRanges/index.jsx
src/views/ResLife/components/RDView/components/TaskList/index.jsx
src/views/ResLife/components/RDView/index.jsx

resolved a data issue when editing an event
added logic to determine which days have active events so the user knows which days to look at:
added a confirm delete option that lets the user know all events in the series are deleted:
added back option to remaining pages:

updates status UI

---

src/views/ResLife/components/RAView/components/CheckIn/index.jsx
src/views/ResLife/components/RAView/components/TaskList/index.jsx
src/views/ResLife/components/ResidentView/components/MyRA/index.jsx

WMR - Adding comments

---

src/views/ResLife/components/RAView/components/ContactMethod/index.jsx
src/views/ResLife/components/RAView/components/MyAssignments/index.jsx
src/views/ResLife/components/RAView/components/StatusCard/index.jsx
src/views/ResLife/components/RAView/index.jsx
src/views/ResLife/components/ResidentView/components/MyHall/index.jsx

**Changes made in PR**
- Changed RA View format because a user said it was too cluttered

wmr - Made RA View look better

---

src/views/LostAndFound/views/FoundItemCleanOut/components/ConfirmCleanOut/index.tsx
src/views/LostAndFound/views/FoundItemCleanOut/index.tsx

The pages now work on mobile (as in they are functional and none of the info is cut off), but they are difficult to understand and poorly laid out (aka ugly). We could merge this if we wanted since it's better than before, but I'm going to work on it more.

Mobile View on Clean Out Page

---

src/views/LostAndFound/views/Admin/LostAndFoundAdmin.module.scss
src/views/LostAndFound/views/Admin/index.tsx

Meant to make admin home page work on mobile

(DRAFT) Admin Mobile Page Fixes

---

src/services/residentLife/RD_OnCall.ts
src/views/ResLife/components/RAView/components/RD-OnCall/index.jsx
src/views/ResLife/components/RDView/components/EditDocs/index.jsx
src/views/ResLife/components/RDView/components/EditPhones/index.jsx
src/views/ResLife/components/StaffView/index.jsx

Added functionality for storing phone numbers in the backend. 
When loading or there is an error text is displayed
When pulled succesfully
There is an edit option for the RDs. I am fighting with styling it functions just fine
Very simple interface

Added Phone number management

---

src/views/LostAndFound/components/CustomDatePicker/index.tsx
src/views/LostAndFound/views/FoundItemCreate/FoundItemFormCreate.module.scss
src/views/LostAndFound/views/FoundItemCreate/index.tsx
src/views/LostAndFound/views/FoundItemEdit/index.tsx
src/views/LostAndFound/views/FoundItemList/index.tsx

Various Minor Improvements

---

.env.development
.env.production
.github/workflows/ci.yml

Wheres my ra

---

src/services/lostAndFound.ts
src/views/Home/components/LostAndFoundCard/components/FoundReports/index.tsx
src/views/LostAndFound/components/ItemForm/FoundItemForm/FoundItemForm.module.scss
src/views/LostAndFound/components/ItemForm/FoundItemForm/index.tsx
src/views/LostAndFound/index.tsx
src/views/LostAndFound/views/Home/index.tsx

This should allow General Users to be able to see items that are marked as belonging to them

Found item by user richie

---

src/views/LostAndFound/components/Header/index.tsx
src/views/LostAndFound/views/Admin/LostAndFoundAdmin.module.scss
src/views/LostAndFound/views/Admin/index.tsx
src/views/LostAndFound/views/FoundItemEdit/index.tsx

- Fixed Double Load Bug for Found List
- Missing Items List Reloads After Marking with No Match Found
- Styling Updates
- Added Mark as Match Confirmation Pop Up:
- Added Mark as Checked Confirmation Pop Up:
- Added clarifying text to full details button

Admin Page Improvements

---

src/services/lostAndFound.ts
src/views/LostAndFound/views/Admin/index.tsx

Admin Page Recently Checked Checkbox

---

src/views/LostAndFound/views/FoundItemConfirm/index.tsx

Changed link to use the new Link Reports Service link

---

src/services/lostAndFound.ts
src/views/LostAndFound/views/FoundItemEdit/index.tsx
src/views/LostAndFound/views/MissingReportDetails/index.tsx

Have Project Board Issue 195, 185, 186 and 194 in here.

Undo link view link richie

---

src/views/LostAndFound/components/CustomDatePicker/index.tsx
src/views/LostAndFound/views/FoundItemCreate/index.tsx
src/views/LostAndFound/views/FoundItemEdit/index.tsx
src/views/LostAndFound/views/ReportItemForOthers/index.tsx

This Pull Request looks to solve two specific bugs in the Lost and Found System. Firstly, it solves the error where an admin user is not able to submit a report on behalf of someone else if the date selected is in the past and not the current date.
Secondly, it solves the error where submitting a report on behalf of someone else creates two reports for that person.

Date lost fix

---

package-lock.json
package.json

Recommended by npm, see:
http://github.com/browserslist/update-db#readme
Generated by running:
npx update-browserslist-db@latest

Update caniuse-lite browser info

---

src/views/Home/components/DiningBalance/index.jsx

Quick fix to #2658. Just wanted to document it!

aligned "Todays Menu" text to be centered on the button

---

src/views/Home/components/DaysLeft/index.jsx

I simplified the loading process to use less intermediate state (and therefore less re-renders), and tried to streamline the date logic by using Date primitives and our standard `date-fns` library, with the goal of making the logic easier to understand for future maintainers.

Streamline loading and calculation of days left

---

src/components/Profile/components/Identification/index.tsx
src/components/Profile/components/PersonalInfoList/index.tsx

created a button in the user profile page that allows directs a user to the registrar to request a name change

Add name change request button

---

src/components/Profile/components/PersonalInfoList/index.tsx
src/services/user.ts
src/views/CoCurricularTranscript/guestTranscript.tsx

Requires https://github.com/gordon-cs/gordon-360-api/pull/1214 to work
Displays year joined for students and year hired for staff/faculty members

S25 join date

---

src/views/InvolvementsAll/components/InvolvementsGrid/index.jsx

Quick fix to #2653, I had it working already I just wanted to document the problem to keep things organized

involvement cards fit for any size window

---

public/sw.js
public/sw_guest_cache.js
public/sw_user_cache.js
src/components/GordonOffline/index.tsx
src/components/Header/index.tsx
src/components/NavButton/index.tsx
src/components/PWAInstructions/index.tsx
src/components/PaletteSwitcherDialog/index.tsx
src/components/Profile/components/Identification/index.tsx
src/components/Profile/components/MembershipsList/index.tsx
src/components/Profile/components/OfficeInfoList/UpdateMailDestinationDialog/index.tsx
src/components/Profile/components/OfficeInfoList/index.tsx
src/hooks/createUseContext.ts
src/hooks/useDocumentTitle.ts
src/hooks/useNetworkStatus.ts
src/services/analytics.ts
src/services/error.ts
src/services/event.ts
src/services/housing.ts
src/services/http.ts
src/services/involvements.ts
src/services/lostAndFound.ts
src/services/news.ts
src/services/session.ts
src/services/storage.ts
src/services/transcript.ts
src/services/utils.ts
src/views/CoCurricularTranscript/Components/Activity/index.tsx
src/views/PeopleSearch/components/SearchFieldList/index.tsx

It seems like warnings are generated through the use of eslint which checkes format based of prettier. When doing commit it automatically runs a format check through eslint(shown in the terminal).
start-------ai---------start
npx eslint . {This lints all files in the current directory (.) and subfolders. It will:Show warnings (like unused variables, formatting issues) Show errors (like syntax problems)
npx eslint . --fix {this automatically fixes the simple warning including preferred lower_caes and spacing or line issue}
----------end---------------

fixing warnings for spacing and favor of lower_case

---

src/components/Profile/components/PersonalInfoList/index.tsx

Fixed displayed message in the snackbar so that May is not displayed twice.

fixed displayed snackbar

---

src/services/marketplace.ts

There was a problem where the GET functions were not working because of a double slash... Should be fixed by now

Fixed a problem with the api and ui connection

---

src/views/MarketPlace/MarketPlace.module.scss
src/views/MarketPlace/components/MarketPlacePopup/index.jsx

In switching to a new library, the image gallery in marketplacepopup had not as intuitive or asthetically pleasing UI. This pull request attempts to fix that!

S25 fixed weird UI for marketplace popup

---

src/views/Home/components/PosterSwiper/PosterSwiper.scss
src/views/Home/components/PosterSwiper/index.jsx

Added CSS to change the pagination for the PosterSwiper to make it contrast better in dark mode. Also fixed the shadows under the Posters to not get cut off by the edge of the PosterSwiper Card

Changed the pagination for PosterSwiper

---

src/components/Profile/components/SchedulePanel/components/ScheduleDialog/index.tsx
src/services/schedule.ts

quad class were only showing the term dates which didn't really match the dates of the class

added class date in adition to term date
