gordon-cs/gordon-360-ui

- src/app.js
This will remove the invalid token from storage when an authentication error is detected, bringing the user directly to the login page on any further page loads.
> Sign user out on auth error

- src/components/Header/components/GlobalMenu/index.js
- src/views/Home/components/DaysLeft/index.js
Menu Items for 'Help' and 'About' only navigated to those pages if the text was directly clicked, not the actual button. I changed it so that the whole button is a link instead of just the text.
> Update Help and About Buttons

- src/views/Events/index.js
I changed the positioning of the search bar on the events page. Now, there is a small margin from the left edge of the events list so that the search bar position seems a bit more natural. It also no longer sticks to the left side of the page when being viewed on a mobile device.
Before - Desktop:
After - Desktop:
Before - Mobile:
After - Mobile:
> Center search bar over events list

- src/components/Header/components/PeopleSearch/people-search.scss
Looks better than it did, but the old way of setting the underline color on hover no longer works. The code is still in the SCSS file, but it has no effect.
From the little bit of Google searching I did, it looks like setting that attribute no longer works through CSS but can only be done using a Material-UI Theme override. I'm not sure about this though.
> Remove white box from search bar

- src/views/Home/components/CLWCreditsDaysLeft/index.js
...as suggested by Dr. Tuck.
**Note**: If run using the release server (360Api), the title is "Summer 2018" as expected, but if run using the development/train server (360ApiTrain), the title is "Spring 17-18 Academic Year". This is identical to the behavior of the charts on [360.gordon.edu](https://360.gordon.edu) vs. [360train.gordon.edu](https://360train.gordon.edu) and is not an issue with the front-end code.
> Replace CL&W credit chart title with description of current term

- src/views/MyProfile/index.js
- src/views/MyProfile/profileButton.scss
I created a new branch based on develop to get around merge conflicts.
The update photo button is now built into the profile image itself. Hovering over the image reveals an "update photo" label (thanks Stephen for the css help!!) On mobile (xs) this label is always visible, as there's no hover option without a mouse. 
With mouse hover:
No hover:
Mobile:
> Update Photo Button

- iisConfig/copyIISConfig.js
- iisConfig/web.config
- package.json
- Requires installation of URL Rewrite module in IIS Manager
The module has already been installed, so it should be good to go from here on out. There's really no easy way to add screenshots or test this locally, unless you open IIS manager, start the website, test the solution, and trust that it is actually running a production build like we said it was... (͡ ͡° ͜ つ ͡͡°)
> Set up internal redirect to eliminate useless 404 (7)

- package.json
Changes that worked just fine locally broke the staging server.
As of the time this pull request was opened, the site was working fine, but should it ever break on rebuild (if you try to load 360newtrain and it shows a blank white screen), merge this pull request and it _should_ be remedied.
It's not a hack, it's a workaround
> Mask breaking changes (reverse attempt at 404 fix)

- src/views/Login/index.js
Not sure if this is normal with all chrome autofill but when the page loads the information is automatically entered rather than having to specify which username and password pair you would like to use for the form
> added autocomplete tag and username id to login

- src/views/About/index.js
- src/views/Events/index.js
- src/views/Help/index.js
Based on feedback from our user testing.
Users went to the help page first to find the report bug feature, and for some reason it was only on the about page. I made the link an uncontained button instead of just a linked text, to be consistent with the rest of the website.
> Added report bug to help page

- src/views/Profile/index.js
Over the weekend I performed an "in-depth investigation" of the funny behavior I've been noticing with the profile images on the public profile page. The changes I've made to the code are minimal, but determining the right changes to make required a bit of testing. Here is my way-too-detailed (but hopefully clear and helpful) analysis of the problem and its solution.
**"Hiccups" with current logic**:
1. If no preferred photo has been set and a user uploads a new preferred photo, no image is displayed on the public profile page for the next ~4 minutes.
2. If a user hides his profile image, the Fighting Scot mascot is only shown for the next ~4 minutes; no image is displayed at all thereafter.
**Resolution**:
After some experimentation, I've determined the following facts about the behavior …
> Fix hiccup in public profile image display logic

- src/views/Login/index.js
- The message *only* appears if login is actually hanging, not if username or password is incorrect, etc.
- The code sets a timeout before the call to the authentication function, and cancels the timeout if it gets past the function call
- Refresh button on snackbar will refresh the page
- Added boolean to disable message if desired (e.g. for testing)
- Added comments to all message-related lines of code to facilitate removal once the login page issue is solved
>  Add message which appears if login hangs for longer than 6 seconds (2)

- src/components/EventList/index.js
Matt noticed an error on the mobile view of the Events page
Both date and time had the time showing before.
> fixed duplicate time on mobile

- .env.development
Add .env.development, which I hope will be used in place of .env.production
in development mode.
> Make 360newtrain use "train" backend

- public/index.html
This should allow our deployed dev branch to also use the Gordon font. There is a different font key for master and develop, so we should configure the server to automatically copy the correct key instead of having a different file in GitHub for dev and master.
> New font key for development

- src/services/user.js
- src/views/ActivitiesAll/components/ActivityGrid/index.js
- src/views/ActivitiesAll/index.js
The "my current involvements" section at the top of the involvements page now displays the involvements for the specified session. The heading says my current involvements when the session is set to the current session.
> My current involvements section displays involvements for specified session

- src/views/MyProfile/Components/LinksDialog/index.js
The button is no longer missing the actual _submit_ functionality.
> HandleSubmit for social media linx dialog

- src/views/PeopleSearch/index.js
The search parameters were off between dept/building, causing an error.
> Fix mixed up building/dept search parameters

- src/views/ActivityProfile/index.js
Fixes the issue where:
"When I click on a past involvement that I wasn't in, then I get the "loading circle" forever (or at least for longer than my patience)."
The issue was that any time anyone wanted to access a specific Involvement, the front end was trying to get a list of all the members' emails (when it should only give it to the admins).
> Involvements Bug

- src/views/Home/components/CLWCreditsDaysLeft/index.js
Replace redundant "CL&W Credits" subtitle at top of card with "CL&W Credits Left" (to match "Days Left").
> Tweak CL&W Chart

- src/views/ActivityProfile/components/Membership/index.js
- src/views/ActivityProfile/index.js
Superadmins can now view, change, and confirm the rosters for any involvement. They are also able to edit any involvement, which includes changing the photo.
This partially fixes #336.
> Involvement page superadmin functionality

- src/views/Home/components/DiningBalance/index.js
Students who are also SuperAdmins can now view their entire meal plan balance, not just the number of dining dollars.
- This change requires a similar change to be made in the back end. The [studentAdminDining](https://github.com/gordon-cs/gordon-360-api/tree/studentAdminDining) branch on `gordon-360-api` has the required changes. Be sure to run that branch when testing this pull request. Also don't forget to merge that branch into develop and redeploy the API before merging and deploying this one.
> Display meal plan info for SuperAdmins in addition to students.

- src/services/user.js
Attempting to isolate bug that results in a blank ID photo submission, with a very small file size.
> Print blob size before sending ID photo to backend

- src/services/user.js
This branch changes the dining balance API call from "api/dining/{role}/{id}/{session}" to just "api/dining".  This API change means (1) it is not necessary to know the role (student,facstaff,etc) of the user, (2) users cannot get meal plan info or dining balance information for other users, and (3) information is always only accessed for the current session (as data for other sessions is unavailable anyway).
This branch should be merged with develop at the same time the branch FinalEmployment is merged into gordon-360-api as that branch contains the corresponding API change.
> Remove Role, ID number, and Session from dining URL

- src/views/IDUploader/IDUploader.scss
- src/views/IDUploader/index.js
This recursively calls post ID image up to 5 times in the case of an error. It drastically reduces the chances of a blank ID image being posted, and implements a suitable error message for the user in the event that a blank photo is posted.
> IDUploader Fix to Master

- src/components/Header/components/NavAvatarRightCorner/index.js
- src/components/Nav/components/NavAvatar/index.js
- src/routes.js
Currently the NavAvatar and NavAvatarRightCorner both append the current user's username when constructing the URL for the users "myprofile" page.  This is unnecessary and is a hold-over from from when there was a single profile page route to users.  In fact, anything following "myprofile/" in the URL is currently ignored.
This pull request includes changes that rectify this behavior.
> Myprofile without username

- .env.development
- .env.production
- src/services/errorLog.js
- src/services/membership.js
- src/views/IDUploader/index.js
Added generic error logging service to UI. Includes method to get user's browser and OS. Currently only used by ID Uploader, to record successes and failures, as well as the browser / os.
It uses a new logging route in the API, to record logs to the database.
Hopefully, this logging service will be helpful for collecting errors from actual website usage. 
Currently the size of the error message seems to be limited -- might need to look into sending multipart file content, or something that can handle larger messages. We were unable to send an entire 6 mb blob, but for typical strings it is currently fine.
> Error Logging for ID Uploader

- src/components/Header/index.js
- src/services/user.js
- src/views/CoCurricularTranscript/Components/CoCurricularTranscriptActivity/coCurricularTranscriptActivity.scss
- src/views/CoCurricularTranscript/Components/CoCurricularTranscriptActivity/index.js
- src/views/CoCurricularTranscript/Components/CoCurricularTranscriptExperience/index.js
- src/views/CoCurricularTranscript/index.js
After talking to Chris Carlson, it was decided that the Co-Curricular Transcript should display memberships in order from most recently ended to least recently ended, and that each membership should only display in one category, showing the full duration of the user's membership, and-if needed-the duration of the user's leadership.
This pull request fixes #500 and #499
> Cct leadership redesign

- src/components/Header/index.js
- src/project-name.js
- src/views/About/index.js
- src/views/Login/index.js
To celebrate Pi Day, on March 14th each year Gordon 360 should become Gordon 2\u03C0.
There are only a few places that "Gordon 360": window titles (appears in title bar and browser tabs), and the About and Feedback pages.  It seems reasonable to leave the feedback page alone, but the change implemented in this pull-request changes the window titles and one line on the About page.
Ideally a different carousel image would be loaded on this day, assuming that "Gordon 360" remains on the main banner image.  If we do move to a true banner rather than a carousel, this might most easily be done using a background image and regular text in the foreground.
> Replace 'Gordon 360' with 'Gordon 2\u03C0' (Gordon 2pi) in strategic places on March 14 ("Pi Day")

- scripts/deploy.sh
This pull request updates the deployment script to more efficiently handle automatic backups. Previously, the script copied a backup of the old web code folder, then deleted the original. After that process, the new build was moved in.
Instead of doing that combination of copy and delete, we can consolidate both actions into a simple rename of the folder--marking it as a backup. Then, we can move in the newly built files.
TODO: automatic deletion procedure, as this will no longer automatically delete older versions. (Perhaps use Unix epoch time to designate different backups, for ease of calculating when to remove old backups)
> Update deployment shell script

- src/views/PeopleSearch/index.js
This change builds the search parameter string cleanly, avoiding including spaces caused by indentation in the source code.
> Avoid extra spaces in search parameter URL

- src/views/About/index.js
Changed the team from this summer to be listed alphabetical, and added last year's and this year's dev teams.
I am wondering if the 'found a bug, report to cts' button should be directed to our team directly rather than to CTS. Does CTS ever forward reports on to us? (Do we get any?)
> Updates to about page

- src/views/ActivityProfile/components/Membership/components/MemberList/index.js
On the involvements page, if a user had no mailbox it would still show "Box #". This change removes that issue, now "Box #" is only shown if the user actually has a mailbox.
> Fix empty mailbox

- src/components/EventList/components/EventItem/index.js
Solves #680 
On the events page, some events have a "No description available" description, while some just have an empty field. Now both cases just display "No description available".
> Add 'no description' text for events without a null description

- src/views/EventsAttended/index.js
Tiny change to center button on attended events page when you have not attended any events.
The old view:
The new view:
For reference, this is what it looks like when you have attended events:
> Center button.

- src/views/Timesheets/index.js
The date out picker no longer autopopulates on the first click, and it now causes the getJobs to run every time the dialog is closed
> Make date out picker initially focus on same day as date in picker

- src/components/Header/index.js
- src/components/Nav/components/NavLinks/index.js
- src/components/QuickLinksDialog/components/LinksList/index.js
- src/components/QuickLinksDialog/index.js
- src/routes.js
- src/views/Timesheets/components/SavedShiftsList/index.js
- src/views/Timesheets/components/ShiftDisplay/index.js
- src/views/Timesheets/components/ShiftItem/index.js
- src/views/Timesheets/index.js
Fixes URL for timesheets so it's no longer a "random" string
Adds link to Student Timesheets page to the quick links dialog
Co-authored-by: adamprinciotta <adamprinciotta@gmail.com>
Co-authored-by: Jacob <jacob.bradley@gordon.edu>
> Add real URL for student timesheets page

- src/components/SchedulePanel/index.js
- src/views/MyProfile/index.js
- src/views/PeopleSearch/components/MobilePeopleSearchResult/index.js
- src/views/PeopleSearch/components/PeopleSearchResult/index.js
- src/views/Profile/index.js
- src/views/Profile/profile.scss
Minor bug fixes:
- Fixed bug with overlapping long emails covering the email icon (resolves #640),
- Fixed issue with layout sizing on people search. The person "type" was given a larger buffer than the correct size given by the headers. This resolved the email address / mailbox section from overflowing side of card.
- Centered people search results on mobile. Potential new issue to note: fixed widths to 250px (to maintain image alignment).
- Corrected the width and location of the "schedule" card on profiles
- Resolved url issue on "schedule" card where links would be https://http// etc. The issue was a logic && mistake. (resolves #639)
> (S20) Resolving Good First Issues

- src/components/Header/components/PeopleSearch/index.js
- src/components/Header/components/PeopleSearch/people-search.scss
src/components/Header/components/PeopleSearch/index.js: Added 'No results' dropdown when there are no people search suggestions & fixed bug where backspacing the search and entering when no suggestions dropdown is shown redirects the user to the first previously available top suggestion.
src/components/Header/components/PeopleSearch/people-search.scss: Added class for 'No results' for gray text and italics.
Edit: Added renderNoResult() function to avoid DRY code. Changed MIN_QUERY_LENGTH from 3 to 2 to include people searches for individuals with 2 letter first or last names.
> S20 People Search 'No results'

- src/views/ActivityProfile/activity-profile.scss
- src/views/ActivityProfile/index.js
Improved UX of the Involvement Profiles (Activity Profile)
- Cleaned up some of messy grid layout (overused nesting of containers)
- Increased font size of main heading
- Moved session/term details to be subtitle on top
- Centered description and website (bolded) and removed "Description: " type leading text
- Added horizontal divider between this above and the extra details
- Left aligned details and fixed paddings/margins
Resolves #724
> (S20) UX Improvements to Involvement Profiles

- src/views/News/components/NewsItem/newsItem.scss
Patch to PR #825 
Sass does not interpret percentage opacity correctly, so changed to decimals
"Keep in mind, though, that if you are using Sass, it will not handle the percentage value, and will compile it to 1%."
> (S20) PATCH 'News Page - "Submit News" and "View Personal Unapproved"' (sass opacity fix)

- src/services/news.js
- src/views/News/components/NewsItem/index.js
- src/views/News/components/NewsItem/newsItem.scss
- src/views/News/components/NewsList/index.js
- src/views/News/index.js
News is still an unfinished feature. This pull request adds the ability to delete news displayed on the News Page UI from the database.
Currently Working:
- Delete news: a button that shows *only* for news items that the currently authenticated user has authored
- Snackbar displays success/failure message
Closes #805
Needs Work:
- Improve snackbar feedback (icon change? like with membership requests)
- Maybe see if there is any way to make snackbars not be terrible (have to pass through every child to send to each component, probably no workarounds).
- Delete button does not contrast well with approved news items (navy on cyan, perhaps change all news items to gray like unapproved news items)
- (Most things from News 2.0)
- More consistent item heights
- Perhaps allow re-rendering of data …
> (S20) News Page - "Delete News" UI

- src/views/News/components/NewsItem/index.js
fixed bug reloading home page infinitely news
null username while not yet authenticated on home page
temporary patch probably, will need to be looked more carefully at in future
> (S20) PATCH 'News Page - "Delete News" UI' (bug reloading home page)

- src/services/news.js
- src/views/Home/components/NewsCard/index.js
- src/views/News/components/NewsItem/index.js
- src/views/News/components/NewsItem/newsItem.scss
- src/views/News/components/NewsList/index.js
- src/views/News/index.js
News is still an unfinished feature. This pull request adds the ability to edit news displayed on the News Page UI from the database.
Currently Working:
- Edit news: a button that shows *only* for news items that the currently authenticated user has authored AND that are unapproved
- Snackbar displays success/failure message
Closes #830 
Needs Work:
- Everything from PR #829 
- Currently the whole page refreshes to update after submission/deletion/edition, but we should allow React to only re-render the updated parts
> (S20) News Page - "Edit News" UI

- .env.production
- public/sw_global_variables.js
Changes the production environment variable to point towards 360APITrain instead of 360API
> S20 pwa installer: Change back env variable to Train

- src/views/News/index.js
Adds a simple logical condition so that unapproved news shows if it exists rather than just "No news to show"
> (F20) Student News Bug Fix - shows unapproved news even if no other news

- src/views/Timesheets/index.js
This commit fixes a timesheets bug (#894) where users set to a different locale (e.g. had browser language set to german) would not be able to retrieve their jobs. This was because when fetching jobs, the front end would send shift_start_datetime and shift_end_datetime as locale strings, and many international locales flip day and month in date strings (i.e. dd/MM/yy instead of MM/dd/yy). This would give the wrong date to the backend. Since ISO date strings are standardized and unaffected by locale, the backend should now always receive the correct date.
> Send date to backend as ISO string, not locale

- src/services/user.js
Because the `sortByTime` function was never exported from event.js, its use in user.js to sort attended chapel events never had any effect. Attended chapel events were not sorted. 
To make matters more complicated, a recent change in where chapel event data originates has left most chapel events without `Occurrences` values, which is what `sortByTime` uses to sort events.  
The goal of this fix was to make sure attended events are sorted for uses.
A new sorter function was created in user.js, `sortAtndEventsByTime`, that sorts based off of `Occurrences` only if it is non-null and by `CHDate` otherwise. `CHDate` works well as a default for sorting attended chapel events because it is the time when a student is awarded credit for the event and thus should never be null. (At least, based on …
> Fix attnd events sort

- src/app.js
- src/components/Header/index.js
This is a suggested fix for two errors that appear during compilation: One is the missing onSignOut for the NavAvatar, the other is an upcoming deprecation warning regarding the syntax used for `createBrowserHistory` in `app.js`
> Suggested Bug fix for compilation error

- src/components/Header/index.js
- src/services/wellness.js
- src/views/Home/index.js
Refactor wellness service to use simple routes ('/wellness' instead of '/wellness/status'). These routes access the refactored and simpler API.
> Use simple wellness routes

- src/views/WellnessCheck/components/HealthStatus/index.js
Students are required to fill out the Return to Campus form before they can complete a COVID check in on 360. All on-campus students will have their status set to red before returning to campus, and this will stay until they fill out the form. 
This code can be removed once the return to campus process has been completed.
> Add Return to Campus form link

- src/views/Profile/index.js
The profile page is perpetually displaying the message "Please login to view this profile", even when logged in. This was because of a small error merging master into develop for a release. The Authentication prop had been refactored into lowercase authentication by a change in develop. However, this change got overwritten by a change from master to this one reference to that prop. This meant that the check for authentication was always failing on the profile page because the component has no Authentication prop.
> Fix profile login message error

- src/views/Timesheets/components/ShiftItem/index.js
- src/views/Timesheets/index.js
Recording time more precisely will help make it affordable to hire Class Assistants to do cleaning between classes (lots of people, working frequent short shifts between their classes).
> Change shift rounding from 15 minutes to 5 minutes (quarter to 12th of an hour)

- src/views/Timesheets/index.js
The math for rounding up student shifts was using strict equals but the hour difference variable was a string being compared to an integer, so it was always returning false. This way, we properly detect shifts that are less than 5 minutes and round them up to 5 minutes, which is the minimum length acceptable.
> Fix shift rounding error when shift was > 5 minutes

- .expo/packager-info.json
- .expo/settings.json
The .expo folder and it's contents were added in a strange [Git manipulation commit](https://github.com/gordon-cs/gordon-360-ui/commits/develop/.expo), and aren't actually referenced or used anywhere else in the project. We don't have or use Expo in this project at all. Removing these helps get rid of unnecessary bloat and tidy up our top-level files so that the meaningful things can be found and used more easily.
> Remove expo files

- README.md
In case our CI/CD integration fails at some point, or if it needs to be adjusted/updated, this commit adds documentation for the process of deploying manually.
> Add documentation to the README for manual deploy

- src/services/user.js
The required CL&W Credits default was broken because it depended on AttendedChapelEvents, so we couldn't fetch the actual value until the student had attended some event in the current session. The API was fixed to add ChapelRequired and ChapelAttended to the StudentProfileInfo. This commit uses those values for the CLWCreditsDaysLeft wheel.
Fixes gordon-cs/gordon-360-api/issues/454
> Fix CL&W credits Required default

- src/views/PeopleSearch/index.js
The include alumni checkbox on people search was showing for people who had a composite persontype (e.g. 'stufac'). No it won't show for anyone whose persontype includes 'stu' for student.
> Include alum checkbox only shows for non-students

- README.md
A new 360 developer changed the nvm environment variable for all CS-RDSH-02 users so that access to it was restricted. The issue was fixed. However, because they were likely following the instructions in the README without realizing that nvm was already installed, I thought a README change would prevent future such mishaps.
> Inform how to check for nvm install

- src/app.js
- src/contexts/NetworkContext.js
- src/hooks/useNetworkStatus.js
This commit introduces the NetworkContext, which uses React's Context API to track the online/offline status of the user's network. The goal is to have network-aware component's subscribe to this context provider so that the network is tracked in only one place, rather than having eventListeners in every component that needs to know the network status.
This may result in minimal performace gains (having only one event listener attached to the window instead of >10 at once), but I would guess that the rerendering takes significantly more processing than the eventlisteners themselves. The real advantage to this technique is the separation of concerns. Now, the NetworkContextProvider is the only component responsible for the logic of tracking network changes. Every ther network-aware …
> Add network status hook

- src/services/jobs.js
- src/views/Timesheets/index.js
Sending dates as ISO strings to the backend caused an unforeseen problem in that dates were being parsed by the backend as UTC and stored in the database as such, but then compared to local time without adjusting for the timezone difference. Instead, we will send the date in a custom format that approximates ISO but is in the user's local time zone. This fixes the above error and preserves the fix from using toLocaleString that caused issues for user's with browsers that had different locales.
Depends on https://github.com/gordon-cs/gordon-360-api/pull/475
> Fix date formatting for timezone bug

- package-lock.json
- src/views/WellnessCheck/components/HealthStatus/index.js
Students are required to fill out another, different Return to Campus form after returning from Easter Break in the Spring of 2021. This updates the link to point to the correct form, and changes the text to clarify the new form.
> Update Return to Campus link & text for Easter

- src/views/Timesheets/index.js
The API has been updated to detect bad shift times when they are saved. This introduces some preliminary error handling on the front end to notify the user more concretely on why their shift failed to save.
> Add error handling for bad shift times

- src/services/housing.js
- src/services/user.js
- src/views/ApartmentApp/components/StaffMenu/index.js
- src/views/ApartmentApp/components/StudentApplication/index.js
There were a couple of insidious bugs related to the function `isApplicantValid`.
1. Assigning an applicant's full name to the `applicant.Profile` property instead of `applicant.Profile.fullName`, accidentally overwriting all other Profile info
2. Calling `user.formatName(...)`, which is a function in `user.js` that wasn't exported (as therefore could not be called). 
3. Making it an async function means that calling it elsewhere is inconvenient, especially when you only want to extract the boolean result for a one-time comparison. I converted it to a synchronous version using `Promise.then()` syntax. This should fix present errors in places it was being used as-if it were synchronous, and also help prevent future bugs of a similar nature.
> Apartapp fix isApplicantValid

- src/views/Help/help.scss
- src/views/Help/index.js
Opened as a new version of #1110 because of merging issues.
The Help page, similar to the About page, has needed a refactor for design and readability when users are looking for easily-accessible assistance.
Current page:
After changes:
Similar to #1099 , "The main elements of the redesign were to put the content on a card and make consistent use of Material UI design."
> Refactor and Update Content on Help Page

- src/views/Help/help.scss
- src/views/Help/index.js
When I merged the pull request (#1111), the sections on the help page gained a box-shadow CSS property. This pull request adds a class to overwrite the box-shadow.
> Remove Box-Shadow from Help Cards

- src/views/About/contributors.json
A few of the students who we just added to the about page as the 2020-21 SD group had incorrect class years. This pull request resolves that.
> Update Class Years of Developers

- src/views/ApartmentApp/components/StaffMenu/index.js
I spotted during the presentation demo that the CSV still includes `EditorProfile` with cells containing `[object]` so I made this quick update to fix that
> ApartApp - Exclude [object] from CSV

- src/views/ActivityProfile/components/Advisors/index.js
- src/views/ActivityProfile/components/GroupContacts/index.js
The Advisors and GroupContacts components were not returning from `render()` when they had no data to display. React requires every component to return, so this was causing an error and getting the stuck in a perpetual loading loop.
I have fixed it so that these components return null when they have no data, and I have also refactored them, removing a great deal of unnecessary code for loading that didn't actually load any data.
> Fix error displaying Activity Profile when Advisors or GroupAdmins is null

- src/views/InvolvementsAll/components/Requests/components/RequestSent/index.js
- src/views/InvolvementsAll/components/Requests/index.js
- src/views/InvolvementsAll/index.js
- Changed "session" to "term" because this makes more sense to a college student, for whom this is primarily targeting
- Changed "type of involvement" to "type" for the same reasons we do not say "search involvements" or "term/session of involvement" (to reduce redundancy, improve consistency, and also to prevent the label from overflowing the input dropdown field)
- Change "no involvements for `term name here (e.g. Spring 20-21 Academic Year) `" to simply "no involvements for this term" because the header already specifies the appropriate term and so this is redundant.
- Changed "All Involvements" header to specify the term, like we had done with the personal involvements
_Note: this is not the most elegant code and should probably be improved in future, but I think the direction is …
> Involvements UI Improvements and Bug Fixes

- src/components/Profile/components/MembershipsList/components/MembershipInfoCard/index.js
- src/views/ActivityProfile/index.js
- src/views/Page404/index.js
- src/views/PeopleSearch/index.js
Re-centered a few elements affected by change in global styling.
Centered people search, 404 mascot, activity profile title, and lock icon for private profile memberships.
> Re-centered Elements

- src/views/PeopleSearch/components/PeopleSearchResult/index.js
- src/views/PeopleSearch/index.js
Adjusted the people search results layout sizing so that way every column has an equal width; class/job title originally had a wider column because faculty/staff have longer titles but this is arguably not worth the inconsistency. Also changed type to description honestly just because it looked bad with a word as short as 'type' which also doesn't have very much significance anyway (type of what, is this telling me what type of person they are?).
Before:
After:
> Adjusted people search results alignment, changed type to description

- src/views/ApartmentApp/components/StudentApplication/components/HallChoiceList/components/HallChoiceListItem/index.js
- src/views/ApartmentApp/components/StudentApplication/index.js
The database tables for apartment applications were renamed for consistency and clarity, e.g. from `AA_Admins` to `Housing_Admins`. This has affected the backend just slightly, and touches the front end in only one case. It appears that when fetching the list of apartment halls from the database, the API was returning an array of objects with the singular property `Name`, a string representing the name of the that hall. The API now returns  and an array of strings, each string being the name of the hall it represents. This only matters in so far as previously the frontend had to 'unwrap' the `Name` property from the hall objects - even though that was the only data a hall object contained. Now, accessing and iterating over the halls is easier because they are simply the names themselves. …
> Apart app db updates

- src/views/Home/components/DaysLeft/index.js
I managed to disable the legend on the staff view of the days remaining doughnut.
Added an "options" var to the Daysleft index.js with legend set to false, which disables the legend but keeps the hover text.
Resolved #1149
> Disabled Legend on Days Remaining for Staff View

- README.md
The documentation was a little bit confusing and misleading when discussing our `.env` files and how to use them with a local backend. I have corrected, updated, and clarified that wording.
I also removed a couple of "known issues" that no longer apply:
- Edge is now a chromium-based browser and runs 360 just fine.
- The login "hanging" has been fixed
- Filtering on the housing admin view of apartment applications is fully implemented and working.
> Update README: clarify env vars, remove old issues

- src/components/Profile/components/PersonalInfoList/index.js
Realized we have a small bug when people change the mobile phone number privacy option...
When people change their privacy option, the website shows us a wrong notification message.
The private option --> "Mobile Phone Visible" (Wrong!!)
The public option --> "Mobile Phone Hidden" (Wrong!!)
I just fixed the bug... Now, it should be all set.
> Fixed notification when people change the mobile phone number privacy option

- src/components/Header/components/NavAvatarRightCorner/index.js
- src/components/Header/components/NavAvatarRightCorner/nav-avatar-right-corner.scss
- src/components/Header/components/PeopleSearch/people-search.scss
- src/components/Header/header.scss
- src/components/Header/index.js
Did some redundant clean up in the `people_search.scss file` as well as changing the flex property in the `header.scss file`. 
------
The Page Title Formatting for Long Titles #1131, the padding in the header file has some issue that when I was trying to divide the flex property that was used in 3 groups see image below
right now we only the header is only divided into two part:
I could not exactly make it even because of some more issues, My guess is the overall padding of the header. 
This is another issue that was found while working on the page title it is not a major issue but something to consider.
> S21 page title

- src/components/Profile/components/PersonalInfoList/index.js
This PR allows Gordon police accounts to see emergency contact information on profiles along with more disclaimers
Added:
- Emergency contact Infomation UI (only accessible by police)
Made progress on #897 (Only the UI part)
> Added Emergency Info ui

- src/services/goStalk.js
- src/views/PeopleSearch/index.js
I added "Only Alumni Option" on Advanced People Search.
This is the UI part for https://github.com/gordon-cs/gordon-360-api/pull/608.
BEFORE:
There was only one option, "Include Alumni".
If the user does not select "Include Alumni" option, current students/faculties/staffs show up (exclude alumni).
If the user select "Include Alumni" option, current students/faculties/staffs and alumni show up.
NOW:
There are two options, "Include Alumni" and "Only Alumni".
It shows the same result as the second image on BEFORE.
If the user selects one of two options, the other option turns into disabled.
> S21 Final Update: Advanced People Search Checkboxes

- src/views/PeopleSearch/components/PeopleSearchResult/index.js
- src/views/PeopleSearch/components/PeopleSearchResult/peopleSearchResult.scss
- src/views/PeopleSearch/index.js
Added a checkbox for people search on desktop that enables larger avatar previews for the results list. This should close issue #1212.
before 
After
> People Search Larger Images Toggle

- src/views/PeopleSearch/index.js
Also changed 'show large images' to be a toggle instead of a checkbox
<pre>
^
|
|
</pre>
> (S21) Adjusted layout of people search options and fixed class year

- src/views/Timesheets/index.js
We are switching HR solutions today, and so employment data will be unpredictably unavailable. It was decided that we should disable timesheets until the switch is complete to prevent any data loss or corruption during the switch.
These changes can be undone once the system is fully switched over tomorrow.
Note that my linter automatically removed the unused imports, but they can be restored quite easily by simply reverting this commit in the future.
> Disable timesheets while switching HR systems

- src/views/PeopleSearch/components/PeopleSearchResult/index.js
This PR makes the encrypted ID invisible.
Example:
> Make the encrypted ID invisible

- src/views/Timesheets/index.js
The HR switch over has reached a stable enough point that Timesheets can be turned back on. I am reverting the changes I previously merged, which will restore timesheets to its previous state.
> Revert "Disable timesheets while switching HR systems"

- package-lock.json
- package.json
- src/components/Profile/components/PersonalInfoList/components/UpdatePhoneDialog/index.js
- src/components/Profile/components/PersonalInfoList/components/UpdatePhoneDialog/index.scss
- src/components/Profile/components/PersonalInfoList/index.js
- src/services/user.js
- src/views/PeopleSearch/components/PeopleSearchResult/index.js
- src/views/Timesheets/index.js
The HR Switch over is complete, so we can restore the student timesheets page (in time for students to submit their hours for the pay period that ends today).
Included in this release is the dialog to update phone numbers. This might not work in Production because of mismatched SQL permission issues, but I will fix it when I work in Tuesday. Since Timesheets is a critical system and the update phone is a small, new feature that no one knows exists, I think it is worthwhile to merge it in a (potentially) broken state for the time being.
> RELEASE: Restore timesheets, add Update Phone dialog

- src/views/Home/components/CLWCreditsDaysLeft/index.js
Added functionality to disable the CL&W credit display for the student view of Home when not applicable (aka, Summer/Winter term when credits are not required or recorded). Closes #1243
> Disabled CL&W view for students during Summer/Winter term

- src/components/Header/components/PeopleSearch/index.js
- src/services/people-search.js
This PR fixes the display error on the quick people search.
Before, the quick people search sends requests every time when the input param is changed, which is very problematic because some requests take longer to search which overwrites the search result of the latest request that took much less time.
Before
===
(This happens if you type fast)
---
After
===
> Fix Quick People Search Loading

- src/services/user.js
Increase color contrast for Clifton Strengths to improve accessibility. Thanks @iamphg97 for pointing this out to me!
Before:
After:
Simon would be so proud
> (S21) PATCH - Update Clifton Strength Color Accessibility

- src/views/About/index.js
The API build time is included in the API executable and displayed in the About page.  The recorded time is UTC rather than one of the USA time zones so it's helpful to explicitly state this.  The simplest way to do this is to just add "UTC" to the string displayed in the About page.
> Add UTC label to API build time in About page

- src/components/Header/components/PeopleSearch/index.js
The old code displays nickname if there is a nickname, if not, then check if there is maiden name, if not, then only show firstname + lastname.
The new code displays nickname if there is a nickname and maiden name if there is a maiden name.
> Reorganized quick people search suggestion display

- src/views/PeopleSearch/index.js
This PR prevents using special characters in the text fields of the advanced people search returning everyone.
> Fixed special char return all results

- src/components/Header/Header.module.scss
- src/components/Header/components/PeopleSearch/PeopleSearch.module.scss
- src/components/Header/index.js
Patch to #1306 CSS Modules Migration
- Adds quick search animation on focus like in prod site (refactored width transition into the Header parent)
- Fixed width of People Search Results dropdown (wraps long names)
Resolves #1312
> CSS Modules Migration *PATCH* Quick search animation and width

- src/views/WellnessCheck/components/HealthStatus/index.js
Per the Covid-19 Team, the semester is in full-swing and students have completed the return-to-campus process. Therefore, the return to campus form links on the wellness page can be removed.
> Disable the Return to Campus form links

- src/components/Profile/components/PersonalInfoList/index.js
This PR shows:
- ID for everyone (only students before the change)
- changed 'Student ID' to 'Gordon ID'
Example:
Related to #1328.
> Added: Gordon ID for everyone private profile

- src/components/WellnessQuestion/WellnessQuestion.module.scss
- src/components/WellnessQuestion/index.js
- src/views/WellnessCheck/components/HealthStatus/HealthStatus.module.scss
The contact info is duplicated in two places, but I forgot and only changed it on the Health Status card but not the Wellness Question card.
Also, I updated the link styling to retain underline on hover.
> Update wellness contact info on question card

- src/services/user.js
Quick fix changing the url from "positivity" to the correct "relator" theme url destination.
Resolves #1338
> Fix Clifton Strengths "Relator" Theme URL

- src/components/QuickLinksDialog/index.js
Added:
- A CLOSE button at the bottom of the useful link dialog box.
Example:
(PC View)
(Mobile View)
> Added: close button on link page

- src/services/session.js
- src/views/InvolvementsAll/index.js
E.g. `session=202109` -> `session=2021fall`
Converts back and forth straight from/to URL to avoid complications with how the session code is used elsewhere. This is intended to be a non-invasive change.
Resolves #1179
> Readable Session Codes on Involvements Page

- src/components/Profile/components/OfficeInfoList/index.js
- src/components/Profile/components/PersonalInfoList/index.js
Pretty self explanatory. If there is a value for the dorm or hall of the student, it will not show that they are on campus as it is redundant to have both. 
Here is what it looked like before:
Here is what it looks like now:
Off Campus indicator still works:
Closes #1260
> Removed On/Off Indicator if Dorm Exists

- src/components/Profile/components/Identification/index.js
- src/components/Profile/components/PersonalInfoList/index.js
For everyone:
- **Reorganized**: identification name format: 
- - facStaff with a title: `title + firstName + (nickname) + lastName + (maidenName)`
- - Others:  `firstName + (nickname) + lastName + (maidenName)`
My old profile:
My new profile:
Sample alumni (have nickname and maidenName) old profile:
Sample alumni (have nickname and maidenName) new profile:
- **Added**: Majors, Minors (though alumni don't have minor in database), Graduation Year
Sample alumni personalInfo:
> Added: nickname (all), maiden name (all), graduation year (alumni), major (alumni), minor (alumni) in profile

- src/hooks/useWindowSize.js
- src/views/Events/index.js
Created a custom hook to track width and height whenever the page is resized and adjusted events page to respond to width changes. 
This relates to issue #1323
> Fix event page width

- src/contexts/UserContext.js
The initial value of UserContext was naively `true` if the user is authenticated. This was causing breaking errors, because the user object appeared to be present and so components were trying to access it's properties (while it was still initially `true`). The reason it was set to true was that a falsy value (like null, the most reasonable default) would cause the site to load as if the user were unauthenticated while it was still fetching profile info. This looked like a flash of the login screen before the site loaded.
Now UserContext will white out the screen while we load user info for the first time. If the user is not logged-in, the extra white screen is not noticeably longer than previous loading times. If the user IS authenticated, it takes a tiny bit longer, but it should end up …
> Fix UserContext issues with initialValue

- src/services/news.js
News search returns nothing whenever you type in a capital letter. This is because I earlier neglected to lowercase the search string when also lowercasing the other values to compare it to.
> Fix News Search Uppercase Issue

- src/components/Profile/components/PersonalInfoList/index.js
The official term for students who haven't picked a major yet is 'Deciding', not 'Undecided'. Also, alumni who have no majors are not 'Deciding', they just don't have majors listed in our system. Hence, we only show the majors list item if the profile belongs to a student, or to an alum who has majors.
> Show Deciding when no majors, and hide for alum without majors

- src/services/wellness.js
- src/views/WellnessCheck/components/HealthStatus/HealthStatus.module.scss
- src/views/WellnessCheck/components/HealthStatus/index.js
- src/views/WellnessCheck/index.js
This PR is the counterpart to gordon-cs/gordon-360-api#674. It shows the StatusDescription on the user's HealthStatus, if there is a StatusDescription to show.
It also refactors the HealthStatus scss module to reduce code duplication and simplify it greatly. By using CSS custom properties, we can declare the styles for the component only once, and override the dynamic properties (in this case, just the background and text color) depending on which color of status is showing. This is a much cleaner alternative to the previous approach of redeclaring the same properties for each color, only changing the background and text color (and changing it in several places). This also helps ensure consistency across the styles.
> Wellness: Add StatusDescription

- src/views/EnrollmentCheckIn/components/EnrollmentCheckInWelcome/components/MajorHolds/index.js
- src/views/EnrollmentCheckIn/components/EnrollmentCheckInWelcome/components/MinorHolds/index.js
- src/views/EnrollmentCheckIn/components/EnrollmentCheckInWelcome/index.js
It turns out that #1432 broke the holds text for major holds in the enrollment check-in process. I had intended to simplify the `displayMajorHolds` method using an array instead of multiple variables to store the needed hold text. However, displaying the resulting list of holds text using `Array.protoype.join()` did not work as expected because the elements of the array were not string but rather `react.element`s. This meant that when displaying holds, they would be displayed as `[object Object]` to the end user. #1439 fixed this for single holds (which I thought at the time was the only issue), but not for multiple holds.
This hotfix has re-structured the way hold text is displayed. Rather than calling a function that returns the hold text, we now have a React component which is …
> Hotfix: Enrollment Check in - Fix major holds

- src/services/goStalk.ts
People Search was broken since the switch to TypeScript because the class filter defaults to '', rather than null or a meaningful variable.
> Fix People Search class filter

- src/views/WellnessCheck/components/HealthStatus/HealthStatus.module.scss
The wellness status module does not show the "Status: ..." message if your screen is too wide (too wide being most computer monitor sizes). This is due to a static height being set for the colored box which is not tall enough to show the message.
My proposal is that we simply remove the css for the height and let the block size itself. I have tested with yellow and green status with many different page sizes and that is the most responsive option.
Current:
Proposed:
> Remove Static Height for Health Box

- src/services/cms.ts
- src/views/BannerSubmission/components/Banner/Banner.module.scss
- src/views/BannerSubmission/components/Banner/index.js
- src/views/BannerSubmission/components/BannerAdmin/BannerAdmin.module.scss
- src/views/BannerSubmission/components/BannerAdmin/index.js
- src/views/BannerSubmission/components/BannerList/BannerList.module.scss
- src/views/BannerSubmission/components/BannerList/index.js
- src/views/BannerSubmission/components/NewBannerDialog/NewBannerDialog.module.scss
- src/views/BannerSubmission/components/NewBannerDialog/index.js
- src/views/BannerSubmission/index.js
- src/views/Home/components/Carousel/index.js
Since October 2021, there has been no way for site admins to change the banners on the home page carousel themselves. Instead, they've had to ask CTS to do it. This adds extra work for both parties and is generally cumbersome and undesirable. 
This pull request introduces a banner admin page from which site admins can upload and delete banners. Once gordon-cs/gordon-360-api#683 is merged, site admins will be able to use this page to manage the home page carousel themselves, while regular users will see that same message about how to submit banners for approval. While it might be nice to build an approval process within 360, it would not have any material benefits over the existing email approval process, so it has not been deemed as high priority.
Desktop view:
Mobile View:
Add New Banner …
> Add admin ability to submit banners to the home page carousel from 360

- src/views/ApartmentApp/index.js
The application period for apartments ends at 5pm this evening. The Housing office has requested that we "close" the application at that time so that students don't get confused and/or mistakenly submit an application after the deadline.
This "closes" the application period by replacing the student application with a message that the application period has ended. This ensures that the housing admin is still able to access the admin page, but students cannot submit a late app.
> "Close" ApartApp page at end of application period

- .env.development
- src/services/http.ts
- src/setupProxy.js
In development (i.e. when running the front-end locally via `npm run start`), we want API requests to be sent to the front-end node server, and re-directed by the http-proxy-middleware to the appropriate API. This is because the proxy sets the `origin` header of API requests to the API url, thereby circumventing CORS errors while developing 360 locally.
While we could prevent CORS errors by allowing cross-origin requests from localhost in the API, that would be a bad idea. Essentially, that would allow nefarious third-party websites or applications on a user's machine to impersonate us and send requests on their behalf, compromising our API using their credentials.
Instead, this solution allows us to connect to any of our API servers while running the API locally, but ensures that from …
> Fix CORS for development

- src/services/auth.ts
The `loginPopup` authentication flow of `@azure/msal-browser` is not working on Safari (on both Macos and iOS). The login redirect works well on all browsers (and actually simplifies the code a little bit), so I am switching to that.
> Redirect for auth, fixing Safari login

- src/components/Profile/components/PersonalInfoList/index.js
We can't use AuthGroups to decide what profile info is relevant for now, becuase we can only access AuthGroups of the authenticated user. This will likely change in the future, but for now, we will revert to using PersonType to determine what info is relevant.
Note that this is not really related to security, since the API controls what profile info is sent. This just ensures that we're only trying to show the correct kind of info on profiles of a given type.
> Use PersonType to filter profile info temporarily

- src/views/EnrollmentCheckIn/components/EmergencyContactUpdate/index.js
- src/views/EnrollmentCheckIn/components/EnrollmentCheckInWelcome/index.js
- src/views/EnrollmentCheckIn/index.js
This PR is a hotfix to the enrollment check in system. It is being pushed as a hotfix because the system went live overnight for the coming semester and the following changes were determined to be immediately necessary:
- Updating the description of the Add/Drop period: rather than hard-coding dates for a specific semester, we just specify that classes can be added during the first five days of classes, which is the standard add/drop period.
- Removing the wellness check in button: since students aren't being required to display their wellness check in on campus, they do not need to access before completing enrollment check in.
- Require either home or mobile phone but not both: awe require that each emergency contact a student lists include some phone number at which we can reach that …
> Hotfix: Update enrollment checkin

- src/services/activity.ts
- src/views/InvolvementProfile/index.js
Depends on gordon-cs/gordon-360-api#698
This PR fixes involvement updates. Since upgrading the API, involvement updates have been broken because of type mismatches between the API and the UI. I have resolved those mismatches, but it required the introduction of a new type, InvolvementUpdate, which is introduced to the API in gordon-cs/gordon-360-api#698. Therefore, this PR will not work without that API PR. This is not a breaking change because the functionality targeted is already broken 😅.
> Fix updating involvements

- src/components/Profile/components/Identification/index.js
- src/components/Profile/components/PersonalInfoList/index.js
- src/services/cliftonStrengths.ts
- src/services/user.ts
Now that gordon-cs/gordon-360-api#700 has been deployed, the API enables users to manage the privacy of their Clifton Strengths. This PR adds a graphical affordance to the My Profile page that allows users to see and manage the privacy of their Clifton Strengths data. It also updates the Public Profile page to respect the privacy setting of Clifton Strengths.
Closes #1485
> User-managed Clifton Strengths privacy

- src/views/EnrollmentCheckIn/index.js
We were setting `loading` to false while the profile was still loading, before data loaded. That meant that as soon as the profile loaded (and before the data was all loaded), we were showing the page, which is not supposed to happen. Now, we only show the page after the profile and data has loaded (even if the loaded value is null).
> Only show page after profile and data is loaded

- .env.production
This release includes #1491, which fixes Enrollment Check In to only show the page after the profile and data is loaded, preventing users from continuing to check in before their holds have been loaded.
It also reapplies #1483, which was undone by the previous release.
> Release: Fix Enrollment Check In Loading and Text

- src/views/Home/components/GuestWelcome/GuestWelcome.module.scss
- src/views/Home/components/GuestWelcome/index.js
The Guest Welcome page changed shape once the old login form was removed. I have updated it to be slightly more appealing by putting a max width on the card and adding a (technically redundant but still helpful) login button.
> Beautify Guest welcome

- src/components/Profile/components/PersonalInfoList/index.js
- src/services/auth.ts
This Pull Request shows ID Number on students' public profile to members of the `SensitiveInfoView` authorization group. The group is carefully curated to only include the subset of Student Life and Campus Safety staff that need access to that data to perform their jobs.
> Show ID Number on public profile as Sensitive Info

- src/views/InvolvementProfile/components/Membership/components/AdminCard/index.js
- src/views/InvolvementProfile/components/Membership/components/MemberList/index.js
I somehow missed renaming the props for MemberList and AdminCard even though I renamed the props for the other components (including their child components). This fixes that mistake so that the correct prop is passed all the way through the component tree.
> Rename prop `isSuperAdmin` -> `isSiteAdmin`

- src/views/Home/components/DiningBalance/index.js
The DiningBalance donut chart was displaying days left in the semester incorrectly, because the code called `Math.min` instead of `Math.max` (so that we never try to display a chart with negative days left).
> Fix dining balance days left chart

- src/views/RecIM/components/Listing/Listing.module.scss
- src/views/RecIM/components/Listing/index.js
- src/views/RecIM/views/Match/index.js
- src/views/RecIM/views/Team/Team.module.scss
- src/views/RecIM/views/Team/index.js
This is what the current team page looks like (and subsequently what the participant listing looks like).
Somethings to consider in this PR:
- Maybe switch from the grid div system we have been using for listings and switch to MUI List as it would be more synonymous with the rest of 360
- Pass user id probably better than AD username, but this requires us have dummy data and a complete participant fetching protocol as we need more data than just user ID
> Finished team page layout and photo fetching for participants

- src/views/RecIM/components/List/Listing/Listing.module.scss
- src/views/RecIM/components/List/Listing/index.js
- src/views/RecIM/components/List/index.js
- src/views/RecIM/views/Activity/index.js
- src/views/RecIM/views/Home/index.js
- src/views/RecIM/views/Match/index.js
- src/views/RecIM/views/Team/index.js
This PR abstracts the listing we were doing with divs, to using MUI lists to link our pages together. It also moves these lists to a component file so they can be reused in different sections of the RecIM pages. Here is a picture of what it looks like with the new lists,
Ignore the PR I accidentally put into the merge into develop category!
> Update lists to MUI and abstract List Components

- src/services/membership.ts
- src/views/InvolvementProfile/components/Membership/components/MemberList/components/MemberListItem/index.js
This PR removes the alumni profile link in involvement page when the user is student, for students should not have access to alumni profile even if the API returns `NotFound()` and the UI redirects them to `NotFound` page.
As the image shows, the second user is black, which means the name is not linked to profile.
Links #1553.
API PR: https://github.com/gordon-cs/gordon-360-api/pull/747.
> remove alumni profile link in involvement page when the user is student

- src/views/About/contributors.json
Looks like we missed this update last Spring. Adding developers that worked in the Fall of 2021 while they were able.
> Update Contributors for 2021/2022 School Year

- src/views/ApartmentApp/components/StudentApplication/components/Agreements/index.js
See CTS ticket 151450
Ethan Mignard has requested that the following be added as another agreement checkbox on the apartapp agreements:
```We agree to host other students in our apartment during the winter break recess, in accordance with the policy outlined in the student handbook```
This PR adds the text.
> Add Agreement Checkbox for Winter Housing Hosting

- src/components/AppRedirect/index.js
- src/views/EnrollmentCheckIn/index.js
- src/views/PublicProfile/index.js
There were a couple lingering components that broke on upgrade to react-router, mainly because of using `props.history` or `Route` instead of `Navigate`. I have fixed these last few.
> Fix react router Navigate

- src/app.js
- src/services/checkIn.ts
Restores `AppRedirect` to automatically redirect users to Enrollment Check-in when it isn't complete, and assumes that, when a user's enrollment check-in status can't be fetched, they have completed it.
> Fix enrollment check in

- src/components/SpreadsheetUploader/index.js
@ChrisImagineer noticed that our spreadsheet uploader was actually not working for excel ".XLSX" files even though we were stating that it should on the upload page.
I did some research and discovered that there is actually another format for Excel files that we have to allow. This change adds that format to the acceptedTypes variable.
> Allow additional format of xlsx upload

- src/views/RecIM/components/Forms/CreateActivityForm/index.js
- src/views/RecIM/components/Forms/components/ConfirmationRow/index.js
- src/views/RecIM/components/Forms/components/InformationField/index.js
Fixes couple DateTime things:
- DateTime pickers re-added after being removed in previous merge conflicts
- Package dependency swapped from dayjs to date-fns, which is what 360 currently uses
- Confirmation window now shows DateTime as a properly formatted (with timezone) string
Noted a bug where activities are all showing time of midnight... Is this a DB or API issue that we are already aware of?
> [Rec-IM] Fix datetime

- src/views/CoCurricularTranscript/index.js
- src/views/IDUploader/index.js
Some class components were still depending on the `authentication` prop to know whether the user is logged in. However, when we upgraded to React Router v6, we removed this prop in favor of the `useIsAuthenicated` hook. The simplest way to use this hook with the class components is by passing it as a prop via a Higher Order Component.
> Pass `authentication` to class components

- src/views/CoCurricularTranscript/index.js
The CCT is currently broken for members of the community who do not have a graduation date (most facstaff). This is because the value check does not account for possible `null` values. This PR modifies the inspection to cover all "empty" values with a simple boolean inverse.
> Fix Grad Year Check for Co-Curricular Transcript

- src/components/AppRedirect/index.js
The AppRedirect component previously only updated it's data when the user's authentication status changed. This meant that, for example, when a user completed enrollment check in, AppRedirect would not be made aware of the change in check in status until the user refreshed the page (or signed out and back in).
> Reload redirect data on navigate.

- src/views/PeopleSearch/components/PeopleSearchResult/index.tsx
As @russtuck points out ( closes #1607 ), people search is currently linking users to a broken page from the results objects. This is because the link is using a relative path (starting from `/people`) rather than a static path (starting from `/`). This PR sets the path as static.
> HOTFIX: Fix people search navigation

- src/services/recim/activity.ts
- src/views/RecIM/components/Forms/TeamForm/index.js
- src/views/RecIM/components/List/Listing/index.js
- src/views/RecIM/views/Activity/Activity.module.scss
- src/views/RecIM/views/Activity/index.js
- src/views/RecIM/views/Home/Home.module.scss
- src/views/RecIM/views/Home/index.js
- src/views/RecIM/views/Team/index.js
Additions
- Basic Edit Team Form
- Added On-going Activities on Home Page
Permissions Created:
Home Page
- Admins are the only ones allowed to create Activity
Activity Page
- Admins are the only ones allowed to EDIT the Activity
- Admins are the only ones allowed to Create a Series
- Students can only Create a Team if they are not already participating in the Activity
- Admins can Create a Team whenever
Team Page
- Only Admins can edit Team Status
- Student Captains/Co-Captains can edit Team Name and Invite Participants WHEN registration is open
- Admins are not restricted by the clause above
> [Rec-IM] Edit Team functionality integration + Admin/Team-Captain permissions

- src/components/Profile/components/PersonalInfoList/index.jsx
- src/services/cliftonStrengths.ts
Clifton Strengths on the profile page is supposed to link to the Gallup introduction to each theme. However, because the link was using React Router's `Link` tag, the `href` prop (which was pointing to the correct page) was being ignored because the `Link` component requires a `to` prop instead.
Closes #1590
> Fix clifton strengths external links

- .github/workflows/ci.yml
GitHub is bumping the minimum Node Version of their actions to Node v16, which requires updating the action versions in our workflows.
> Update Workflows for Node v16

- .github/workflows/ci.yml
The output path of our builds has changed from `/build` to `/dist` since upgrading to Vite, so the CD script needs to be updated.
> Update continuous deployment for Vite

- src/components/Profile/components/PersonalInfoList/index.jsx
- src/services/auth.ts
Faculty and staff are currently unable to physically view advisor information of students on the student's profile. To resolve this, the authentication group 'AcademicInfoView' was made so that anyone included in this auth group would be able to see the advisors in a student's profile. 
This PR allows any user in auth group AcademicInfoView to also view the advisor information of a student in the student's profile, in addition to students that can already view their own advisor information on their profiles. 
fixes #1509
> Allow `AcademicInfoView` AuthGroup to view advisor info of students.

- src/views/Timesheets/index.jsx
The LocalizationProvider for Timesheets was wrapping the whole page except for the `ShiftDisplay`. When someone tried to edit shifts within the `ShiftDisplay`, they would receive a MUI error because no LocalizationProvider was present.
> Wrap ShiftDisplay in LocalizationProvider

- src/components/EventList/index.jsx
This check to see if there are any events with the current filters is checking for `length < 0` which is a case that will never occur. This PR updates the logic to check `length <= 0` instead.
> Fix Case for Showing no Events Message

- src/services/user.ts
This PR fixes some logic in fetching a user profile so that Clifton Strengths show on the profiles of both Fac/Staff and Students if it is available (and/or public?). 
Fixes #1642
> Clifton Strengths to show on both Fac/Staff and Student Profiles

- src/views/InvolvementProfile/components/Membership/components/AdminCard/index.jsx
This PR will fix the issue where the involvement member form saves with the previously inputted values after closing it. This will update it so that after closing the member form list, it clears it out.
> Add state updates after Addmember function to 'clear' the form after close.

- src/views/InvolvementProfile/components/Membership/index.jsx
Involvement memberships are currently not loading for non-site-admins unless they are a member of the involvement. This is caused by a null coalesce with a user's personal membership to check if their participation is of type guest. If they are not a guest, they are allowed to see the membership. Unfortunately `membership?.ParticipationType` resolves to `null` when the current user is not a member of the involvement, and the comparison `membership.Participation !== Participation.Guest` resolves to `true`.
This PR fixes the issue by first checking if the membership is not falsey (aka not null).
I also added a UI cleanup that does not show the members block if the memberships array is empty. Otherwise it could cause some confusion if a user is seeing a blank table whereas others see members …
> HOTFIX: Involvement Membership Loading

- src/services/user.ts
The "is birthday today" logic in the user service was comparing date ISO formats to see if a user's birthday was the current date. Unfortunately, the user's birthday in ISO format also includes the year that they were born so this will essentially never resolve to true.
This PR updates the logic so that it compares the month number and the day of the month (1-30ish) rather than the ISO date string.
This change will officially activate the "Happy Birthday" message feature for the first time in Production.
> Fix Happy Birthday Message

- vite.config.ts
This PR will change the VITE configuration so that it allows the user to specify the hostname and port that they want VITE to try to run on as an option. It reads this information from the env files as `VITE_PORT` and `VITE_HOST`.
> Read Vite Port and Host From Env File

- src/services/checkIn.ts
There is some disconnect that happens momentarily when the user first opens the site after a significant time away, where `useIsAuthenticated` from MSAL returns `true`, but the token provided by MSAL is not valid according to the API. I suspect this may involve token refreshing, but don't know for certain.
This disconnect was causing issues with the `AppRedirect` component, which was redirecting users erroneously to the Enrollment Check In page. The problem was that AppRedirect requests the user's enrollment check in status when `useIsAuthenticated` returns true, but in the brief milliseconds where the token is still invalid, the API was returning a `401 Unauthorized` response. AppRedirect caught the resulting `AuthError`, but was only expecting instances of `NotFoundError`, and so was …
> Don't redirect on auth errors

- src/services/error.ts
- src/views/InvolvementProfile/components/Membership/components/AdminCard/index.jsx
The current mode for catching 'Member Already Added' exceptions/errors is bypassed because the error message does not return exactly what is expected by the code (replicated by trying to add an already existing member to a club/involvement).
As a result, there is currently no visual/UI response when trying to add a member that already exists. There is only a console error.
This PR creates a new error 'Conflict Error' which is caught when trying to add an already existing member. The caught error will product a snackbar that states that 'username' is already a member.
Fixes #1701 
This is an extension of [this PR](https://github.com/gordon-cs/gordon-360-ui/pull/1702). Extended due to some unwanted files in the original PR.
> Create new 409 Error 'Conflict' to give a 'Member Already Added' error message for involvements

- package-lock.json
- package.json
- src/components/Providers/components/AuthProvider/index.tsx
- src/components/Providers/index.tsx
- src/index.tsx
- src/services/auth.ts
- vite.config.ts
Hot Module Reloading was broken in two ways with the recent migration to Vite.
1. HMR doesn't work because of Circular Dependencies:
- The Microsoft Authentication Library (MSAL) package we use for Auth requires a single instance of the PublicClientApplication to be created at runtime. This instance requires some complex configuration, which was kept in `src/services/auth.ts`, but the instance has to be created once at runtime when the app starts up, so it was being done in `src/index.tsx`. The problem is that all the other methods in `auth.ts` require a reference to the MSAL instance, so `auth.ts` was importing the instantiated object from `index.tsx`. This created a circular dependency where index.tsx imports from auth.ts and then auth.ts imports from index.tsx.
The solution is to move …
> Fix Hot Module Reloading

- src/views/InvolvementProfile/components/Membership/components/MemberList/components/MemberListItem/index.jsx
- src/views/InvolvementProfile/components/Membership/components/MemberList/index.jsx
This pr removes Mail Location from the Involvement Profile page. If anyone wants to know the mail location of another member, they can simply click the link to other's profile and view it there.
PS: this pr was originally planned to solve the duplicate mail location bug, but turned out we decided to move forward with another approach without Mail Location.
Here is the new UI for Involvement Profile page.
Full screen
Mobile view
< Admin View >
Full screen
Mobile view
> Drop Mail Location from Involvement Profile page

- src/views/RecIM/components/Forms/ActivityForm/index.jsx
- src/views/RecIM/components/Forms/TeamForm/index.jsx
While the image is null, the UI still throws an error when you clicked the `submit` button. That's because of the following code, where on line 337 compares `cropperImageData` and `null` value. But the operator is wrong here. When we use `!==`, this compares the data type on both sides, and since `undefined` is not the same type as `null`, the code will go through line 338 which the cropper is `undefined` in `cropperRef`. So the correct operator is `!=`, where both `undefined` and `null` are false, thus the code goes through line 339 instead of line 338.
> Recim image first hotfix

- .env.production
- src/_vars.scss
- src/views/RecIM/components/Forms/MatchForm/index.jsx
- src/views/RecIM/components/List/List.module.scss
- src/views/RecIM/components/List/Listing/Listing.module.scss
- src/views/RecIM/components/List/Listing/index.jsx
- src/views/RecIM/components/List/index.jsx
- src/views/RecIM/components/index.jsx
- src/views/RecIM/views/Activity/Activity.module.scss
- src/views/RecIM/views/Activity/components/ScheduleList/index.jsx
- src/views/RecIM/views/Activity/index.jsx
- src/views/RecIM/views/Home/Home.module.scss
- src/views/RecIM/views/Home/index.jsx
- src/views/RecIM/views/Match/index.jsx
- src/views/RecIM/views/Team/Team.module.scss
- src/views/RecIM/views/Team/index.jsx
Team Records
--
Comparison (OLD)
- Teams now have a Win/Loss count (Tie is unavailable currently as the calculation needs a rework)
- Activity font on the listing is smaller, and location has been moved below the team name (the benefit of this is that we can fit longer team/activity names and only need a smaller space for the listing/invite)
- `Home` shows an all encompassing Activity Record (a calculation done on summation of Series Records)
- `Activity` page shows Series Records individually and sorts them by Most Wins
- Activity see's teams by `Series` (thus individual series records)
- Tab is autofocused on first `ongoing` series (handled by time), defaulted to first tab
- Series tabs are centered **UNTIL** they need to be scrollable
- MUI does not allow for scrollable and centered, …
> [Rec-IM] Show/Sort Series Teams by Series Records + Styling Update

- src/components/Profile/components/PersonalInfoList/index.jsx
Continuation from #1709.
This PR fixes state logic for showing which selection (from private or public) personal information currently is. Previously, the logic for setting the state of the toggle always returned false when there was no Home phone no. added (it seems), which automatically set the toggle to 'true' (which is shown as public by the toggler). So whether or not you set your profile as private or public with the toggle, it would show that it was set to public (see https://github.com/gordon-cs/gordon-360-ui/issues/1653).
> Fac/Staff Personal Info Toggle Visual Fix

- src/views/InvolvementProfile/components/Membership/components/MemberList/components/MemberListItem/index.jsx
This PR fixes the member profile links in an involvement on small screens by fixing a variable name.
Fixes #1638
> Fix Involvement Member Links on small screens

- src/views/RecIM/views/Home/index.jsx
There was a bug that caused non-participants to load infinitely on the home page due to `Team Invites` and `Participant Teams` loading (since they weren't participants). Logic is moved after we check for a participant; if `null` we know that they haven't signed up for rec-im (which is fine). 
Next thing to do is to move the `Waiver` to `Accept Team Invite` and `Join an Activity`
> [Rec-IM] Home Page hang

- package-lock.json
- package.json
- src/components/SpreadsheetUploader/index.jsx
- src/views/Admin/components/CliftonStrengthsUpload/index.jsx
I have updated our `xlsx` package to the latest version. Note that the `xlsx` [package on the public npm registry](https://www.npmjs.com/package/xlsx) is no longer the authoritative version and is not being updated. The official source for the package is now their own [cdn](https://cdn.sheetjs.com/) (and also the official source code is in their own Gitea instance, with the GitHub repo being deprecated).
I have tested that the updated package works as expected.
I fixed a regression in the Clifton Strengths uploader caused by a bad merge during the switch to Vite (my bad!).
I have also refactored the `SpreadsheetUploader` component. The only behavioral difference is that the preview of uploaded data now has a `max-height` of `40vb` (aka 40% of the height/block-direction of the viewport). …
> Update `xlsx` dependency

- src/services/recim/sport.ts
- src/views/RecIM/components/Forms/Form/components/InformationField/index.jsx
- src/views/RecIM/components/Forms/SportForm/index.jsx
- src/views/RecIM/components/Forms/SurfaceForm/index.jsx
- src/views/RecIM/components/List/Listing/Listing.module.scss
- src/views/RecIM/components/List/Listing/index.jsx
- src/views/RecIM/components/List/index.jsx
- src/views/RecIM/views/Activity/index.jsx
- src/views/RecIM/views/Admin/Admin.module.scss
- src/views/RecIM/views/Admin/index.jsx
This PR allows for the creation of sports on the admin page, with the following layout.
Here is the corresponding form that appears when the "add a sport" button is clicked
A rule book now appears on the top right corner of the match page, with a clickable button to bring up a rule tooltip,
Let me know if it looks good! The only thing I can mention, is that I could see the rules button opening a card with the rules if they were expected to be long. But I think that the tooltip will work for RecIM's purposes.
> [RecIM] Sports!

- src/views/InvolvementProfile/InvolvementProfile.module.scss
- src/views/InvolvementProfile/index.jsx
This PR just adds some styles and moves some code around so that 
1. Users can see the text to 'drag and drop or click image to choose image' which was previously covered up by the existing involvements photo (see #1747 example).
2. Users can no longer see the text asking to select an image when there is actually no functionality to do so (see example below).
Example:
Before:
After:
Fixes #1747
> Update visuals for involvements 'change image' use case

- src/views/PeopleSearch/components/PeopleSearchResult/PeopleSearchResult.module.scss
- src/views/PeopleSearch/components/PeopleSearchResult/index.tsx
Implements a use case where you can easily start emailing someone from the people search results list by adding a mailing icon/button for each result listed. 
This is only implemented in Desktop view for now because of the limited space for such a use case on a mobile view.
Fixes #1194
> Add a Mailto link in the search results page

- src/components/AppRedirect/index.jsx
- src/services/auth.ts
- src/services/checkIn.ts
The user was getting erroneously redirected to the Enrollment Check In page. This error seemed to occur when first opening the app after a multi-hour period of inactivity.
This bug has proven almost impossible to reproduce consistently in the development environment. However, based off of my observations in our deployed environments and a deep dive into the execution order of the redirect process, I believe I have narrowed down the cause of the issue. It seems to be a blip in authentication logic when an authenticated user has an expired token.
The way that our authentication library works is that the user authenticates against Microsoft using their Gordon (Microsoft Exchange) account. If the user authenticates to Microsoft successfully, Microsoft returns them to our site along with an ID …
> Fix erroneous redirects

- .env.production
- package-lock.json
- package.json
- src/app.jsx
- src/services/analytics.ts
- src/views/Home/components/GuestWelcome/index.jsx
This PR updates the version of our Google Analytics package to work with their new version 4 which will replace Universal Analytics on July 1st.
The changes are pretty minimal and simple but we needed a new tag code to use on the site as well. Most of the new features are in the analytics dashboard itself.
> Update Google Analytics to V4

- src/services/errorLog.ts
- src/services/logging.ts
- src/views/IDUploader/index.jsx
The error logging within the ID Uploader service depends on deprecated navigator APIs (platform, appVersion, vendor) - as well as the `navigator.userAgent` that is gradually being deprecated and quickly becoming less than informative - for useful error logging. This is causing problems because the data extracted from these old APIs is now appearing in logs as repeated "unknown"s, which is not very helpful.
Chromium-based browsers (which hold >70% market share of browsers) already support the (currently experimental) User Agent Data interface that is planned to take the place of these old interfaces<sup>1</sup>. As such, I have updated the logging logic to take from the User Agent Data API if it exists in the browser, and to fallback to the old user agent otherwise.
I also updated the …
> Improve error logging for ID Uploader

- src/views/Home/components/GuestWelcome/index.jsx
When we updated to the `react-ga4` package, someone updated an import without actually checking that the import was still valid. It was not still valid, and it caused unauthenticated users to see an error page on the home screen, breaking the site.
I have updated the import to use the new syntax from the new package.
> Use ReactGA properly

- src/components/GordonDialogBox/index.jsx
Improved UX for computer users.  Enter key will now press the submit button when the dialog box is focused and the button is available.
https://github.com/gordon-cs/RecIM-Docs/issues/83
> Implemented enter key submission in GordonDialogBox

- src/services/recim/participant.ts
- src/views/RecIM/components/Forms/InviteParticipantForm/index.jsx
- src/views/RecIM/components/Forms/ParticipantForm/index.jsx
- src/views/RecIM/components/List/Listing/index.jsx
- src/views/RecIM/components/List/index.jsx
- src/views/RecIM/components/QuickSearch/QuickSearch.module.scss
- src/views/RecIM/components/QuickSearch/index.jsx
- src/views/RecIM/views/Admin/index.jsx
This pr adds a new form that allows creating custom participants, and updating their info in the Admin page.
Also improves the loading speed of Admin page by replacing `GetProfileInfo()` with a lighter method.
API pr: https://github.com/gordon-cs/gordon-360-api/pull/891.
New `Create Participant` Button
`Create Participant` View
Only `Custom Participant` has the `MoreOption` Button at the righthand side
And they don't have a pic for now
Menu displayed when clicked the `MoreOption` Button
`Edit Participant` View
Quick Search in RecIM team page
* Admins can search both Gordon participants and non-Gordon participants
**Participant List Checklist**
* let me know if I missed any
> [Rec-IM] Create & Edit custom participant in Admin page

- docs/Developer's Guide.md
It has worked well for developers to clone this repository using SSH rather than HTTPS.  The developer instructions have been modified to direct developers to use this method.  Instructions are provided create a new key (if they don't already have one) and install it on Github.
> Add instructions to use ssh when cloning repository.

- src/services/http.ts
Currently all our updates use `http put` which is not correct terminology when updating elements of a resource and not the entire resource. 
This update has already been in the `recim` branch, but as the branch is not ready to be merged, it would be beneficial for the practicum students to have access to the patch route.
> Add patch route to http.ts

- src/components/Header/index.jsx
- src/views/PeopleSearch/components/SearchFieldList/index.tsx
For posterity - somehow, the `popstate` event listener was not being triggered within `SearchFieldList` when the user navigated in history. The fix was to add the event listener within a separate useEffect that only runs on mount, rather than inside the one that runs everytime `location` from React-Router updated.
Somehow, this bug in the event listener didn't appear until the Header component called `useLocation`. We have no idea why that is the case. :shrug:
> Fix PeopleSearch params not updating on navigation

- src/components/Header/index.jsx
- src/views/PeopleSearch/components/SearchFieldList/index.tsx
Reverts gordon-cs/gordon-360-ui#1906
While this improves the code, it doesn't fix the "back" button going strictly between people searches.  Let's revert this, and PR 1837 (via 1905), so we can release the rest of the improvements.  Then we can work on a new fix that incorporates both of these PRs.
> Revert "Fix PeopleSearch params not updating on navigation"

- src/views/PeopleSearch/components/SearchFieldList/index.tsx
Previously, we listened for the `popstate` event and updated a `ref` when the event happened. Simultaneously, we had a useEffect that would run whenever `location` changed, which would update the search params from the URL *if* the `ref` said to. This *almost* worked, except that, on the very first `popstate` event, the ref would not update before the `useEffect` ran, meaning we wouldn't read the params from the URL the first time that the user triggered `popstate` after `SearchFieldList` mounted.
The solution is to simply perform the update (i.e. read the params from the URL) directly inside the event listener callback. The only times we need to read the params from the URL are when the component first mounts (in case we're mounting with a paramful URL, i.e. because the user opened 360 …
> People Search: Read params from URL directly in event listener

- src/views/PeopleSearch/components/SearchFieldList/index.tsx
If you had previously added parameters such as Major, Minor, or Class_Year and unchecked the student box the parameters will be cleared. This prevents a search with no results.
The same will happen for the parameters Department and Building for the faculty/Staff checkbox.
issue: https://github.com/gordon-cs/gordon-360-ui/issues/1929
> changed handleUpdate to clean params when checkboxes are unchecked

- src/services/recim/series.ts
- src/views/RecIM/views/Activity/components/ScheduleList/index.jsx
Old API feature that was requested by the customer but was never implemented in the UI.
Adds use to `Round Robin Match Capacity` and `Ladder Matches`
> [Rec-IM] auto sched parameters

- src/components/Profile/components/OfficeInfoList/index.jsx
The public profile of any user with Office Info is currently broken in develop because the code is passing an object as a React child. The fix is to pass strings instead.
I also fixed all the linting warnings because of unused code and imports.
> Fix broken public office info

- src/views/PeopleSearch/components/PeopleSearchResult/index.tsx
People search results either show users profile pictures (if they exist) or fills this area with a neutral gray color.  The gray color used worked well in light mode but was a little bright in dark mode.  This PR replaces the fill color with a neutral gray but with 15% opacity so it blends the background color.  The blank images look just about the same in light mode but are much darker in dark mode.
> Replace people search missing image default color

- src/views/RecIM/components/List/Listing/Listing.module.scss
- src/views/RecIM/components/List/Listing/index.jsx
- src/views/RecIM/components/List/index.jsx
- src/views/RecIM/views/Match/index.jsx
Usage is for visually displaying matches that have more than 2 teams playing.
NEW
--
- pseudo-listing for teams. Ordered by points then sportsmanship score. 
- attendance accordion for visualization of participants on a team as well as attendance marking
- Header has the name of the activity as well as the image of the activity until marked as completed, where the winner will be listed as well as their logo picture.
QOL
--
- completed activities cannot have their information edited. (API will throw an error, but preventing the options makes life easier)
`new`
- Mobile used to clash listing size. New smaller attendance listing 
Associated API PR:
https://github.com/gordon-cs/gordon-360-api/pull/979 
Generates more lightweight objects for multi team matches
> [Rec-IM] Ladder Match Page

- src/components/Header/index.jsx
On the header of Gordon 360, the tab for  RecIM would not highlight when user is using RecIM so it was fixed
> Header highlight fix for RecIM

- src/views/RecIM/components/List/Listing/index.jsx
get participant now holds first/last names (based on a view). Thus we don't need to use the expensive getProfile hook which results in
> Implement full name into current participant get

- src/views/Timesheets/index.jsx
As of August 20th, all students will enter their timesheets on Criterion. Payroll has said that 360 Timesheets can stay active until the next pay period is processed so that students can continue to enter timesheets for the previous period until that date.
I have added a notice that Timesheets is moving, and set it to completely replace Timesheets as of August 27 (current approximation of switch over date).
Interim notice:
Permanent notice:
> Give notice that timesheets has moved to Criterion

- src/views/Timesheets/index.jsx
Payroll has indicated that no further Timesheets submitted via 360 will be processed. All future timesheets must be submitted to Criterion, and retroactive timesheets must be negotiated with Payroll directly.
> Update Timesheets Move Notice

- src/components/Header/Header.module.scss
Apparently `position: sticky` creates a new stacking context with a default z-index of 0. This caused the Qucik search results in the header to appear underneath any raised content on the page, because it could never go higher than it's parent's stacking context z-index of 0. Setting the app bar to have a z-index of 100 resolves the issue.
> Hotfix: quick search z index

- src/views/HousingLottery/HousingLottery.module.scss
- src/views/HousingLottery/index.jsx
- src/views/HousingLottery/studentView/StudentApplicants/ApplicantFields/index.jsx
- src/views/HousingLottery/studentView/StudentApplicants/index.jsx
First draft of the Add Participant box. Has a text field for the name of the participants to add and a field to type the Gordon email of the participant.
> Add Participant Box

- src/services/housing.ts
- src/views/HousingLottery/adminView/index.jsx
- src/views/HousingLottery/studentView/index.jsx
Update and get the due date of the housing applications
> set and get due date

- src/components/Profile/components/OfficeInfoList/index.jsx
This PR will fix a bug with the OfficeInfoList block on the user profile where the block does not show if a user only has a Mail_Location.
> Show Office Info for Users who Only Have Mail_Location -- CTS Ticket 169936

- src/components/Profile/components/OfficeInfoList/index.jsx
The code for showing `BuildingDescription` in Office Info List was broken on My Profile.
The `BuildingDescription` and `OnCampusRoom` were put in parentheses. I believe the intent was to show the two values separated by a comma (as is done on public profile). However, the parentheses were acting as the Grouping operator, which means only the `OnCampusRoom` was rendered. I have replaced this with a template literal that displays both values separated by a comma.
> fix: display building description on my profile

- src/components/Profile/components/MembershipsList/MembershipsList.module.scss
Fixed the color of the my profile involvements text for dark mode on mobile, changing the color from "--mui-palette-neutral-light" to "--mui-palette-primary-contrastText".
> Fixed my profile involvements text on mobile dark mode

- src/views/About/contributors.json
- added appropriate graduation years for students of the Summer 2023 Computer Science Practicum in the About page
> add graduation years for summer practicum 2023

- src/components/Profile/components/VictoryPromise/components/GraphDisplay.tsx
Setting colors[index] = Colors[key] on line 26 set colors[index] = var(--mui-palette-error-main, #B53228), which is why it kept setting the colors to black.
How I fixed: 
- Used RegEx to pull out the hex from var(--mui-palette-error-main, #B53228), or returned empty string which takes care of the case where match returns null.
- Added a check to return black (#000000) if the match function returns an empty string, else return the appropriate colors.
Works for all combinations of color modes and screen displays.
> Fix Broken Victory Promise Graph to have Color

- src/components/Profile/components/SchedulePanel/index.tsx
The starting status of the schedule accordion was closed and line 33 was giving a warning. After editing line 33 the problem seems to be fixed, it displays no warnings and after clearing my cache, the starting status seems to be open. If this seems inefficient or could possibly cause bugs I would appreciate another approach.
> Fixed Starting Status

- src/views/About/index.jsx
It seems that on the about page, in the section where it states what students have worked on for 360, there was "(coming soon)" before the brief description about RECIM, since RECIM is now completed and implemented into 360 I removed the "(coming soon)" text from the About section.
> took-off-coming-soon-text-for-recim

- .env.development
- src/components/Header/components/NavAvatarRightCorner/index.jsx
An issue was mentioned in the Triage board where when hovering over the profile icon in the header of Gordon 360 it's alternate text only read "More". I changed the aria label in "src/components/Header/components/NavAvatarRightCorner/index.jsx" to say "My Profile" then tested it with a screen reader.
Fixes #2134
> Updated Header Profile Button Alt text for screen reader

- .env.development
- src/components/Profile/components/PersonalInfoList/components/UpdatePlannedGraduationYear/UpdatePlannedGradYear.module.scss
- src/components/Profile/components/PersonalInfoList/components/UpdatePlannedGraduationYear/index.jsx
- src/components/Profile/components/PersonalInfoList/index.jsx
Updated the "NOTES" on the MyProfile page for planned graduation date according to Dr. Tuck's suggestions on https://github.com/gordon-cs/gordon-360-api/issues/730 (I couldn't find a way to link it since it was closed and then reopened later).
This is what the changes look like.
> Update information for the planned graduation year on MyProfile page

- src/components/Profile/components/MembershipsList/components/MembershipInfoCard/index.jsx
- src/views/InvolvementsAll/components/InvolvementsGrid/index.jsx
- src/views/News/components/NewsItem/index.jsx
- src/views/PeopleSearch/components/PeopleSearchResult/index.tsx
- src/views/RecIM/components/List/Listing/index.jsx
- src/views/RecIM/views/Home/index.jsx
Add the `loading="lazy"` attribute to `img` components, so that the browser can delay loading images that are not yet in the viewport (i.e. haven't been scrolled into the visible section of the page). See [the `loading` attribute of the `img` HTML element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#loading) for more info.
PS: This attribute is not yet well supported on Firefox. Also, for some reason, the MUI Avatar component is not respecting the loading attribute in the for the img slot props. Nevertheless, this serves as a great progressive enhancement for the browsers/components that employ it, and won't cause any issues in cases where it isn't supported.
> Lazy load images when sensible

- src/components/EventList/components/EventItem/index.jsx
Related to #2133 and #2135 
Can now expand an event using the enter key **BUT** anytime you press enter while focused on an event it opens or closes it no matter what. So if you tab to "Add to Calendar" but press enter it just closes the event.
You can however press space while focused on "Add to Calendar" and that doesn't close the event. So it's not perfect, but you can at least open the event now.
> Make Enter Key Expand Event

- src/components/Profile/components/PersonalInfoList/components/UpdatePlannedGraduationYear/index.jsx
- src/views/PeopleSearch/components/SearchFieldList/components/SearchField/index.tsx
Related to https://github.com/gordon-cs/gordon-360-api/issues/730
- Fixed the link color from purple to GordonBlue by switching from an <a> tag to Link Component
- Added indicator to SearchField Component to allow the default menu item to be "None" instead of "All" which is more applicable in this case, see below...
I could also change it to be set as "Blank" if that describes it better.
> Fix PlanGradYear Link Color and Default Value

- src/views/RecIM/components/Forms/InviteParticipantForm/index.jsx
Bug where participant search box was incredibly small
Issue:
https://github.com/gordon-cs/gordon-360-ui/issues/2279
> [Rec-IM] Fix tiny search box

- src/views/InvolvementsAll/components/Requests/index.jsx
Resolves Issue #2022 , when there is no membership request sent, it is automatically closed but when there is a request sent it is automatically open.
> collapse membership requests when nothing to do

- src/components/Header/index.jsx
Reference #2132 
Top navigation tabs were inaccessible via keyboard, now they work like before...
- Hitting tab once focuses the page tabs, and then you can use the arrow keys to move focus within the tabs. 
- Hitting tab again jumps focus to the people search box. 
- Shift+tab will take you back to the tabs.
This does not break any of the other page tab functionality (still highlights and underlines correct icon when on the corresponding page).
> Make Top Tabs Accessible

- src/views/Events/index.jsx
Changed the "Attended CL&W" Button to link to the iAttended page (same as the "Links" page).
> Changed Attended CL&W Link on Events Page

- src/components/Profile/components/SchedulePanel/components/ScheduleCalendar/ScheduleCalendar.scss
- src/components/Profile/components/SchedulePanel/components/ScheduleCalendar/index.tsx
There were issues with the text display for quad classes and I was able to fix it by having the size of the text shrink when the screen gets smaller. I also have the location display on a new line and instead of it showing 'ONLN ASY' we decided it would be easier to understand if it just said 'ASYNC' and it fit on the screen better. I also eliminated the spaces between the course and course code, MAT 210 -> MAT210. This is now more consistent with how it is printed everywhere else throughout Gordon. I also added an else if to account for courses like Discovery that have a room number and location of null. Amos previously mentioned that null refers to an object, which is true but the best way I found to prevent it from printing 'null null' was the else if statement that I added.
#2287
> Schedule visual bugs s24

- src/components/Header/Header.module.scss
Reference #2132 
When someone is not logged in/authenticated the disabled top tabs (People and Rec-IM) now pass contrast tests. This is what they look like now...
When on dark mode tabs were the same color, now they look like this...
The difference isn't fairly obvious from the enabled tabs but it at least passes the contrast checker.
> Fix Disabled Top Tab Contrast

- src/components/Header/index.jsx
- src/components/Nav/components/NavLinks/index.jsx
Finishes #580 
Added the Guest Transcript to the side navigation bar for users that aren't logged in, looks like this...
Talked with Amos and adding a guest transcript button to the header would make it too cluttered. 
Once you log in it disappears from the side navigation bar. And if you are on the transcript page when you log in then it just changes to your personal transcript.
I also changed the dialog box content to more accurately reflect what the user needs to do, and added a break to just make it look better. Looks like this...
Mobile:
> Add Guest Transcript

- src/components/Nav/components/NavLinks/index.jsx
Switch guest transcript button to show only for users who aren't logged in. Was showing for logged in users... (Whoops).
> Guest Transcript Button for Logged Out Only

- src/views/Home/components/DaysLeft/index.jsx
Train does not retrieve the current or correct dates for the progress bar to work. This means that to test it correctly you need to be on PROD, to minimize clutter and keep train looking nice I added logic to not display it when using train.
> Hides Progress Bar on Train

- src/components/Profile/components/SchedulePanel/index.tsx
For a someone without a schedule like an athletic coach, they will see the schedule tab and a small drop-down menu with unreadable text inside. I removed the schedule tab entirely if the user has had no courses past or present, the schedule will only display on the users profile if they have been a part of at least one course. I also made the title of the schedule tab say 'Course Schedule' instead of just 'Schedule' this will hopefully add a little more clarity for people such as athletes who might be looking for practice times or any other reason.
[#2324](https://github.com/gordon-cs/gordon-360-ui/issues/2324)
> Removes schedule for non student/teachers

- src/components/Profile/components/PersonalInfoList/PersonalInfoList.module.scss
- src/components/Profile/components/PersonalInfoList/index.jsx
- src/components/Profile/components/SchedulePanel/ScheduleHeader.module.scss
- src/components/Profile/components/SchedulePanel/index.tsx
This centers the text in every tab on the profile page when the screen gets smaller. This adds consistency and looks overall cleaner and more uniformed.
[#2325](https://github.com/gordon-cs/gordon-360-ui/issues/2325)
> Centers all text when screen gets smaller

- src/components/Nav/components/NavLinks/index.tsx
When a user is logged in, the People and Rec-IM tabs are disabled in the hamburger menu...
Now the user is able to navigate through the hamburger menu for both people and RECIM the rest worked prior to this issue so those were left alone. #2329
> Fix People Rec-IM Tab Error

- src/components/NavButton/index.tsx
Fixes #2285 
Can now navigate tabs expanded from hamburger with keyboard correctly. Only takes one tab key press to go from one item to another. When tab is highlighted and enter key is pressed you now go to the page.
> Fix Hamburger Tab Navigation

- src/services/user.ts
This fixes a bug for users without a birthday, introduced by https://github.com/gordon-cs/gordon-360-api/pull/1052 which sets a default birthday of 1/1/1800 for users without a birthday, so they don't get a message on Jan 1.
This also fixes a bug introduced in in https://github.com/gordon-cs/gordon-360-ui/pull/2317, which accidentally switched from checking for matching month and day to matching full birthdate.  (That effectively turned off the birthday message, since nobody logs in until years after they are born.)
Tested by editing gordon-cs\gordon-360-api\Gordon360\Services\ProfileService.cs, line 83, to set various default dates (like today, and this date last year), then running the test API server to test the UI.
> Fix 2 birthday bugs: day born vs. birthday, and no birthday

- package-lock.json
- package.json
Material-ui/* was deprecated a while ago when updating to MUI5. However, it appears that material-ui/core was not deprecated and with the update to React 18 has now caused package conflicts on new `npm install`s. This PR fully removes material-ui/core and updates remaining @mui/material @mui/styles.
> remove material-ui, replaced with @mui

- src/components/Header/index.tsx
Fixes #1390 
Allows all header tabs to be accessed via keyboard by pressing the tab key. The conversation about this was a while ago, so I'm not sure if we still want every header tab to be accessible by pressing the enter key or if the original functionality (just using the arrow keys to navigate the header tabs) is good. If the original functionality is fine then I will just close the issue referenced.
> Fix Header Tab Keyboard Navigation

- src/components/Nav/components/NavLinks/index.tsx
Fixes #2337 
Clicking the appearance button to change color modes now stays on your current page rather than navigating to the home page.
> Clicking Appearance Button Stays on Current Page

- src/components/Profile/components/VictoryPromise/components/GraphDisplay.tsx
When  a user had zero victory promise points the graph wont display, that is fixed but apparently the graph cannot be changed to its original size, there are two sizes I was able to get and I am curious of your thoughts. #2342
> graph-does-display

- src/components/Profile/components/PersonalInfoList/index.jsx
- src/services/user.ts
Adjusted API route name from `/api/profiles/mailbox-combination` to `/api/profiles/mailbox-information` since other information than just the combination may be present in the JSON received.  This change is probably not important enough to warrant a change on its own, but matches changes in the API that were made to clean things up while removing an unnecessary thrown exception.
See PR 1056 in gordon-360-api
> S24 mailbox information

- src/views/Home/components/DiningBalance/index.jsx
I have gotten the link for metz and the new dining services so now That link is clickable for Todays Menu on dining balance. Website is mainly operational, some things will be upgraded but the link should work no matter what. 
https://github.com/orgs/gordon-cs/projects/15/views/1?pane=issue&itemId=65814033
> new-menu-linked-on-dining-balance

- src/views/Events/index.jsx
Sets default filter to "2 Weeks" and adds a card header at the bottom of the event list to remind the user of the current time filter being used.
For "2 Weeks" default filter
Mobile:
For "All" events
Mobile:
> Add Filter Reminder for Events Page

- src/views/Links/index.jsx
- Added descriptors for Criterion and 25Live on the Links page
> s24-add descriptors for links

- src/views/Events/index.jsx
Changed Filter names to be more descriptive. "Filter" to "Event Types" and "Time Filters" to "Time Window"
Added HashLinks to Events Page so you can jump from top to bottom and vice versa.
> HashLinks to Top/Bottom Events Page

- src/components/Profile/components/Identification/components/SocialMediaLinks/index.jsx
- src/components/Profile/components/PersonalInfoList/components/UpdatePhoneDialog/index.jsx
- src/components/Profile/components/PersonalInfoList/components/UpdatePlannedGraduationYear/index.jsx
Added more descriptive labels for pencil edit buttons. Used to be just "button" now they say "Update planned graduation year button"...
> Give Pencil Icon Buttons Labels for Screen Reader

- src/views/Help/index.jsx
The Return to Top of Page works as intended and makes it easier for users to go back to the top of the page after using an anchor to go to certain titles on the Help Page, Only problem is the ident i can't figure it out but I got the spacing out.
> Return to top of page hashlink-help-page

- src/services/recim/participant.ts
- src/views/RecIM/components/List/Listing/index.jsx
Per CTS Ticket #175058, Shows a participant's Hall when it is present. The Hall field is only included in a Participant's data when the viewer is an Admin, as enforced in gordon-cs/gordon-360-api#1069.
> RecIM: Display team participant's Hall when present

- src/services/auth.ts
This hotfix addresses a bug introduced in #2377 that prevented our authentication code from ever redirecting to MS for authentication when an access token was requested and interaction is required.
> Hotfix: redirect for auth exactly once

- src/views/Housing/components/RDView/index.jsx
- src/views/Housing/components/RDView/updateTasks/index.jsx
- src/views/Housing/index.jsx
Changes made in PR:
- Changed the housing index.jsx to go to the RD View only if you are faculty ( We can change this when we make a group for RD's). 
- Created an RDView folder within the housing/components folder. This new folder is where all of the RDView components will go as well as where the index.jsx for the RD View is.
- Created a card to edit documents in he RD View which has links to SharePoint and our room range program, as well as a dialog box that pops up when you click the edit button next to "RA/AC Task List". The code for the edit button is in a folder within RDView called components which will hold any components needed for the RD View.
- The code to edit tasks is just the dialog box that pops up, you cannot type anything yet.
> WMR RD View Setup

- src/views/CampusSafety/index.tsx
Button does not navigate anywhere since I need to figure out how to do navigation like the Rec-IM page.
> Added Lost and Found Section to Safety Page

- .env.development
- src/services/lostAndFound.ts
- src/views/CampusSafety/views/LostAndFound/components/DeleteConfirmation/DeleteConfirmation.module.scss
- src/views/CampusSafety/views/LostAndFound/components/DeleteConfirmation/index.tsx
- src/views/CampusSafety/views/LostAndFound/index.tsx
Sets an item's status to deleted and moves it to past reports, but does not include the confirmation pop-up. PR also contains status update front-end service.
API: https://github.com/gordon-cs/gordon-360-api/pull/1083
> Delete Report Button 

- src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/components/MissingItemReportData/MissingItemReportData.module.scss
- src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/components/MissingItemReportData/index.tsx
Improved the styling and content of the admin missing item report details page to be more in line with the Figma design, and have all the needed content.
> L&F Report Details Page Improvements

- src/services/lostAndFound.ts
- src/views/CampusSafety/views/LostAndFoundAdmin/LostAndFoundAdmin.module.scss
- src/views/CampusSafety/views/LostAndFoundAdmin/index.tsx
- src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/components/MissingItemReportData/MissingItemReportData.module.scss
- src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/components/MissingItemReportData/index.tsx
- src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/index.tsx
[Admin Actions Design Doc](url)
API Changes in [API #1104](https://github.com/gordon-cs/gordon-360-api/pull/1104)
Can now record items as checked agains the list of found items.  This also updates the status to "found" if the user says they've found it.
Form for cross-checking action:
Now the "Last Checked" date is calculated based on the most recent "Checked" action on a report.  Also the color of the date is set based on how old it is.
Updated the admin landing page.
New Appearance:
> Admin Landing Page + Admin Actions Checked Action

- src/views/CampusSafety/views/LostAndFound/components/DeleteConfirmation/DeleteConfirmation.module.scss
- src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/components/confirmReport/index.tsx
- src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/index.tsx
- src/views/CampusSafety/views/LostAndFound/views/MissingItemEdit/components/confirmReport/index.tsx
- src/views/CampusSafety/views/LostAndFound/views/MissingItemEdit/index.tsx
The missing item edit and create forms now use a much more advanced date picker component.  I had to do a bunch of custom styling to fix dark mode contrast issues.  This fixes the bug where the field would display mm/dd/yyyy on Chrome, and is also a much nicer date picker, that actually uses the MUI theme colors (so will switch to dark mode).
This is actually a site wide issue, on all of the pages that use the ```TextField``` component, because of how dark mode was set up.  I found a workaround using the ```sx``` prop, and applied it to our two general user forms (create and edit).  Now the label text doesn't change to a (far too) dark color when each form field is selected by the user.
Custom styling:
You can now edit the stolen description, to add more details, etc.
The missing item …
> Various Bugfixes

- src/theme.ts
This has been an issue for several years now.  Figured I'd finally fix it, since it's kinda annoying, and relatively easy to fix :).  Added a style override to the theme, fixing the colors of the label and border elements when focusing form fields.
> Dark Mode Form Label Text Contrast Fix

- src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/MissingItemList.module.scss
- src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/index.tsx
On desktop, the header bar on the list of missing item reports will now stick to the top of the screen when the user scrolls down.  The CSS workaround I had to do to make this work is a little stupid, but it works.
Also, please test on Safari, and I will cry when it breaks catastrophically 🤞
> Sticky List Header

- src/views/CampusSafety/index.tsx
- src/views/Links/index.jsx
Code copied directly from people search, super quick fix.
Button on links page disabled:
Direct navigation to any routes yields:
> LostAndFound No Longer Visible in Guest Mode

- src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/MissingItemList.module.scss
- src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/components/ReportItemPageOther/index.tsx
- src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/index.tsx
Added custom date picker to admin report for others.
Added status chips to the admin reports list view.
> DatePicker and Status Chips on Admin Pages

- src/services/lostAndFound.ts
This fixes the issue with calling the POST route in production returning 404.  Not sure how we missed this, apparently this route call works fine in the development environment, but as soon as you build and run for production, it doesn't work with the leading /.  Not sure how we missed this inconsistency, but it's fixed now :).
Thanks @EjPlatzer for spotting that!
> Fix for Issue with Creating Missing Item Reports in Production

- src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/MissingItemList.module.scss
Fixes this CSS issue with the header bar in the production build environment.
> HOTFIX for sticky header padding on admin list Page.

- src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/components/confirmReport/index.tsx
- src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/index.tsx
Button in bottom right used to be "SUBMIT"
Used to say "File a Report" in the header and then "Confirm the Details of your Report" below outside of the header.
> Clarified Wording when Creating a Report

- src/views/ResLife/components/RDView/components/RoomRanges/index.jsx
- src/views/ResLife/components/ResidentView/components/MyRA/index.jsx
if a resident was in B20 'B20' was sent to the API causing some errors. Now only ints are sent to the API
> Updates to my hall to remove characters when calling the api

- src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/components/confirmReport/index.tsx
- src/views/CampusSafety/views/LostAndFound/views/MissingItemEdit/components/confirmReport/index.tsx
- src/views/CampusSafety/views/LostAndFound/views/MissingItemEdit/index.tsx
Button text now more clear.  Fixes Issue #134.
OLD:
NEW:
> Confirmation Page Button Text Clarity

- src/views/CampusSafety/views/LostAndFound/views/MissingItemEdit/index.tsx
- src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/components/ReportItemPageOther/index.tsx
Changed admin missing item form to match the lowercase formatting of the item category from the general user form and changed the edit form to be case insensitive so that previous upper case entries don't cause issues.
> Fixed case-sensitive issues for item categories

- src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/components/MissingItemReportData/index.tsx
Fixed the admin side item view so that the location lost text wraps to another line instead of cutting off text
> Made location lost wrap to another line

- src/views/ResLife/components/ResidentView/components/MyRA/index.jsx
* When the page is loading, the loading information has been updated so that no field is empty
> wmr - Small UI Update

- package-lock.json
- package.json
- src/components/Profile/components/SchedulePanel/components/ScheduleCalendar/index.tsx
- src/services/event.ts
- src/services/news.ts
- src/views/ApartmentApp/components/StaffMenu/index.jsx
- src/views/ApartmentApp/components/StudentApplication/components/ApplicationDataTable/index.jsx
- src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/components/MissingItemReportData/index.tsx
Finally removing `luxon` as a dependency, since we've decided to use the native `Date` object along with `date-fns` instead. 
There were a few lingering uses of `luxon` that were easily replaced with the above combination. 
The main blocker to removing `luxon` in the past was lack of support in `react-big-calendar` for localization via `date-fns`, but since they have added a `dateFnsLocalizer`, that is no longer an issue.
Now that [`Temporal`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Temporal) has been added to the spec, we will eventually want to start adopting that as the preferred (and much nicer and safer) native method of working with dates and times in JS. However, browser support is still a long ways off for `Temporal`, so there's no rush to …
> Remove luxon

- .env.development
- src/services/residentLife/RA_Checkin.ts
- src/views/ResLife/components/RAView/index.jsx
As usual RA will have a button to check in to their shift
When the RA is checked in the button text will change asking if they want to check in to additional halls. Previously the button would be disabled
When clicked any halls the RA is currently checked in to will be checked and disabled as they are unable to check out of a hall and unable to check into a hall they are already in.
The API call will only deal with the newly selected halls
> Added RA option to check in to additional halls

- src/views/LostAndFound/views/Admin/index.tsx
Removed the "Under Construction" text as it's no longer under construction :)
Looks like this now...
> Remove Under Construction Text

- src/views/ResLife/components/RDView/components/TaskList/index.jsx
When editing a task you are stuck in edit mode until you save changes
This PR just adds the cancel option
> Added option to cancel when editing a task

- src/views/LostAndFound/views/FoundItemConfirm/index.tsx
Looks like this (on the far left) (matches the Figma now):
Also seems like the columns are broken for the data cells :)
> Fixed Details Button Contrast on CrossCheck Page

- src/components/Profile/components/PersonalInfoList/index.tsx
There are cases where people who are not (or more commonly are no longer) students have an assigned mailbox. In those cases, when the person is viewing their profile, we should show them their mailbox combination, since the mailbox is still assigned to them.
Depends on gordon-cs/gordon-360-api#1199
> Show mailbox combination (when present) on my profile, regardless of user's person type

- src/components/Profile/components/PersonalInfoList/index.tsx
- src/components/Profile/index.tsx
- src/components/Snackbar/index.tsx
- src/services/user.ts
Fix #2107 
Shows registrar's official intent to graduate term as private information if Graduation Application is submitted, otherwise displays estimated graduation term or a warning to fill in their graduation application if it is less than a year before their planned/estimated graduation date.
Displays a snackbar warning when entering their own profile page to fill in their graduation application if it is less than a year before their planned/estimated graduation date.
Notes on the bottom of the profile page has also been updated to guide students in their graduation process.
Requires https://github.com/gordon-cs/gordon-360-api/pull/1206 to obtain graduation data from the database.
> S25 graduation flag

- src/components/Profile/components/PersonalInfoList/index.tsx
This PR makes two cosmetic changes to the personal information card in the personal profile.
Alumni viewing their profile have a "UPDATE INFORMATION" button at the top of the personal information card.  Clicking on this opens a form they can use to request changes to information in the alumni database.  Submitting the form seems to generate an email (hopefully to the alumni office) requesting the changes.
At the bottom of the personal information card there is a note shown to faculty and staff that explains that the Criterion site should be used to make changes to personal data.
To make a clearer distinction between these two features, particularly for staff who are also alumni, the button label is changed to UPDATE ALUMNI INFORMATION and the note for facstaff is now prefaced with …
> Re-label alumni information update button and fac/staff update instructions

- src/views/About/contributors.json
Several recent senior projects have contributed features to 360 but these were not included in the list of contributors.  This PR adds (most of) them.
> S25 add senior projects to about page

- src/services/academicTerm.ts
`export const getCurrentTerm = (): Promise<AcademicTerm> => http.get('academicterm/currentterm');`
removed ' / ' from ' `/academicterm/currentterm`
> s25 small fix fetching currentTerm
